<?php

$jobs = [
    [
        'data' => [
            'key' => 'swordsman',
            'name' => '剣士',
            'rank' => 'normal',
            'description' => '剣一本で世界と向き合う。防御を固め、堅実に前進する近接職の王道。',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 110,
            'atk_rate' => 100,
            'def_rate' => 120,
            'mag_rate' => 110,
            'spr_rate' => 90,
            'spd_rate' => 100,
            'luck_rate' => 110,
            'is_hidden' => false,
            'sort_order' => 10,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 20,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'warrior',
            'name' => '戦士',
            'rank' => 'normal',
            'description' => '力こそが正義。厚い体躯と荒々しい一撃で、正面から敵を圧倒する豪腕の戦士。',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 120,
            'atk_rate' => 90,
            'def_rate' => 130,
            'mag_rate' => 110,
            'spr_rate' => 80,
            'spd_rate' => 90,
            'luck_rate' => 100,
            'is_hidden' => false,
            'sort_order' => 20,
            'bonus_hp' => 2,
            'bonus_mp' => 20,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'thief',
            'name' => '盗賊',
            'rank' => 'normal',
            'description' => '影に潜み、隙を突く。敵が気づく前に、勝負はすでに終わっている。',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 100,
            'atk_rate' => 100,
            'def_rate' => 110,
            'mag_rate' => 90,
            'spr_rate' => 90,
            'spd_rate' => 90,
            'luck_rate' => 130,
            'is_hidden' => false,
            'sort_order' => 30,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 20,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'archer',
            'name' => '弓使い',
            'rank' => 'normal',
            'description' => '冷静な眼と確かな腕が、急所を撃ち抜く一矢を生む。距離が、最大の武器だ。',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 100,
            'atk_rate' => 100,
            'def_rate' => 120,
            'mag_rate' => 90,
            'spr_rate' => 90,
            'spd_rate' => 100,
            'luck_rate' => 120,
            'is_hidden' => false,
            'sort_order' => 40,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 20,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'fighter',
            'name' => '格闘家',
            'rank' => 'normal',
            'description' => '武器など不要。己の拳と速さこそが最強の凶器だと、体が証明してみせる。',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 110,
            'atk_rate' => 90,
            'def_rate' => 120,
            'mag_rate' => 100,
            'spr_rate' => 80,
            'spd_rate' => 100,
            'luck_rate' => 130,
            'is_hidden' => false,
            'sort_order' => 50,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 10,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 10,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'mage',
            'name' => '魔法使い',
            'rank' => 'normal',
            'description' => '呪文一つで世界を書き換える。知恵と魔力の前に、剣も鎧も意味を持たない。',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 90,
            'atk_rate' => 130,
            'def_rate' => 80,
            'mag_rate' => 90,
            'spr_rate' => 130,
            'spd_rate' => 120,
            'luck_rate' => 110,
            'is_hidden' => false,
            'sort_order' => 60,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 20,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'priest',
            'name' => '僧侶',
            'rank' => 'normal',
            'description' => '癒しこそ、最大の戦力。倒れた仲間を何度でも立たせる者が、最後に勝つ。',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 100,
            'atk_rate' => 120,
            'def_rate' => 90,
            'mag_rate' => 100,
            'spr_rate' => 120,
            'spd_rate' => 130,
            'luck_rate' => 90,
            'is_hidden' => false,
            'sort_order' => 70,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 20,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'merchant',
            'name' => '商人',
            'rank' => 'normal',
            'description' => '金は力だ。情報と財を操り、戦場でさえ有利な取引を成立させる。',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 110,
            'atk_rate' => 100,
            'def_rate' => 100,
            'mag_rate' => 110,
            'spr_rate' => 100,
            'spd_rate' => 110,
            'luck_rate' => 100,
            'is_hidden' => false,
            'sort_order' => 80,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 20,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'magic_swordsman',
            'name' => '魔法剣士',
            'rank' => 'middle',
            'description' => '剣閃と魔力が一体となる瞬間、敵はどちらを防げばいいか分からなくなる。',
            'max_job_level' => 10,
            'hp_rate' => 120,
            'mp_rate' => 120,
            'atk_rate' => 140,
            'def_rate' => 120,
            'mag_rate' => 140,
            'spr_rate' => 120,
            'spd_rate' => 120,
            'luck_rate' => 120,
            'is_hidden' => false,
            'sort_order' => 90,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 20,
            'bonus_def' => 0,
            'bonus_mag' => 25,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '剣士',
            '魔法使い',
        ],
    ],
    [
        'data' => [
            'key' => 'paladin',
            'name' => '聖騎士',
            'rank' => 'middle',
            'description' => '盾は守るためにある——そして守った先に、聖なる一撃が来る。',
            'max_job_level' => 10,
            'hp_rate' => 140,
            'mp_rate' => 130,
            'atk_rate' => 120,
            'def_rate' => 150,
            'mag_rate' => 110,
            'spr_rate' => 160,
            'spd_rate' => 90,
            'luck_rate' => 100,
            'is_hidden' => false,
            'sort_order' => 100,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 25,
            'bonus_mag' => 0,
            'bonus_spr' => 20,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '剣士',
            '僧侶',
        ],
    ],
    [
        'data' => [
            'key' => 'samurai',
            'name' => '侍',
            'rank' => 'middle',
            'description' => '刃は己の意志の延長。抜かずとも勝ち、抜けば一瞬で決める。',
            'max_job_level' => 10,
            'hp_rate' => 120,
            'mp_rate' => 100,
            'atk_rate' => 170,
            'def_rate' => 110,
            'mag_rate' => 90,
            'spr_rate' => 100,
            'spd_rate' => 160,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 110,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 25,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 20,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '剣士',
            '弓使い',
        ],
    ],
    [
        'data' => [
            'key' => 'tactician',
            'name' => '軍師',
            'rank' => 'middle',
            'description' => '勝負は戦う前から決まっている。全てを見通す知略が、無双の武器となる。',
            'max_job_level' => 10,
            'hp_rate' => 120,
            'mp_rate' => 120,
            'atk_rate' => 120,
            'def_rate' => 130,
            'mag_rate' => 110,
            'spr_rate' => 130,
            'spd_rate' => 120,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 120,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 20,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 25,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '剣士',
            '商人',
        ],
    ],
    [
        'data' => [
            'key' => 'gladiator',
            'name' => '剣闘士',
            'rank' => 'middle',
            'description' => '闘技場で磨かれた本物の強さ。観客の歓声が消えても、剣の切れ味は残る。',
            'max_job_level' => 10,
            'hp_rate' => 140,
            'mp_rate' => 90,
            'atk_rate' => 170,
            'def_rate' => 130,
            'mag_rate' => 80,
            'spr_rate' => 100,
            'spd_rate' => 140,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 130,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 45,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '剣士',
            '戦士',
        ],
    ],
    [
        'data' => [
            'key' => 'berserker',
            'name' => '狂戦士',
            'rank' => 'middle',
            'description' => '傷を受けるほど、燃え上がる。限界の向こうに、本物の破壊力が待っている。',
            'max_job_level' => 10,
            'hp_rate' => 140,
            'mp_rate' => 90,
            'atk_rate' => 180,
            'def_rate' => 100,
            'mag_rate' => 90,
            'spr_rate' => 90,
            'spd_rate' => 150,
            'luck_rate' => 160,
            'is_hidden' => false,
            'sort_order' => 140,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 45,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '戦士',
            '格闘家',
        ],
    ],
    [
        'data' => [
            'key' => 'guardian_knight',
            'name' => '守護騎士',
            'rank' => 'middle',
            'description' => '仲間が背中にいる限り、一歩も退かない。その盾こそが、最強の矛だ。',
            'max_job_level' => 10,
            'hp_rate' => 160,
            'mp_rate' => 100,
            'atk_rate' => 130,
            'def_rate' => 180,
            'mag_rate' => 80,
            'spr_rate' => 130,
            'spd_rate' => 90,
            'luck_rate' => 130,
            'is_hidden' => false,
            'sort_order' => 150,
            'bonus_hp' => 25,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 20,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '戦士',
            '僧侶',
        ],
    ],
    [
        'data' => [
            'key' => 'mercenary',
            'name' => '傭兵',
            'rank' => 'middle',
            'description' => '報酬さえ払えば、どんな戦場にも立つ。その代わり、確実に仕事をやり遂げる。',
            'max_job_level' => 10,
            'hp_rate' => 150,
            'mp_rate' => 90,
            'atk_rate' => 160,
            'def_rate' => 140,
            'mag_rate' => 80,
            'spr_rate' => 100,
            'spd_rate' => 130,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 160,
            'bonus_hp' => 20,
            'bonus_mp' => 0,
            'bonus_str' => 25,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '戦士',
            '商人',
        ],
    ],
    [
        'data' => [
            'key' => 'ninja',
            'name' => '忍者',
            'rank' => 'middle',
            'description' => '音もなく現れ、気づかれる前に消える。存在すること自体が、既に勝利だ。',
            'max_job_level' => 10,
            'hp_rate' => 110,
            'mp_rate' => 110,
            'atk_rate' => 140,
            'def_rate' => 100,
            'mag_rate' => 110,
            'spr_rate' => 100,
            'spd_rate' => 180,
            'luck_rate' => 140,
            'is_hidden' => false,
            'sort_order' => 170,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 45,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '盗賊',
            '格闘家',
        ],
    ],
    [
        'data' => [
            'key' => 'sniper',
            'name' => '狙撃手',
            'rank' => 'middle',
            'description' => '息を止め、引き金を引く。その一瞬に全てが凝縮される、静寂の暗殺者。',
            'max_job_level' => 10,
            'hp_rate' => 110,
            'mp_rate' => 110,
            'atk_rate' => 160,
            'def_rate' => 100,
            'mag_rate' => 100,
            'spr_rate' => 100,
            'spd_rate' => 160,
            'luck_rate' => 160,
            'is_hidden' => false,
            'sort_order' => 180,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 25,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 20,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '弓使い',
            '盗賊',
        ],
    ],
    [
        'data' => [
            'key' => 'magic_thief',
            'name' => '魔盗士',
            'rank' => 'middle',
            'description' => '魔力と暗器を組み合わせた予測不能の戦闘術。敵は何が来るか分からない。',
            'max_job_level' => 10,
            'hp_rate' => 100,
            'mp_rate' => 150,
            'atk_rate' => 90,
            'def_rate' => 90,
            'mag_rate' => 170,
            'spr_rate' => 140,
            'spd_rate' => 130,
            'luck_rate' => 130,
            'is_hidden' => false,
            'sort_order' => 190,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 25,
            'bonus_spr' => 0,
            'bonus_spd' => 20,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '盗賊',
            '魔法使い',
        ],
    ],
    [
        'data' => [
            'key' => 'traveling_merchant',
            'name' => '旅商人',
            'rank' => 'middle',
            'description' => '世界中を渡り歩き、誰も持っていない情報と財を手に入れる。旅こそが資産だ。',
            'max_job_level' => 10,
            'hp_rate' => 130,
            'mp_rate' => 120,
            'atk_rate' => 120,
            'def_rate' => 130,
            'mag_rate' => 120,
            'spr_rate' => 130,
            'spd_rate' => 120,
            'luck_rate' => 130,
            'is_hidden' => false,
            'sort_order' => 200,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 45,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '商人',
            '盗賊',
        ],
    ],
    [
        'data' => [
            'key' => 'monk',
            'name' => 'モンク',
            'rank' => 'middle',
            'description' => '鍛え抜かれた肉体と精神が一つになるとき、拳は神の領域に達する。',
            'max_job_level' => 10,
            'hp_rate' => 130,
            'mp_rate' => 110,
            'atk_rate' => 150,
            'def_rate' => 120,
            'mag_rate' => 100,
            'spr_rate' => 130,
            'spd_rate' => 150,
            'luck_rate' => 110,
            'is_hidden' => false,
            'sort_order' => 210,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 25,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 20,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '僧侶',
            '格闘家',
        ],
    ],
    [
        'data' => [
            'key' => 'magic_archer',
            'name' => '魔弓士',
            'rank' => 'middle',
            'description' => '矢に魔力を込め、射程の果てから必殺の一矢を放つ。逃げ場など存在しない。',
            'max_job_level' => 10,
            'hp_rate' => 100,
            'mp_rate' => 140,
            'atk_rate' => 130,
            'def_rate' => 100,
            'mag_rate' => 160,
            'spr_rate' => 110,
            'spd_rate' => 140,
            'luck_rate' => 120,
            'is_hidden' => false,
            'sort_order' => 220,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 20,
            'bonus_def' => 0,
            'bonus_mag' => 25,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '弓使い',
            '魔法使い',
        ],
    ],
    [
        'data' => [
            'key' => 'bard',
            'name' => '吟遊詩人',
            'rank' => 'middle',
            'description' => '歌が戦場を変える。その旋律に、敵は怯え、仲間は奮い立つ。',
            'max_job_level' => 10,
            'hp_rate' => 110,
            'mp_rate' => 130,
            'atk_rate' => 110,
            'def_rate' => 100,
            'mag_rate' => 120,
            'spr_rate' => 130,
            'spd_rate' => 130,
            'luck_rate' => 170,
            'is_hidden' => false,
            'sort_order' => 230,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 45,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '弓使い',
            '商人',
        ],
    ],
    [
        'data' => [
            'key' => 'bishop',
            'name' => '司祭',
            'rank' => 'middle',
            'description' => '神の言葉を武器に変える。祈りが、時に剣よりも深く敵を穿つ。',
            'max_job_level' => 10,
            'hp_rate' => 110,
            'mp_rate' => 160,
            'atk_rate' => 90,
            'def_rate' => 120,
            'mag_rate' => 160,
            'spr_rate' => 160,
            'spd_rate' => 110,
            'luck_rate' => 90,
            'is_hidden' => false,
            'sort_order' => 240,
            'bonus_hp' => 0,
            'bonus_mp' => 20,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 25,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '僧侶',
            '魔法使い',
        ],
    ],
    [
        'data' => [
            'key' => 'apothecary',
            'name' => '薬師',
            'rank' => 'middle',
            'description' => '毒も薬も、使い手次第。その知識が生死の境界線を塗り替える。',
            'max_job_level' => 10,
            'hp_rate' => 120,
            'mp_rate' => 130,
            'atk_rate' => 90,
            'def_rate' => 120,
            'mag_rate' => 130,
            'spr_rate' => 160,
            'spd_rate' => 100,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 250,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 25,
            'bonus_spd' => 0,
            'bonus_luk' => 20,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '商人',
            '僧侶',
        ],
    ],
    [
        'data' => [
            'key' => 'alchemist',
            'name' => '錬金術師',
            'rank' => 'middle',
            'description' => 'あらゆる素材を力に変える者。世界の法則すら、素材の一つに過ぎない。',
            'max_job_level' => 10,
            'hp_rate' => 110,
            'mp_rate' => 150,
            'atk_rate' => 100,
            'def_rate' => 110,
            'mag_rate' => 150,
            'spr_rate' => 130,
            'spd_rate' => 110,
            'luck_rate' => 140,
            'is_hidden' => false,
            'sort_order' => 260,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 25,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 20,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '商人',
            '魔法使い',
        ],
    ],
    [
        'data' => [
            'key' => 'hero',
            'name' => '勇者',
            'rank' => 'advanced',
            'description' => '伝説の名を背負い、それを超えていく。勇者の道に、終わりはない。',
            'max_job_level' => 10,
            'hp_rate' => 160,
            'mp_rate' => 140,
            'atk_rate' => 170,
            'def_rate' => 160,
            'mag_rate' => 140,
            'spr_rate' => 150,
            'spd_rate' => 150,
            'luck_rate' => 130,
            'is_hidden' => false,
            'sort_order' => 270,
            'bonus_hp' => 30,
            'bonus_mp' => 0,
            'bonus_str' => 30,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 30,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '魔法剣士',
            '聖騎士',
        ],
    ],
    [
        'data' => [
            'key' => 'sword_master',
            'name' => '剣聖',
            'rank' => 'advanced',
            'description' => '剣の道を極め、剣そのものになった者。その一閃に、宇宙が震える。',
            'max_job_level' => 10,
            'hp_rate' => 140,
            'mp_rate' => 120,
            'atk_rate' => 210,
            'def_rate' => 130,
            'mag_rate' => 100,
            'spr_rate' => 120,
            'spd_rate' => 190,
            'luck_rate' => 190,
            'is_hidden' => false,
            'sort_order' => 280,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 45,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 45,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '侍',
            '剣闘士',
        ],
    ],
    [
        'data' => [
            'key' => 'grand_sage',
            'name' => '大賢者',
            'rank' => 'advanced',
            'description' => '知は力を超える。世界の理を掌握した者の前に、不可能という言葉は存在しない。',
            'max_job_level' => 10,
            'hp_rate' => 120,
            'mp_rate' => 200,
            'atk_rate' => 100,
            'def_rate' => 130,
            'mag_rate' => 210,
            'spr_rate' => 200,
            'spd_rate' => 140,
            'luck_rate' => 100,
            'is_hidden' => false,
            'sort_order' => 290,
            'bonus_hp' => 0,
            'bonus_mp' => 30,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 30,
            'bonus_spr' => 30,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '司祭',
            '錬金術師',
        ],
    ],
    [
        'data' => [
            'key' => 'dark_knight',
            'name' => '暗黒騎士',
            'rank' => 'advanced',
            'description' => '深淵の力を鎧とし、禁じられた力で世界を切り拓く。痛みすら、燃料だ。',
            'max_job_level' => 10,
            'hp_rate' => 180,
            'mp_rate' => 120,
            'atk_rate' => 200,
            'def_rate' => 150,
            'mag_rate' => 130,
            'spr_rate' => 130,
            'spd_rate' => 140,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 300,
            'bonus_hp' => 45,
            'bonus_mp' => 0,
            'bonus_str' => 45,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '狂戦士',
            '聖騎士',
        ],
    ],
    [
        'data' => [
            'key' => 'golden_merchant',
            'name' => '黄金商人',
            'rank' => 'advanced',
            'description' => '富は武器を超える。世界を金で動かす者が、真の支配者だ。',
            'max_job_level' => 10,
            'hp_rate' => 150,
            'mp_rate' => 150,
            'atk_rate' => 150,
            'def_rate' => 150,
            'mag_rate' => 150,
            'spr_rate' => 150,
            'spd_rate' => 150,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 310,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 90,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '旅商人',
            '錬金術師',
        ],
    ],
    [
        'data' => [
            'key' => 'dragoon',
            'name' => '竜騎士',
            'rank' => 'advanced',
            'description' => '竜の咆哮を胸に、天高く舞い、地を揺るがす一撃を放つ。',
            'max_job_level' => 10,
            'hp_rate' => 170,
            'mp_rate' => 110,
            'atk_rate' => 180,
            'def_rate' => 160,
            'mag_rate' => 100,
            'spr_rate' => 120,
            'spd_rate' => 180,
            'luck_rate' => 180,
            'is_hidden' => false,
            'sort_order' => 320,
            'bonus_hp' => 30,
            'bonus_mp' => 0,
            'bonus_str' => 30,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 30,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '守護騎士',
            '狙撃手',
        ],
    ],
    [
        'data' => [
            'key' => 'war_god',
            'name' => '武神',
            'rank' => 'advanced',
            'description' => '神の域に達した武の体現者。その一撃は、山を割り、嵐を生む。',
            'max_job_level' => 10,
            'hp_rate' => 180,
            'mp_rate' => 100,
            'atk_rate' => 210,
            'def_rate' => 130,
            'mag_rate' => 90,
            'spr_rate' => 120,
            'spd_rate' => 200,
            'luck_rate' => 170,
            'is_hidden' => false,
            'sort_order' => 330,
            'bonus_hp' => 30,
            'bonus_mp' => 0,
            'bonus_str' => 30,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 30,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            'モンク',
            '狂戦士',
        ],
    ],
    [
        'data' => [
            'key' => 'phantom_king',
            'name' => '幻影王',
            'rank' => 'advanced',
            'description' => '実体と虚像の境を消し去る。敵が剣を振る頃には、既に幻の中にいる。',
            'max_job_level' => 10,
            'hp_rate' => 120,
            'mp_rate' => 140,
            'atk_rate' => 150,
            'def_rate' => 100,
            'mag_rate' => 150,
            'spr_rate' => 120,
            'spd_rate' => 220,
            'luck_rate' => 200,
            'is_hidden' => false,
            'sort_order' => 340,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 45,
            'bonus_luk' => 45,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '忍者',
            '魔盗士',
        ],
    ],
    [
        'data' => [
            'key' => 'machinist_king',
            'name' => '機工王',
            'rank' => 'advanced',
            'description' => '機械と魔導を融合させた最先端の戦闘術。理論が、最強の武器になる。',
            'max_job_level' => 10,
            'hp_rate' => 150,
            'mp_rate' => 150,
            'atk_rate' => 160,
            'def_rate' => 170,
            'mag_rate' => 170,
            'spr_rate' => 140,
            'spd_rate' => 120,
            'luck_rate' => 140,
            'is_hidden' => false,
            'sort_order' => 350,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 45,
            'bonus_mag' => 45,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '軍師',
            '錬金術師',
        ],
    ],
    [
        'data' => [
            'key' => 'priest_warrior',
            'name' => '神官戦士',
            'rank' => 'advanced',
            'description' => '鋼の体に神の加護を宿す。折れない盾と折れない信念が、全てを守り抜く。',
            'max_job_level' => 10,
            'hp_rate' => 170,
            'mp_rate' => 160,
            'atk_rate' => 140,
            'def_rate' => 170,
            'mag_rate' => 150,
            'spr_rate' => 210,
            'spd_rate' => 100,
            'luck_rate' => 100,
            'is_hidden' => false,
            'sort_order' => 360,
            'bonus_hp' => 30,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 30,
            'bonus_mag' => 0,
            'bonus_spr' => 30,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '守護騎士',
            '司祭',
        ],
    ],
    [
        'data' => [
            'key' => 'shadow_hunter',
            'name' => '影狩人',
            'rank' => 'advanced',
            'description' => '獲物は逃げられない。影の中から放たれる一撃が、世界最速の死神を作る。',
            'max_job_level' => 10,
            'hp_rate' => 130,
            'mp_rate' => 120,
            'atk_rate' => 190,
            'def_rate' => 110,
            'mag_rate' => 110,
            'spr_rate' => 110,
            'spd_rate' => 220,
            'luck_rate' => 210,
            'is_hidden' => false,
            'sort_order' => 370,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 30,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 30,
            'bonus_luk' => 30,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '狙撃手',
            '忍者',
        ],
    ],
    [
        'data' => [
            'key' => 'merchant_sage_king',
            'name' => '賢商王',
            'rank' => 'advanced',
            'description' => '知恵と財の両輪を持つ者。その判断は常に正しく、損をすることを知らない。',
            'max_job_level' => 10,
            'hp_rate' => 150,
            'mp_rate' => 170,
            'atk_rate' => 110,
            'def_rate' => 150,
            'mag_rate' => 160,
            'spr_rate' => 190,
            'spd_rate' => 110,
            'luck_rate' => 160,
            'is_hidden' => false,
            'sort_order' => 380,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 30,
            'bonus_spr' => 30,
            'bonus_spd' => 0,
            'bonus_luk' => 30,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '薬師',
            '旅商人',
        ],
    ],
    [
        'data' => [
            'key' => 'valzeria_hero',
            'name' => 'ヴァルゼリアの救世主',
            'rank' => 'legend',
            'description' => '時代を超え、語り継がれる名。その存在自体が、世界への希望だ。',
            'max_job_level' => 10,
            'hp_rate' => 180,
            'mp_rate' => 180,
            'atk_rate' => 180,
            'def_rate' => 180,
            'mag_rate' => 180,
            'spr_rate' => 180,
            'spd_rate' => 180,
            'luck_rate' => 180,
            'is_hidden' => true,
            'sort_order' => 390,
            'bonus_hp' => 30,
            'bonus_mp' => 10,
            'bonus_str' => 30,
            'bonus_def' => 30,
            'bonus_mag' => 30,
            'bonus_spr' => 30,
            'bonus_spd' => 30,
            'bonus_luk' => 10,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 5,
        ],
        'requirements' => [
            '勇者',
            '剣聖',
            '大賢者',
        ],
        'req_item' => '英雄の証',
    ],
    [
        'data' => [
            'key' => 'abyss_walker',
            'name' => '深淵歩き',
            'rank' => 'legend',
            'description' => '普通の者が踏み込めぬ場所を歩く。闇の向こうに何があるか——恐れるのは、己だけだ。',
            'max_job_level' => 10,
            'hp_rate' => 160,
            'mp_rate' => 160,
            'atk_rate' => 225,
            'def_rate' => 150,
            'mag_rate' => 225,
            'spr_rate' => 150,
            'spd_rate' => 200,
            'luck_rate' => 170,
            'is_hidden' => true,
            'sort_order' => 400,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 100,
            'bonus_def' => 0,
            'bonus_mag' => 100,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 5,
        ],
        'requirements' => [
            '暗黒騎士',
            '幻影王',
            '大賢者',
        ],
        'req_item' => '深淵の核',
    ],
    [
        'data' => [
            'key' => 'ancient_alchemist_king',
            'name' => '古代錬成王',
            'rank' => 'legend',
            'description' => '失われた古代の技術を完全習得した錬成の頂点。素材と法則が、意のままになる。',
            'max_job_level' => 10,
            'hp_rate' => 160,
            'mp_rate' => 225,
            'atk_rate' => 140,
            'def_rate' => 170,
            'mag_rate' => 225,
            'spr_rate' => 225,
            'spd_rate' => 140,
            'luck_rate' => 155,
            'is_hidden' => true,
            'sort_order' => 410,
            'bonus_hp' => 0,
            'bonus_mp' => 50,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 75,
            'bonus_spr' => 75,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 5,
        ],
        'requirements' => [
            '黄金商人',
            '機工王',
            '賢商王',
        ],
        'req_item' => '古代核',
    ],
    [
        'data' => [
            'key' => 'dragon_god',
            'name' => '蒼竜王',
            'rank' => 'legend',
            'description' => '竜の神格に目覚めた者。その力の前に、世界は色を失う。',
            'max_job_level' => 10,
            'hp_rate' => 225,
            'mp_rate' => 150,
            'atk_rate' => 225,
            'def_rate' => 200,
            'mag_rate' => 120,
            'spr_rate' => 170,
            'spd_rate' => 200,
            'luck_rate' => 150,
            'is_hidden' => true,
            'sort_order' => 420,
            'bonus_hp' => 60,
            'bonus_mp' => 0,
            'bonus_str' => 70,
            'bonus_def' => 70,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 5,
        ],
        'requirements' => [
            '竜騎士',
            '武神',
            '勇者',
        ],
        'req_item' => '竜神の鱗',
    ],
    [
        'data' => [
            'key' => 'time_space_king',
            'name' => '時空王',
            'rank' => 'legend',
            'description' => '時間と空間を支配する究極の存在。勝敗は、最初から決まっている。',
            'max_job_level' => 10,
            'hp_rate' => 150,
            'mp_rate' => 225,
            'atk_rate' => 120,
            'def_rate' => 140,
            'mag_rate' => 225,
            'spr_rate' => 180,
            'spd_rate' => 225,
            'luck_rate' => 175,
            'is_hidden' => true,
            'sort_order' => 430,
            'bonus_hp' => 0,
            'bonus_mp' => 40,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 60,
            'bonus_spr' => 0,
            'bonus_spd' => 100,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 5,
        ],
        'requirements' => [
            '大賢者',
            '幻影王',
            '機工王',
        ],
        'req_item' => '時空結晶',
    ],
];

