<?php

$jobs = [
    [
        'data' => [
            'key' => 'swordsman',
            'name' => '剣士',
            'rank' => 'normal',
            'description' => '近接バランスの底上げ',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 110,
            'atk_rate' => 100,
            'def_rate' => 120,
            'mag_rate' => 110,
            'spr_rate' => 90,
            'spd_rate' => 100,
            'luck_rate' => 110,
            'is_hidden' => false,
            'sort_order' => 10,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 20,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'warrior',
            'name' => '戦士',
            'rank' => 'normal',
            'description' => 'HPと物理火力の底上げ',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 120,
            'atk_rate' => 90,
            'def_rate' => 130,
            'mag_rate' => 110,
            'spr_rate' => 80,
            'spd_rate' => 90,
            'luck_rate' => 100,
            'is_hidden' => false,
            'sort_order' => 20,
            'bonus_hp' => 2,
            'bonus_mp' => 20,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'thief',
            'name' => '盗賊',
            'rank' => 'normal',
            'description' => '速度と運の底上げ',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 100,
            'atk_rate' => 100,
            'def_rate' => 110,
            'mag_rate' => 90,
            'spr_rate' => 90,
            'spd_rate' => 90,
            'luck_rate' => 130,
            'is_hidden' => false,
            'sort_order' => 30,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 20,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'archer',
            'name' => '弓使い',
            'rank' => 'normal',
            'description' => '遠距離会心型の土台',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 100,
            'atk_rate' => 100,
            'def_rate' => 120,
            'mag_rate' => 90,
            'spr_rate' => 90,
            'spd_rate' => 100,
            'luck_rate' => 120,
            'is_hidden' => false,
            'sort_order' => 40,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 20,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'fighter',
            'name' => '格闘家',
            'rank' => 'normal',
            'description' => '素早い物理職の土台',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 110,
            'atk_rate' => 90,
            'def_rate' => 120,
            'mag_rate' => 100,
            'spr_rate' => 80,
            'spd_rate' => 100,
            'luck_rate' => 130,
            'is_hidden' => false,
            'sort_order' => 50,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 10,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 10,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'mage',
            'name' => '魔法使い',
            'rank' => 'normal',
            'description' => '魔法火力の土台',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 90,
            'atk_rate' => 130,
            'def_rate' => 80,
            'mag_rate' => 90,
            'spr_rate' => 130,
            'spd_rate' => 120,
            'luck_rate' => 110,
            'is_hidden' => false,
            'sort_order' => 60,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 20,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'priest',
            'name' => '僧侶',
            'rank' => 'normal',
            'description' => '回復・精神の土台',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 100,
            'atk_rate' => 120,
            'def_rate' => 90,
            'mag_rate' => 100,
            'spr_rate' => 120,
            'spd_rate' => 130,
            'luck_rate' => 90,
            'is_hidden' => false,
            'sort_order' => 70,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 20,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'merchant',
            'name' => '商人',
            'rank' => 'normal',
            'description' => '金策と運の土台',
            'max_job_level' => 10,
            'hp_rate' => 0,
            'mp_rate' => 110,
            'atk_rate' => 100,
            'def_rate' => 100,
            'mag_rate' => 110,
            'spr_rate' => 100,
            'spd_rate' => 110,
            'luck_rate' => 100,
            'is_hidden' => false,
            'sort_order' => 80,
            'bonus_hp' => 2,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 20,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 0,
        ],
    ],
    [
        'data' => [
            'key' => 'magic_swordsman',
            'name' => '魔法剣士',
            'rank' => 'middle',
            'description' => 'ATK/MAGを同値で伸ばし、魔法剣士らしさを出す。',
            'max_job_level' => 12,
            'hp_rate' => 120,
            'mp_rate' => 120,
            'atk_rate' => 140,
            'def_rate' => 120,
            'mag_rate' => 140,
            'spr_rate' => 120,
            'spd_rate' => 120,
            'luck_rate' => 120,
            'is_hidden' => false,
            'sort_order' => 90,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 20,
            'bonus_def' => 0,
            'bonus_mag' => 25,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '剣士',
            '魔法使い',
        ],
    ],
    [
        'data' => [
            'key' => 'paladin',
            'name' => '聖騎士',
            'rank' => 'middle',
            'description' => 'DEF/SPRとHPを伸ばす。勇者・暗黒騎士の土台。',
            'max_job_level' => 12,
            'hp_rate' => 140,
            'mp_rate' => 130,
            'atk_rate' => 120,
            'def_rate' => 150,
            'mag_rate' => 110,
            'spr_rate' => 160,
            'spd_rate' => 90,
            'luck_rate' => 100,
            'is_hidden' => false,
            'sort_order' => 100,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 25,
            'bonus_mag' => 0,
            'bonus_spr' => 20,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '剣士',
            '僧侶',
        ],
    ],
    [
        'data' => [
            'key' => 'samurai',
            'name' => '侍',
            'rank' => 'middle',
            'description' => 'ATK/SPD/LUKを伸ばし、剣聖につなげる。',
            'max_job_level' => 12,
            'hp_rate' => 120,
            'mp_rate' => 100,
            'atk_rate' => 170,
            'def_rate' => 110,
            'mag_rate' => 90,
            'spr_rate' => 100,
            'spd_rate' => 160,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 110,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 25,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 20,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '剣士',
            '弓使い',
        ],
    ],
    [
        'data' => [
            'key' => 'tactician',
            'name' => '軍師',
            'rank' => 'middle',
            'description' => '耐久・精神・運を伸ばし、機工王への導線を作る。',
            'max_job_level' => 12,
            'hp_rate' => 120,
            'mp_rate' => 120,
            'atk_rate' => 120,
            'def_rate' => 130,
            'mag_rate' => 110,
            'spr_rate' => 130,
            'spd_rate' => 120,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 120,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 20,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 25,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '剣士',
            '商人',
        ],
    ],
    [
        'data' => [
            'key' => 'gladiator',
            'name' => '剣闘士',
            'rank' => 'middle',
            'description' => 'ATK/DEF/SPDを伸ばす物理中級職。',
            'max_job_level' => 12,
            'hp_rate' => 140,
            'mp_rate' => 90,
            'atk_rate' => 170,
            'def_rate' => 130,
            'mag_rate' => 80,
            'spr_rate' => 100,
            'spd_rate' => 140,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 130,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 45,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '剣士',
            '戦士',
        ],
    ],
    [
        'data' => [
            'key' => 'berserker',
            'name' => '狂戦士',
            'rank' => 'middle',
            'description' => 'ATKを強めにし、反動火力職の土台にする。',
            'max_job_level' => 12,
            'hp_rate' => 140,
            'mp_rate' => 90,
            'atk_rate' => 180,
            'def_rate' => 100,
            'mag_rate' => 90,
            'spr_rate' => 90,
            'spd_rate' => 150,
            'luck_rate' => 160,
            'is_hidden' => false,
            'sort_order' => 140,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 45,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '戦士',
            '格闘家',
        ],
    ],
    [
        'data' => [
            'key' => 'guardian_knight',
            'name' => '守護騎士',
            'rank' => 'middle',
            'description' => 'HP/DEFを大きく伸ばし、竜騎士・神官戦士につなげる。',
            'max_job_level' => 12,
            'hp_rate' => 160,
            'mp_rate' => 100,
            'atk_rate' => 130,
            'def_rate' => 180,
            'mag_rate' => 80,
            'spr_rate' => 130,
            'spd_rate' => 90,
            'luck_rate' => 130,
            'is_hidden' => false,
            'sort_order' => 150,
            'bonus_hp' => 25,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 20,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '戦士',
            '僧侶',
        ],
    ],
    [
        'data' => [
            'key' => 'mercenary',
            'name' => '傭兵',
            'rank' => 'middle',
            'description' => 'ATK/DEF/LUKとGOLD獲得を伸ばす。',
            'max_job_level' => 12,
            'hp_rate' => 150,
            'mp_rate' => 90,
            'atk_rate' => 160,
            'def_rate' => 140,
            'mag_rate' => 80,
            'spr_rate' => 100,
            'spd_rate' => 130,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 160,
            'bonus_hp' => 20,
            'bonus_mp' => 0,
            'bonus_str' => 25,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '戦士',
            '商人',
        ],
    ],
    [
        'data' => [
            'key' => 'ninja',
            'name' => '忍者',
            'rank' => 'middle',
            'description' => 'SPDを大きく伸ばす。幻影王・影狩人の重要素材。',
            'max_job_level' => 12,
            'hp_rate' => 110,
            'mp_rate' => 110,
            'atk_rate' => 140,
            'def_rate' => 100,
            'mag_rate' => 110,
            'spr_rate' => 100,
            'spd_rate' => 180,
            'luck_rate' => 140,
            'is_hidden' => false,
            'sort_order' => 170,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 45,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '盗賊',
            '格闘家',
        ],
    ],
    [
        'data' => [
            'key' => 'sniper',
            'name' => '狙撃手',
            'rank' => 'middle',
            'description' => 'ATK/SPD/LUKを伸ばす。',
            'max_job_level' => 12,
            'hp_rate' => 110,
            'mp_rate' => 110,
            'atk_rate' => 160,
            'def_rate' => 100,
            'mag_rate' => 100,
            'spr_rate' => 100,
            'spd_rate' => 160,
            'luck_rate' => 160,
            'is_hidden' => false,
            'sort_order' => 180,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 25,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 20,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '弓使い',
            '盗賊',
        ],
    ],
    [
        'data' => [
            'key' => 'magic_thief',
            'name' => '魔盗士',
            'rank' => 'middle',
            'description' => 'MAG/SPR/SPD/LUKを伸ばす。',
            'max_job_level' => 12,
            'hp_rate' => 100,
            'mp_rate' => 150,
            'atk_rate' => 90,
            'def_rate' => 90,
            'mag_rate' => 170,
            'spr_rate' => 140,
            'spd_rate' => 130,
            'luck_rate' => 130,
            'is_hidden' => false,
            'sort_order' => 190,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 25,
            'bonus_spr' => 0,
            'bonus_spd' => 20,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '盗賊',
            '魔法使い',
        ],
    ],
    [
        'data' => [
            'key' => 'traveling_merchant',
            'name' => '旅商人',
            'rank' => 'middle',
            'description' => '商人系の中心。GOLDとドロップを少し伸ばす。',
            'max_job_level' => 12,
            'hp_rate' => 130,
            'mp_rate' => 120,
            'atk_rate' => 120,
            'def_rate' => 130,
            'mag_rate' => 120,
            'spr_rate' => 130,
            'spd_rate' => 120,
            'luck_rate' => 130,
            'is_hidden' => false,
            'sort_order' => 200,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 45,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '商人',
            '盗賊',
        ],
    ],
    [
        'data' => [
            'key' => 'monk',
            'name' => 'モンク',
            'rank' => 'middle',
            'description' => 'ATK/SPR/SPDを伸ばす。武神への導線。',
            'max_job_level' => 12,
            'hp_rate' => 130,
            'mp_rate' => 110,
            'atk_rate' => 150,
            'def_rate' => 120,
            'mag_rate' => 100,
            'spr_rate' => 130,
            'spd_rate' => 150,
            'luck_rate' => 110,
            'is_hidden' => false,
            'sort_order' => 210,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 25,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 20,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '僧侶',
            '格闘家',
        ],
    ],
    [
        'data' => [
            'key' => 'magic_archer',
            'name' => '魔弓士',
            'rank' => 'middle',
            'description' => 'ATK/MAG/SPDを伸ばす。',
            'max_job_level' => 12,
            'hp_rate' => 100,
            'mp_rate' => 140,
            'atk_rate' => 130,
            'def_rate' => 100,
            'mag_rate' => 160,
            'spr_rate' => 110,
            'spd_rate' => 140,
            'luck_rate' => 120,
            'is_hidden' => false,
            'sort_order' => 220,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 20,
            'bonus_def' => 0,
            'bonus_mag' => 25,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '弓使い',
            '魔法使い',
        ],
    ],
    [
        'data' => [
            'key' => 'bard',
            'name' => '吟遊詩人',
            'rank' => 'middle',
            'description' => 'LUKと支援寄りステータスを伸ばす。',
            'max_job_level' => 12,
            'hp_rate' => 110,
            'mp_rate' => 130,
            'atk_rate' => 110,
            'def_rate' => 100,
            'mag_rate' => 120,
            'spr_rate' => 130,
            'spd_rate' => 130,
            'luck_rate' => 170,
            'is_hidden' => false,
            'sort_order' => 230,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 45,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '弓使い',
            '商人',
        ],
    ],
    [
        'data' => [
            'key' => 'bishop',
            'name' => '司祭',
            'rank' => 'middle',
            'description' => 'MP/MAG/SPRを強化。大賢者の土台。',
            'max_job_level' => 12,
            'hp_rate' => 110,
            'mp_rate' => 160,
            'atk_rate' => 90,
            'def_rate' => 120,
            'mag_rate' => 160,
            'spr_rate' => 160,
            'spd_rate' => 110,
            'luck_rate' => 90,
            'is_hidden' => false,
            'sort_order' => 240,
            'bonus_hp' => 0,
            'bonus_mp' => 20,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 25,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '僧侶',
            '魔法使い',
        ],
    ],
    [
        'data' => [
            'key' => 'apothecary',
            'name' => '薬師',
            'rank' => 'middle',
            'description' => 'SPR/LUKとドロップを少し伸ばす。',
            'max_job_level' => 12,
            'hp_rate' => 120,
            'mp_rate' => 130,
            'atk_rate' => 90,
            'def_rate' => 120,
            'mag_rate' => 130,
            'spr_rate' => 160,
            'spd_rate' => 100,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 250,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 25,
            'bonus_spd' => 0,
            'bonus_luk' => 20,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '商人',
            '僧侶',
        ],
    ],
    [
        'data' => [
            'key' => 'alchemist',
            'name' => '錬金術師',
            'rank' => 'middle',
            'description' => 'MAG/SPR/LUKとドロップを伸ばす。',
            'max_job_level' => 12,
            'hp_rate' => 110,
            'mp_rate' => 150,
            'atk_rate' => 100,
            'def_rate' => 110,
            'mag_rate' => 150,
            'spr_rate' => 130,
            'spd_rate' => 110,
            'luck_rate' => 140,
            'is_hidden' => false,
            'sort_order' => 260,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 25,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 20,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 3,
        ],
        'requirements' => [
            '商人',
            '魔法使い',
        ],
    ],
    [
        'data' => [
            'key' => 'hero',
            'name' => '勇者',
            'rank' => 'advanced',
            'description' => '全体を広く底上げするが、英雄との差は残す。',
            'max_job_level' => 15,
            'hp_rate' => 160,
            'mp_rate' => 140,
            'atk_rate' => 170,
            'def_rate' => 160,
            'mag_rate' => 140,
            'spr_rate' => 150,
            'spd_rate' => 150,
            'luck_rate' => 130,
            'is_hidden' => false,
            'sort_order' => 270,
            'bonus_hp' => 30,
            'bonus_mp' => 0,
            'bonus_str' => 30,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 30,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '魔法剣士',
            '聖騎士',
        ],
    ],
    [
        'data' => [
            'key' => 'sword_master',
            'name' => '剣聖',
            'rank' => 'advanced',
            'description' => 'ATK/SPD/LUKを大きく伸ばす。',
            'max_job_level' => 15,
            'hp_rate' => 140,
            'mp_rate' => 120,
            'atk_rate' => 210,
            'def_rate' => 130,
            'mag_rate' => 100,
            'spr_rate' => 120,
            'spd_rate' => 190,
            'luck_rate' => 190,
            'is_hidden' => false,
            'sort_order' => 280,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 45,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 45,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '侍',
            '剣闘士',
        ],
    ],
    [
        'data' => [
            'key' => 'grand_sage',
            'name' => '大賢者',
            'rank' => 'advanced',
            'description' => 'MP/MAG/SPRを大きく伸ばす。',
            'max_job_level' => 15,
            'hp_rate' => 120,
            'mp_rate' => 200,
            'atk_rate' => 100,
            'def_rate' => 130,
            'mag_rate' => 210,
            'spr_rate' => 200,
            'spd_rate' => 140,
            'luck_rate' => 100,
            'is_hidden' => false,
            'sort_order' => 290,
            'bonus_hp' => 0,
            'bonus_mp' => 30,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 30,
            'bonus_spr' => 30,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '司祭',
            '錬金術師',
        ],
    ],
    [
        'data' => [
            'key' => 'dark_knight',
            'name' => '暗黒騎士',
            'rank' => 'advanced',
            'description' => 'HP/ATK/DEFを伸ばし、反動技を支える。',
            'max_job_level' => 15,
            'hp_rate' => 180,
            'mp_rate' => 120,
            'atk_rate' => 200,
            'def_rate' => 150,
            'mag_rate' => 130,
            'spr_rate' => 130,
            'spd_rate' => 140,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 300,
            'bonus_hp' => 45,
            'bonus_mp' => 0,
            'bonus_str' => 45,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '狂戦士',
            '聖騎士',
        ],
    ],
    [
        'data' => [
            'key' => 'golden_merchant',
            'name' => '黄金商人',
            'rank' => 'advanced',
            'description' => '全能力とGOLD/ドロップを伸ばす商人系上位。',
            'max_job_level' => 15,
            'hp_rate' => 150,
            'mp_rate' => 150,
            'atk_rate' => 150,
            'def_rate' => 150,
            'mag_rate' => 150,
            'spr_rate' => 150,
            'spd_rate' => 150,
            'luck_rate' => 150,
            'is_hidden' => false,
            'sort_order' => 310,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 90,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '旅商人',
            '錬金術師',
        ],
    ],
    [
        'data' => [
            'key' => 'dragoon',
            'name' => '竜騎士',
            'rank' => 'advanced',
            'description' => 'HP/ATK/DEF/SPDを伸ばす。',
            'max_job_level' => 15,
            'hp_rate' => 170,
            'mp_rate' => 110,
            'atk_rate' => 180,
            'def_rate' => 160,
            'mag_rate' => 100,
            'spr_rate' => 120,
            'spd_rate' => 180,
            'luck_rate' => 180,
            'is_hidden' => false,
            'sort_order' => 320,
            'bonus_hp' => 30,
            'bonus_mp' => 0,
            'bonus_str' => 30,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 30,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '守護騎士',
            '狙撃手',
        ],
    ],
    [
        'data' => [
            'key' => 'war_god',
            'name' => '武神',
            'rank' => 'advanced',
            'description' => 'ATK/SPDを大きく伸ばす。',
            'max_job_level' => 15,
            'hp_rate' => 180,
            'mp_rate' => 100,
            'atk_rate' => 210,
            'def_rate' => 130,
            'mag_rate' => 90,
            'spr_rate' => 120,
            'spd_rate' => 200,
            'luck_rate' => 170,
            'is_hidden' => false,
            'sort_order' => 330,
            'bonus_hp' => 30,
            'bonus_mp' => 0,
            'bonus_str' => 30,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 30,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            'モンク',
            '狂戦士',
        ],
    ],
    [
        'data' => [
            'key' => 'phantom_king',
            'name' => '幻影王',
            'rank' => 'advanced',
            'description' => 'SPD/LUKを最重視し、ATK/MAGも少し伸ばす。',
            'max_job_level' => 15,
            'hp_rate' => 120,
            'mp_rate' => 140,
            'atk_rate' => 150,
            'def_rate' => 100,
            'mag_rate' => 150,
            'spr_rate' => 120,
            'spd_rate' => 220,
            'luck_rate' => 200,
            'is_hidden' => false,
            'sort_order' => 340,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 45,
            'bonus_luk' => 45,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '忍者',
            '魔盗士',
        ],
    ],
    [
        'data' => [
            'key' => 'machinist_king',
            'name' => '機工王',
            'rank' => 'advanced',
            'description' => 'DEF/MAGを中心に、機械・魔導の複合感を出す。',
            'max_job_level' => 15,
            'hp_rate' => 150,
            'mp_rate' => 150,
            'atk_rate' => 160,
            'def_rate' => 170,
            'mag_rate' => 170,
            'spr_rate' => 140,
            'spd_rate' => 120,
            'luck_rate' => 140,
            'is_hidden' => false,
            'sort_order' => 350,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 45,
            'bonus_mag' => 45,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '軍師',
            '錬金術師',
        ],
    ],
    [
        'data' => [
            'key' => 'priest_warrior',
            'name' => '神官戦士',
            'rank' => 'advanced',
            'description' => 'HP/MP/DEF/SPRを伸ばす。',
            'max_job_level' => 15,
            'hp_rate' => 170,
            'mp_rate' => 160,
            'atk_rate' => 140,
            'def_rate' => 170,
            'mag_rate' => 150,
            'spr_rate' => 210,
            'spd_rate' => 100,
            'luck_rate' => 100,
            'is_hidden' => false,
            'sort_order' => 360,
            'bonus_hp' => 30,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 30,
            'bonus_mag' => 0,
            'bonus_spr' => 30,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '守護騎士',
            '司祭',
        ],
    ],
    [
        'data' => [
            'key' => 'shadow_hunter',
            'name' => '影狩人',
            'rank' => 'advanced',
            'description' => 'ATK/SPD/LUKを大きく伸ばす。',
            'max_job_level' => 15,
            'hp_rate' => 130,
            'mp_rate' => 120,
            'atk_rate' => 190,
            'def_rate' => 110,
            'mag_rate' => 110,
            'spr_rate' => 110,
            'spd_rate' => 220,
            'luck_rate' => 210,
            'is_hidden' => false,
            'sort_order' => 370,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 30,
            'bonus_def' => 0,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 30,
            'bonus_luk' => 30,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '狙撃手',
            '忍者',
        ],
    ],
    [
        'data' => [
            'key' => 'merchant_sage_king',
            'name' => '賢商王',
            'rank' => 'advanced',
            'description' => 'MP/MAG/SPR/LUKと金策を強化。',
            'max_job_level' => 15,
            'hp_rate' => 150,
            'mp_rate' => 170,
            'atk_rate' => 110,
            'def_rate' => 150,
            'mag_rate' => 160,
            'spr_rate' => 190,
            'spd_rate' => 110,
            'luck_rate' => 160,
            'is_hidden' => false,
            'sort_order' => 380,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 30,
            'bonus_spr' => 30,
            'bonus_spd' => 0,
            'bonus_luk' => 30,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 4,
        ],
        'requirements' => [
            '薬師',
            '旅商人',
        ],
    ],
    [
        'data' => [
            'key' => 'valzeria_hero',
            'name' => 'ヴァルゼリアの英雄',
            'rank' => 'legend',
            'description' => '全ステータスを均等に大きく底上げする最終職。',
            'max_job_level' => 20,
            'hp_rate' => 180,
            'mp_rate' => 180,
            'atk_rate' => 180,
            'def_rate' => 180,
            'mag_rate' => 180,
            'spr_rate' => 180,
            'spd_rate' => 180,
            'luck_rate' => 180,
            'is_hidden' => true,
            'sort_order' => 390,
            'bonus_hp' => 30,
            'bonus_mp' => 10,
            'bonus_str' => 30,
            'bonus_def' => 30,
            'bonus_mag' => 30,
            'bonus_spr' => 30,
            'bonus_spd' => 30,
            'bonus_luk' => 10,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 5,
        ],
        'requirements' => [
            '勇者',
            '剣聖',
            '大賢者',
        ],
        'req_item' => '英雄の証',
    ],
    [
        'data' => [
            'key' => 'abyss_walker',
            'name' => '深淵歩き',
            'rank' => 'legend',
            'description' => 'ATK/MAG/SPDを中心に伸ばす。耐久はHPで補う。',
            'max_job_level' => 20,
            'hp_rate' => 160,
            'mp_rate' => 160,
            'atk_rate' => 225,
            'def_rate' => 150,
            'mag_rate' => 225,
            'spr_rate' => 150,
            'spd_rate' => 200,
            'luck_rate' => 170,
            'is_hidden' => true,
            'sort_order' => 400,
            'bonus_hp' => 0,
            'bonus_mp' => 0,
            'bonus_str' => 100,
            'bonus_def' => 0,
            'bonus_mag' => 100,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 5,
        ],
        'requirements' => [
            '暗黒騎士',
            '幻影王',
            '大賢者',
        ],
        'req_item' => '深淵の核',
    ],
    [
        'data' => [
            'key' => 'ancient_alchemist_king',
            'name' => '古代錬成王',
            'rank' => 'legend',
            'description' => 'MP/MAG/SPRを大きく伸ばし、ドロップも強化。',
            'max_job_level' => 20,
            'hp_rate' => 160,
            'mp_rate' => 225,
            'atk_rate' => 140,
            'def_rate' => 170,
            'mag_rate' => 225,
            'spr_rate' => 225,
            'spd_rate' => 140,
            'luck_rate' => 155,
            'is_hidden' => true,
            'sort_order' => 410,
            'bonus_hp' => 0,
            'bonus_mp' => 50,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 75,
            'bonus_spr' => 75,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 5,
        ],
        'requirements' => [
            '黄金商人',
            '機工王',
            '賢商王',
        ],
        'req_item' => '古代核',
    ],
    [
        'data' => [
            'key' => 'dragon_god',
            'name' => '竜神',
            'rank' => 'legend',
            'description' => 'HP/ATK/DEF/SPDを大きく伸ばす。',
            'max_job_level' => 20,
            'hp_rate' => 225,
            'mp_rate' => 150,
            'atk_rate' => 225,
            'def_rate' => 200,
            'mag_rate' => 120,
            'spr_rate' => 170,
            'spd_rate' => 200,
            'luck_rate' => 150,
            'is_hidden' => true,
            'sort_order' => 420,
            'bonus_hp' => 60,
            'bonus_mp' => 0,
            'bonus_str' => 70,
            'bonus_def' => 70,
            'bonus_mag' => 0,
            'bonus_spr' => 0,
            'bonus_spd' => 0,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 5,
        ],
        'requirements' => [
            '竜騎士',
            '武神',
            '勇者',
        ],
        'req_item' => '竜神の鱗',
    ],
    [
        'data' => [
            'key' => 'time_space_king',
            'name' => '時空王',
            'rank' => 'legend',
            'description' => 'MP/MAG/SPDを大きく伸ばす。',
            'max_job_level' => 20,
            'hp_rate' => 150,
            'mp_rate' => 225,
            'atk_rate' => 120,
            'def_rate' => 140,
            'mag_rate' => 225,
            'spr_rate' => 180,
            'spd_rate' => 225,
            'luck_rate' => 175,
            'is_hidden' => true,
            'sort_order' => 430,
            'bonus_hp' => 0,
            'bonus_mp' => 40,
            'bonus_str' => 0,
            'bonus_def' => 0,
            'bonus_mag' => 60,
            'bonus_spr' => 0,
            'bonus_spd' => 100,
            'bonus_luk' => 0,
            'bonus_gold_rate' => 0,
            'bonus_drop_rate' => 0,
            'bonus_critical_rate' => 0,
            'special_skill_rate' => 5,
        ],
        'requirements' => [
            '大賢者',
            '幻影王',
            '機工王',
        ],
        'req_item' => '時空結晶',
    ],
];
