<div class="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8" data-nation-war-admin>
    <header class="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
        <div><p class="text-xs font-black tracking-[0.2em] text-amber-600">NATION WAR OPERATIONS</p><h1 class="mt-1 text-3xl font-black text-slate-950">国家・国家戦 運用設定</h1><p class="mt-2 text-sm font-bold text-slate-500">公開・宣戦布告・施設成長を分離し、基準D未校正では開戦できない構成です。</p></div>
        <div class="flex gap-2 text-xs font-black"><span class="rounded-md border px-3 py-2 {{ $featureEnabled ? 'border-emerald-300 bg-emerald-50 text-emerald-800' : 'border-slate-300 bg-slate-100 text-slate-700' }}">国家UI {{ $featureEnabled ? 'ON' : 'OFF' }}</span><span class="rounded-md border border-slate-300 bg-white px-3 py-2">国家 {{ $summary['nations'] }} / 進行中 {{ $summary['live_wars'] }}</span></div>
    </header>
    @if(session('status'))<div class="mt-5 rounded-lg border border-emerald-300 bg-emerald-50 px-4 py-3 text-sm font-black text-emerald-800" role="status">{{ session('status') }}</div>@endif
    @unless($featureEnabled)<div class="mt-5 rounded-lg border border-sky-200 bg-sky-50 px-4 py-3 text-sm font-black text-sky-900">NATION_WAR_ENABLED はOFFです。本番プレイヤーには従来の「準備中」画面だけが表示されます。</div>@endunless
    <form wire:submit="save" class="mt-6 space-y-6">
        <section class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-black text-slate-950">運用・バランス設定</h2><p class="mt-1 text-xs font-bold text-rose-700">宣戦布告と施設Lvアップの初期値はOFF。基準Dへ推測値を入力しないでください。</p></div><div class="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">
            @foreach($settings as $setting)<label class="block rounded-lg border border-slate-200 p-3"><span class="block text-sm font-black text-slate-900">{{ $setting->label }}</span><span class="mt-1 block min-h-8 text-xs font-bold leading-relaxed text-slate-500">{{ $setting->description }}</span>@if($setting->value_type === 'boolean')<select wire:model="values.{{ $setting->id }}" class="mt-2 min-h-11 w-full rounded-md border border-slate-300 px-3 font-bold"><option value="0">OFF</option><option value="1">ON</option></select>@else<input wire:model="values.{{ $setting->id }}" class="mt-2 min-h-11 w-full rounded-md border border-slate-300 px-3 font-mono font-bold">@endif @error('values.'.$setting->id)<span class="text-xs font-bold text-rose-700">{{ $message }}</span>@enderror</label>@endforeach
        </div></section>
        <section class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-black text-slate-950">国家資材換算（40素材）</h2></div><div class="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-4">@foreach($rates as $rate)<label class="rounded-lg border border-slate-200 p-3"><span class="block truncate text-sm font-black text-slate-900">{{ $rate->material?->name ?? '不明' }}</span><span class="block text-xs font-bold text-slate-500">{{ $rate->material?->material_code }}</span><input type="number" min="1" wire:model="materialPoints.{{ $rate->id }}" class="mt-2 min-h-11 w-full rounded-md border border-slate-300 px-3 font-bold"></label>@endforeach</div></section>
        <button type="submit" wire:loading.attr="disabled" class="min-h-12 w-full rounded-lg bg-slate-950 px-5 font-black text-white disabled:opacity-50">設定を保存</button>
    </form>
    <section class="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 class="font-black text-amber-950">ライフサイクル手動確認</h2><p class="mt-1 text-sm font-bold text-amber-800">Schedulerと同じ冪等処理を実行します。設定をONへ変更する操作ではありません。</p><button type="button" wire:click="runLifecycle" class="mt-3 min-h-11 rounded-lg bg-amber-600 px-5 font-black text-white">今すぐ確認</button></section>
</div>
