<div class="min-h-full bg-slate-100 p-4 sm:p-6">
    <div class="mx-auto max-w-7xl space-y-5">
        <div class="rounded-xl bg-slate-950 p-5 text-white shadow-lg"><h1 class="text-xl font-black">追加ダンジョン管理</h1><p class="mt-2 text-sm font-bold text-slate-300">街・敵候補・強さ基準・危険度・EXP・Job EXPを設定して、追加ダンジョンを作成します。追加ダンジョンではモンスター印は落ちません。</p></div>
        @if(session('message'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{{ session('message') }}</div>@endif
        <div class="grid gap-5 xl:grid-cols-[1.1fr_1.4fr]">
            <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between gap-3"><h2 class="text-lg font-black">登録済み</h2><button wire:click="createNew" class="rounded-lg bg-slate-900 px-3 py-2 text-sm font-black text-white">新規作成</button></div><div class="mt-4 space-y-3">@forelse($dungeons as $dungeon)<button wire:click="edit({{ $dungeon->id }})" class="w-full rounded-lg border p-3 text-left transition hover:border-amber-400 hover:bg-amber-50"><div class="flex justify-between gap-3"><span class="font-black text-slate-900">{{ $dungeon->name }}</span><span class="text-xs font-bold {{ $dungeon->is_enabled ? 'text-emerald-700' : 'text-slate-400' }}">{{ $dungeon->is_enabled ? '公開中' : '停止中' }}</span></div><div class="mt-1 text-xs font-bold text-slate-500">{{ $dungeon->city?->name }} / 敵候補: {{ $dungeon->sourceArea?->name }} / 基準: {{ $dungeon->baselineArea?->name ?? '個別設定' }}</div></button>@empty<div class="rounded-lg bg-slate-50 p-4 text-sm font-bold text-slate-500">追加ダンジョンはまだありません。</div>@endforelse</div></section>
            <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-black">{{ $editingId ? '追加ダンジョンを編集' : '追加ダンジョンを作成' }}</h2><form wire:submit="save" class="mt-4 space-y-5"><div class="grid gap-3 sm:grid-cols-2"><label class="block text-sm font-bold">名前<input wire:model="form.name" class="mt-1 w-full rounded border-slate-300" placeholder="例: 風蝕深坑"></label><label class="block text-sm font-bold">配置する街<select wire:model="form.city_id" class="mt-1 w-full rounded border-slate-300"><option value="">選択してください</option>@foreach($cities as $city)<option value="{{ $city->id }}">{{ $city->name }}</option>@endforeach</select></label></div><label class="block text-sm font-bold">説明<textarea wire:model="form.description" rows="2" class="mt-1 w-full rounded border-slate-300" placeholder="カードと入場画面に表示します"></textarea></label>
                <div class="rounded-lg border border-amber-200 bg-amber-50 p-4"><h3 class="font-black text-amber-950">敵と基準</h3><p class="mt-1 text-xs font-bold text-amber-800">敵候補はこの通常ダンジョンのモンスターを使います。強さ基準を変えると初期ステータスとEXP倍率を自動計算します。</p><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="block text-sm font-bold">敵候補<select wire:model="form.source_area_id" class="mt-1 w-full rounded border-slate-300"><option value="">選択してください</option>@foreach($areas as $area)<option value="{{ $area->id }}">{{ $area->city?->name }} / {{ $area->name }}</option>@endforeach</select></label><label class="block text-sm font-bold">強さ・EXP基準<select wire:model="form.baseline_area_id" class="mt-1 w-full rounded border-slate-300"><option value="">選択してください</option>@foreach($areas as $area)<option value="{{ $area->id }}">{{ $area->city?->name }} / {{ $area->name }}</option>@endforeach</select></label></div></div>
                <div class="grid gap-3 sm:grid-cols-2"><label class="block text-sm font-bold">入場Gold<input type="number" wire:model="form.entry_gold" class="mt-1 w-full rounded border-slate-300"></label><label class="block text-sm font-bold">危険度上昇確率（%）<input type="number" wire:model="form.danger_increase_percent" class="mt-1 w-full rounded border-slate-300"></label></div><label class="block text-sm font-bold">入場素材 <span class="text-xs text-slate-500">1行ごとに「素材コード 数量」</span><textarea wire:model="form.entry_materials_text" rows="3" class="mt-1 w-full rounded border-slate-300" placeholder="WEV0026 2"></textarea></label>
                <div class="rounded-lg border border-slate-200 p-4"><h3 class="font-black">危険度と報酬</h3><div class="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">@foreach(['base_job_exp'=>'初期Job EXP','main_stat_per_danger'=>'主要能力/危険度','hp_per_danger'=>'HP/危険度','agi_luk_per_danger'=>'SPD・LUK/危険度','exp_per_danger'=>'EXP/危険度','exp_multiplier_cap'=>'EXP倍率上限','job_exp_cap'=>'Job EXP上限','danger_per_guaranteed_bonus'=>'Job加算危険度','remainder_percent_divisor'=>'端数抽選割り'] as $field=>$label)<label class="block text-xs font-bold text-slate-600">{{ $label }}<input type="number" step="any" wire:model="form.{{ $field }}" class="mt-1 w-full rounded border-slate-300 text-sm"></label>@endforeach</div></div>
                <div class="grid gap-3 sm:grid-cols-2"><label class="block text-sm font-bold">最高記録ログ開始危険度<input type="number" wire:model="form.public_log_minimum_danger" class="mt-1 w-full rounded border-slate-300"></label><label class="mt-7 inline-flex items-center gap-2 text-sm font-bold"><input type="checkbox" wire:model="form.is_enabled" class="rounded border-slate-300">公開する</label></div>
                @if($errors->any())<div class="rounded-lg bg-rose-50 p-3 text-sm font-bold text-rose-700">{{ $errors->first() }}</div>@endif<div class="flex gap-2"><button class="flex-1 rounded-lg bg-amber-500 px-4 py-3 font-black text-slate-950">{{ $editingId ? '更新する' : '作成する' }}</button><button type="button" wire:click="resetForm" class="rounded-lg border border-slate-300 px-4 py-3 font-black text-slate-700">クリア</button></div></form></section>
        </div>
    </div>
</div>
