<style>
    .nw{max-width:980px;margin:0 auto 32px;font-size:14px;color:#24344b;line-height:1.65}
    .nw *{box-sizing:border-box;min-width:0}.nw h2,.nw h3{font-weight:800;color:#132b47}.nw h2{font-size:18px}.nw h3{font-size:15px}
    .nw p{margin:6px 0}.nw small,.nw .muted{font-size:12px;color:#627286}.nw .card{background:#fff;border:1px solid #d8e0e8;border-radius:12px;padding:18px;margin:12px 0}
    .nw .hero{background:#132b47;color:#eef4fa;border:0}.nw .hero h2{color:#fff}.nw .hero small{color:#d8bb76}.nw .hero p{color:#d1dce8}
    .nw .row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.nw .between{justify-content:space-between}.nw .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.nw .grid>.card{margin:0}
    .nw a.link{color:#315b84;text-decoration:underline}.nw button,.nw .button{display:inline-flex;justify-content:center;align-items:center;background:#183d63;color:#fff;border:1px solid #183d63;border-radius:7px;padding:10px 14px;min-height:44px;font-weight:700;cursor:pointer;text-decoration:none;line-height:1.4}
    .nw button.secondary,.nw a.secondary{background:#fff;color:#244465;border-color:#c4d1df}.nw button.danger{background:#8e392b;border-color:#8e392b}.nw button:disabled{opacity:.45;cursor:default}
    .nw input:not([type=checkbox]):not([type=radio]):not([type=hidden]),.nw select{max-width:100%;min-height:44px;padding:7px 10px;border:1px solid #b6c5d6;border-radius:6px;background:#fff;color:#213b56}.nw input[type=number]{width:105px}.nw select{width:100%}.nw input[type=checkbox]{width:19px;height:19px;flex-shrink:0}
    .nw label{display:block}.nw label.check{display:flex;gap:9px;align-items:center;min-height:44px}.nw .stack>*+*{margin-top:10px}.nw .slot{border:1px dashed #b6c5d6;background:#f5f8fb;padding:12px;border-radius:8px;margin-top:10px}.nw .badge{display:inline-block;font-size:11px;background:#e9eff5;color:#274d73;border-radius:4px;padding:2px 6px}.nw .gold{background:#fbf0cf;color:#75551b}.nw .notice{background:#eef8f3;border-color:#b5deca}.nw .error{background:#fff0ec;border-color:#ecc1b4;color:#8b3829}.nw nav{display:flex;gap:6px;margin:14px 0}.nw nav a{flex:1}.nw .scroll{max-height:330px;overflow:auto;border:1px solid #dce4ed;border-radius:7px;padding:10px}.nw .line{padding:9px 0;border-bottom:1px solid #e5eaf0}.nw .line:last-child{border:0}.nw summary{cursor:pointer;min-height:44px;display:list-item;padding:9px 0;font-weight:700}.nw .stats{font-variant-numeric:tabular-nums;font-weight:700}.nw .full{width:100%}.nw .battle-log{font-size:12px;line-height:1.9}.nw .battle-log>div{margin:5px 0}.nw .absorb-row{display:grid;grid-template-columns:1fr 105px;gap:8px;align-items:center}.nw .relic-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.nw .relic-grid .card{margin:0;overflow-wrap:anywhere}
    @media(max-width:620px){.nw .grid,.nw .relic-grid{grid-template-columns:1fr}.nw .card{padding:14px}.nw nav a{padding:10px 4px;font-size:13px}.nw .row>form{max-width:100%}.nw .slot .row{align-items:stretch}.nw .slot .row>*{width:100%}.nw .hero h2{font-size:20px}}
    .nw .renamed-equipment,.nw a.renamed-equipment{color:#1d4ed8}
    .nw .card{overflow-wrap:anywhere}.nw .card h2{max-width:100%}
    .nw .filter-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}
    .nw .equipment-summary{display:grid;grid-template-columns:140px minmax(0,1fr);gap:18px;align-items:center;padding-bottom:14px;border-bottom:1px solid #e1e6ea}
    .nw .equipment-art{display:block;width:140px;height:140px;max-width:100%;object-fit:contain;margin:0;background:radial-gradient(ellipse,#f2efe5 0%,#fafbfc 65%);border:1px solid #e4e5e0;border-radius:12px}
    .nw .equipment-copy h2{margin:0;font-size:20px}.nw .equipment-copy.stack>*+*{margin-top:6px}.nw .equipment-copy button{padding:8px 12px}
    .nw .equipment-picker h2{font-size:15px}.nw .equipment-picker small{display:block}.nw .equipment-picker summary{font-size:12px;min-height:36px;padding:6px 0}
    .nw .select-shell{position:relative;display:block;margin-top:5px}.nw .select-shell:after{content:'';position:absolute;right:16px;top:18px;width:8px;height:8px;border-right:2px solid #9b7942;border-bottom:2px solid #9b7942;transform:rotate(45deg);pointer-events:none}.nw .select-shell select{appearance:none;background:linear-gradient(110deg,#faf7ee,#f0f5fa);border-color:#c4bda9;box-shadow:inset 0 1px 0 #fff;border-radius:10px;padding:10px 38px 10px 12px;font-weight:700;min-height:48px}
    .nw input:focus-visible,.nw select:focus-visible,.nw button:focus-visible,.nw summary:focus-visible{outline:2px solid #9d7b43;outline-offset:3px}
    .nw .forge-panel{padding-top:4px}.nw .forge-price{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap}.nw .forge-price>strong{font-size:22px;color:#795b2a}.nw .forge-price>small{margin-left:auto}
    .nw .material-choices{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;max-height:240px;overflow:auto;padding:3px}
    .nw .material-choice{display:flex;gap:8px;align-items:center;border:1px solid #d6dedf;border-radius:10px;padding:10px;background:#fafcfd;min-height:64px;cursor:pointer}.nw .material-choice:has(input:checked){border-color:#a7884e;background:#faf3df;box-shadow:0 0 0 1px #a7884e}.nw .material-choice.unavailable{opacity:.55;cursor:default}.nw .material-choice img{width:36px;height:36px;object-fit:contain;flex-shrink:0}.nw .material-choice input{width:18px;height:18px;flex-shrink:0;accent-color:#8f7042}.nw .material-choice strong,.nw .material-choice small{display:block}.nw .material-choice strong{font-size:13px}.nw .material-choice small{font-size:11px}
    .nw .equipment-details{border-top:1px solid #e4e9ed}.nw .equipment-details>summary{font-size:12px;color:#627286}.nw .relic-slot{padding:0 12px 12px;border:1px solid #d7e0e8;border-radius:10px;background:linear-gradient(110deg,#f8fafc,#fff)}.nw .relic-slot>summary{display:flex;align-items:center;gap:10px;position:relative;padding-right:22px}.nw .relic-slot>summary:after{content:'⌄';position:absolute;right:0;color:#9b7942}.nw .relic-slot small{display:block;font-weight:400}.nw .slot-number{display:grid;place-items:center;flex-shrink:0;width:30px;height:30px;border-radius:8px;background:#e7edf4;color:#34516d}.nw .effect-preview{background:#f1f5fa;padding:0 10px 10px;border-radius:8px}.nw .effect-preview>summary{font-size:12px}
    .nw .feed-card>summary{font-size:14px}.nw .relic-entry>summary{display:flex;align-items:center;gap:12px}.nw .relic-entry>summary strong{color:#233e5c}.nw .relic-entry>summary small{font-weight:400}.nw .relic-copy{flex:1;min-width:0}.nw .relic-copy strong,.nw .relic-copy small{display:block}
    @media(max-width:620px){.nw .equipment-summary{grid-template-columns:100px minmax(0,1fr);gap:12px}.nw .equipment-art{width:100px;height:120px}.nw .equipment-copy h2{font-size:17px}.nw .material-choices{grid-template-columns:1fr}.nw nav a{font-size:12px}.nw .forge-price>small{margin-left:0}.nw .filter-grid{grid-template-columns:1fr}}
    .nw .collection-art{display:grid;grid-template-columns:repeat(auto-fit,minmax(88px,1fr));gap:8px}.nw .collection-art .badge{text-align:center;padding:6px}.nw .collection-art img{display:block;width:64px;height:64px;object-fit:contain;margin:0 auto 4px}
    .nw [x-cloak]{display:none!important}.nw .forge-total{display:flex;gap:6px 18px;flex-wrap:wrap;background:#f4f7fa;border:1px solid #d4dfe9;border-radius:8px;padding:10px 12px}.nw .forge-total small{width:100%}.nw .forge-total strong{color:#795b2a}.nw .forge-sources>summary{padding:5px 0;min-height:38px}
    .nw .forge-material{border:1px solid #d6dedf;border-radius:10px;padding:10px;background:#fafcfd}.nw .forge-material.chosen{border-color:#a7884e;background:#faf3df}.nw .forge-source-copy{display:flex;gap:8px;align-items:center}.nw .forge-source-copy img{width:32px;height:32px;object-fit:contain}.nw .forge-material strong{font-size:13px}.nw .forge-material small{display:block;font-size:11px}.nw .forge-quantity{display:flex;gap:6px;align-items:center;margin-top:8px}.nw .forge-quantity input[type=number]{width:80px}.nw .forge-quantity button{padding:7px 9px;margin-left:auto;font-size:12px}.nw .forge-effect>summary{font-size:12px;min-height:36px;padding:6px 0}.nw .forge-relic-choice:has(input:disabled){opacity:.6}
    .nw .forge-quantity{flex-wrap:wrap}.nw .forge-stepper{display:flex;gap:4px;align-items:center;flex-shrink:0}.nw .forge-stepper input[type=number]{width:62px;text-align:center;padding:7px 4px}.nw .forge-stepper .quantity-step{width:44px;min-height:44px;padding:0;margin:0;font-size:22px;line-height:1}.nw .forge-quantity .fill-material{margin-left:auto}.nw .equipment-rename>summary{display:inline-flex;align-items:center;min-height:44px;font-size:12px;color:#315b84;text-decoration:underline;padding:4px 0}.nw .equipment-rename form{padding:8px;background:#f5f8fb;border:1px solid #d7e0e8;border-radius:8px}.nw .equipment-rename input{font-size:13px}
    .nw .forge-upgrade{display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap;padding:8px 10px;background:#f0f4f8;border-radius:7px;font-size:13px}.nw .forge-upgrade strong{color:#244465}
    .nw .forge-progress{background:#f5f7fa;border:1px solid #d4dfe9;border-radius:10px;padding:12px}.nw .forge-progress>.row{font-size:13px}.nw .forge-progress>.row span{font-variant-numeric:tabular-nums}.nw .forge-progress>.row b{font-size:19px;color:#795b2a}.nw .forge-progress-track{height:12px;border-radius:8px;background:#e0e6ee;overflow:hidden;margin:8px 0}.nw .forge-progress-fill{display:block;height:100%;width:0;border-radius:inherit;background:linear-gradient(90deg,#997947,#d8bb79);transition:width .22s ease}.nw .forge-progress.complete{border-color:#93bcad;background:#f1f8f5}.nw .forge-progress.complete .forge-progress-fill{background:linear-gradient(90deg,#2e6a59,#6ba88f)}.nw .forge-progress.complete>.row b{color:#2e6a59}.nw .forge-progress-breakdown{display:flex;gap:8px;flex-wrap:wrap;font-size:11px;color:#627286}.nw .forge-progress .forge-progress-message{margin:6px 0 0;font-size:12px}.nw .forge-progress.complete .forge-progress-message{color:#2e6a59;font-weight:700}
    .nw .bulk-actions button{flex:1 1 140px}.nw .bulk-equipment-choice{align-items:flex-start;overflow-wrap:anywhere}.nw .bulk-equipment-choice small{display:block}.nw .bulk-equipment-choice input[type=checkbox]{flex-shrink:0;margin-top:5px}
    @media(prefers-reduced-motion:reduce){.nw .forge-progress-fill{transition:none}}
</style>
