<x-layouts.facility title="装備市場管理">
    <div class="mx-auto w-full max-w-6xl space-y-4 pb-10">
        <h1 class="text-2xl font-black text-slate-900">装備市場管理</h1>
        @if(session('status'))<div class="rounded border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{{ session('status') }}</div>@endif
        @if(session('error'))<div class="rounded border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-800">{{ session('error') }}</div>@endif
        <div class="grid grid-cols-2 gap-3 sm:grid-cols-5">@foreach(['出品中'=>$summary['active'], '成立件数'=>$summary['sold'], '売買総額'=>number_format($summary['gross']).'G', '手数料総額'=>number_format($summary['fees']).'G', '平均販売額'=>number_format($summary['average']).'G'] as $label => $value)<div class="rounded border bg-white p-3"><div class="text-xs font-bold text-slate-500">{{ $label }}</div><div class="mt-1 text-lg font-black">{{ $value }}</div></div>@endforeach</div>
        <div class="rounded border bg-white p-4"><h2 class="font-black">ランク別販売件数</h2><div class="mt-2 flex flex-wrap gap-2 text-xs font-bold">@forelse($byRank as $row)<span class="rounded bg-slate-100 px-2 py-1">{{ $row->weapon_rank ?: '-' }}: {{ $row->count }}件</span>@empty<span class="text-slate-500">まだ成立取引はありません。</span>@endforelse</div></div>
        <div class="overflow-x-auto rounded border bg-white"><table class="min-w-full text-left text-xs"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-3">状態</th><th class="p-3">武器</th><th class="p-3">出品者</th><th class="p-3">購入者</th><th class="p-3">査定</th><th class="p-3">価格</th><th class="p-3">操作</th></tr></thead><tbody>@foreach($listings as $listing)<tr class="border-t"><td class="p-3 font-bold">{{ $listing->status }}</td><td class="p-3">{{ $listing->display_name_snapshot }}<div class="text-slate-400">個体 #{{ $listing->character_item_id }}</div></td><td class="p-3">{{ $listing->seller?->name ?? '-' }}</td><td class="p-3">{{ $listing->buyer?->name ?? '-' }}</td><td class="p-3">@if($listing->appraisal_version >= 2 && $listing->body_appraisal_price !== null && $listing->trait_appraisal_price !== null)<div>本体 {{ number_format($listing->body_appraisal_price) }}G</div><div>特性 {{ number_format($listing->trait_appraisal_price) }}G</div>@else<div>旧査定</div>@endif<div class="font-black">総額 {{ number_format($listing->appraisal_price) }}G</div><div class="text-slate-400">査定v{{ $listing->appraisal_version }}</div></td><td class="p-3"><div>{{ $listing->status === 'sold' ? '成立' : '出品' }} {{ number_format($listing->listing_price) }}G</div>@if($listing->appraisalRatioPercent() !== null)<div class="text-slate-400">査定比 {{ number_format($listing->appraisalRatioPercent(), 1) }}%</div>@endif</td><td class="p-3">@if($listing->status === 'active')<form method="POST" action="{{ route('admin.equipment-market.cancel', $listing) }}" onsubmit="return confirm('手数料なしで出品者へ返却します。')">@csrf<button class="rounded border border-red-200 px-2 py-1 font-black text-red-700">運営取消</button></form>@endif</td></tr>@endforeach</tbody></table></div>
    </div>
</x-layouts.facility>
