<?php

return [
    [
        'id' => '2026-06-26-tavern-npc-portraits',
        'date' => '2026-06-26',
        'category' => 'added',
        'title' => '酒場NPCのキャラ画像表示を追加',
        'detail' => '酒場で出会える冒険者や名簿に、NPCごとのキャラ画像を表示するようにしました。',
    ],
    [
        'id' => '2026-06-26-drop-armor-affixes',
        'date' => '2026-06-26',
        'category' => 'added',
        'title' => '銘付きドロップ防具を追加',
        'detail' => '敵から落ちる一部の防具に、能力銘や種族耐性が付くことがあります。',
    ],
    [
        'id' => '2026-06-26-storage-expand-price-50',
        'date' => '2026-06-26',
        'category' => 'balance',
        'title' => '倉庫拡張を利用しやすく調整',
        'detail' => '素材倉庫・装備倉庫の+50拡張に必要な輝石を50個にしました。',
    ],
    [
        'id' => '2026-06-26-job-master-rank-10-balance',
        'date' => '2026-06-26',
        'category' => 'balance',
        'title' => '職業マスター条件を統一',
        'detail' => '職業は全てランク10でマスターし、上位職ほど必要職業EXPが多くなるよう調整しました。',
    ],
    [
        'id' => '2026-06-26-job-master-display-error-fix',
        'date' => '2026-06-26',
        'category' => 'fixed',
        'title' => '職業マスター表示を修正',
        'detail' => '職業ランク表示で画面が開けなくなる場合があった不具合を修正しました。',
    ],
    [
        'id' => '2026-06-26-material-storage-limit-500',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '素材倉庫の標準枠を拡張',
        'detail' => '素材倉庫の標準上限を300個から500個に増やしました。',
    ],
    [
        'id' => '2026-06-26-job-growth-display-fix',
        'date' => '2026-06-26',
        'category' => 'fixed',
        'title' => '職業の伸びやすさ表示を修正',
        'detail' => '神殿の職業詳細で、成長倍率が高い能力を確認できるようにしました。',
    ],
    [
        'id' => '2026-06-26-job-detail-modal',
        'date' => '2026-06-26',
        'category' => 'added',
        'title' => '職業の詳細確認を追加',
        'detail' => '神殿で各職業の特徴、伸びやすい能力、奥義、マスター恩恵、必要条件を確認できるようにしました。',
    ],
    [
        'id' => '2026-06-26-profile-scrollbar-modern',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => 'プロフィール表示をさらに調整',
        'detail' => 'PC表示時のプロフィール内スクロールバーを見やすく整えました。',
    ],
    [
        'id' => '2026-06-26-profile-modal-frame-cleanup',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => 'プロフィール表示をすっきり調整',
        'detail' => '冒険者プロフィールの外周フレームを外し、内容を見やすくしました。',
    ],
    [
        'id' => '2026-06-26-valmon-toast-front',
        'date' => '2026-06-26',
        'category' => 'fixed',
        'title' => 'ヴァルモン通知を見やすく修正',
        'detail' => '餌やり後の通知がアプリ追加バナーに隠れないようにしました。',
    ],
    [
        'id' => '2026-06-26-home-action-job-change',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '転職の案内を分かりやすく',
        'detail' => '現在の職業をマスターした冒険者に、神殿で転職を確認する案内を表示するようにしました。',
    ],
    [
        'id' => '2026-06-26-valmon-feed-tab-toast',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => 'ヴァルモン餌やりを改善',
        'detail' => '餌を与えた後も餌タブに残り、結果をトーストで確認できるようにしました。',
    ],
    [
        'id' => '2026-06-26-storage-full-link',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '倉庫満杯時の導線を改善',
        'detail' => '倉庫がいっぱいの案内から、そのまま倉庫整理へ移動できるようにしました。',
    ],
    [
        'id' => '2026-06-26-drop-weapon-affixes',
        'date' => '2026-06-26',
        'category' => 'added',
        'title' => '銘付きドロップ武器を追加',
        'detail' => '敵から落ちる一部の武器に、能力銘や種族特効が付くことがあります。',
    ],
    [
        'id' => '2026-06-26-material-source-highlight',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '素材の入手場所を見つけやすく',
        'detail' => '素材の入手場所へ移動したとき、対象の探索先がより分かりやすく表示されるようにしました。',
    ],
    [
        'id' => '2026-06-26-supply-stock-breakdown',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '補給所の保管数を見やすく',
        'detail' => '補給所に残る回復アイテムを、持ち越し分と本日分に分けて確認できるようにしました。',
    ],
    [
        'id' => '2026-06-26-battle-enemy-family-display',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '敵の種族を見やすく表示',
        'detail' => '戦闘画面の敵情報で、属性等ではなく種族が分かるようにしました。',
    ],
    [
        'id' => '2026-06-26-remove-guild-chat-option',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => 'チャット送信先を整理',
        'detail' => '未使用のギルド送信先を外し、全体と個人を選びやすくしました。',
    ],
    [
        'id' => '2026-06-26-chat-history-expand',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => 'チャット履歴を見返しやすく',
        'detail' => '下部チャットの展開時に、通常より15行多く履歴を表示できるようにしました。',
    ],
    [
        'id' => '2026-06-26-depth-cooldown-tuning',
        'date' => '2026-06-26',
        'category' => 'balance',
        'title' => '探索待機を階層別に調整',
        'detail' => '表層10秒、深部15秒、深層以降20秒にし、浅い探索を進めやすくしました。',
    ],
    [
        'id' => '2026-06-26-chat-polling-interval',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '全体チャットの更新間隔を調整',
        'detail' => 'サーバー負荷を抑えるため、下部チャットの自動更新間隔を30秒にしました。',
    ],
    [
        'id' => '2026-06-26-route-area-exp-rebalance',
        'date' => '2026-06-26',
        'category' => 'balance',
        'title' => '街道の経験値を上方調整',
        'detail' => '次の街へつながる道ダンジョンの敵から、強さに見合う経験値を得られるようにしました。',
    ],
    [
        'id' => '2026-06-26-next-action-frontline-area',
        'date' => '2026-06-26',
        'category' => 'fixed',
        'title' => '次やることの探索案内を修正',
        'detail' => '到達済みの新しい街に未完了ダンジョンがある場合、前の街道ではなく本来進める場所を案内するようにしました。',
    ],
    [
        'id' => '2026-06-26-depth-recommended-level-display',
        'date' => '2026-06-26',
        'category' => 'fixed',
        'title' => '深い階層の推奨Lv表示を修正',
        'detail' => '探索中に深い階層へ進む画面で、現在の強さ設定に合う推奨Lvを表示するようにしました。',
    ],
    [
        'id' => '2026-06-26-laravel-deploy-cache',
        'date' => '2026-06-26',
        'category' => 'internal',
        'title' => '表示速度の土台を調整',
        'detail' => 'デプロイ時にLaravelの本番キャッシュを作成し、画面表示の土台を軽くしました。',
    ],
    [
        'id' => '2026-06-26-admin-chat-message',
        'date' => '2026-06-26',
        'category' => 'added',
        'title' => '管理人メッセージを追加',
        'detail' => '管理画面から全体チャットへ管理人メッセージを投稿できるようにしました。',
    ],
    [
        'id' => '2026-06-26-hide-complete-exploration-progress',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '探索結果の表示をすっきり調整',
        'detail' => '探索の進展が100%になった場所では、戦闘結果の進展表示を出し続けないようにしました。',
    ],
    [
        'id' => '2026-06-26-help-text-accordion',
        'date' => '2026-06-26',
        'category' => 'internal',
        'title' => 'ヘルプ文言編集を見やすく',
        'detail' => 'ヘルプ文言管理の各項目を開閉できるようにしました。',
    ],
    [
        'id' => '2026-06-26-help-text-admin',
        'date' => '2026-06-26',
        'category' => 'internal',
        'title' => 'ヘルプ文言を管理しやすく',
        'detail' => 'ヘルプと案内所の説明文を管理画面から編集できるようにしました。',
    ],
    [
        'id' => '2026-06-26-material-exchange-cleanup',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '素材交換所の表示を整理',
        'detail' => '現在使う交換だけを探しやすくし、使わない装備素材変換を表示から外しました。',
    ],
    [
        'id' => '2026-06-26-material-exchange-filters',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '素材交換所を探しやすく改善',
        'detail' => '交換カテゴリと説明文を整理し、必要な素材交換を見つけやすくしました。',
    ],
    [
        'id' => '2026-06-26-equipment-plus-five',
        'date' => '2026-06-26',
        'category' => 'balance',
        'title' => '装備をさらに鍛えられるように',
        'detail' => '鍛冶屋で装備を+5まで強化でき、欠片から強化用の石を作れるようにしました。',
    ],
    [
        'id' => '2026-06-26-admin-summary-copy-controls',
        'date' => '2026-06-26',
        'category' => 'internal',
        'title' => '更新情報をコピーしやすく改善',
        'detail' => '管理者が公開用の文面を選んでコピーできるようにしました。',
    ],
    [
        'id' => '2026-06-26-admin-update-summary',
        'date' => '2026-06-26',
        'category' => 'internal',
        'title' => '更新情報の管理機能を追加',
        'detail' => '今後の更新内容を管理画面で確認できるようにしました。',
    ],
    [
        'id' => '2026-06-25-depth-danger-reset',
        'date' => '2026-06-25',
        'category' => 'balance',
        'title' => '深い階層の探索バランスを調整',
        'detail' => '深部以降に進んだときの危険度と敵の強さを調整し、階層ごとの手応えが分かりやすくなりました。',
    ],
    [
        'id' => '2026-06-25-shop-rank-badges',
        'date' => '2026-06-25',
        'category' => 'changed',
        'title' => '装備屋でランクが見やすく',
        'detail' => '装備屋の一覧や現在の装備にランク表示を追加し、装備の強さを比べやすくしました。',
    ],
    [
        'id' => '2026-06-25-arena-rank-logs',
        'date' => '2026-06-25',
        'category' => 'changed',
        'title' => '闘技場の順位変動を分かりやすく',
        'detail' => '格上に勝つと順位が大きく上がり、順位上昇やTOP10入りが全体チャットに流れるようになりました。',
    ],
    [
        'id' => '2026-06-25-private-chat-scope',
        'date' => '2026-06-25',
        'category' => 'fixed',
        'title' => '個別チャットの表示を修正',
        'detail' => '個別チャットや手紙の内容が、全体チャット側に表示されないようにしました。',
    ],
    [
        'id' => '2026-06-25-material-drop-tuning',
        'date' => '2026-06-25',
        'category' => 'fixed',
        'title' => '地域素材を入手しやすく調整',
        'detail' => '一部の地域素材が探索で手に入る機会を増やし、素材集めを進めやすくしました。',
    ],
    [
        'id' => '2026-06-25-sell-treasure-display',
        'date' => '2026-06-25',
        'category' => 'changed',
        'title' => '換金素材が分かりやすく',
        'detail' => '探索で手に入れた換金素材を、通常素材と見分けやすい表示にしました。',
    ],
];
