<?php

return [
    [
        'id' => '2026-07-04-tavern-reunion-duplicate-fix',
        'date' => '2026-07-04',
        'category' => 'fixed',
        'title' => '酒場の重複表示を修正',
        'detail' => '探索中にすれ違ったNPCが当日の酒場にもいる場合、同じ人物が重複表示されないよう修正しました。',
    ],
    [
        'id' => '2026-07-03-inn-analytics-profit-estimate',
        'date' => '2026-07-03',
        'category' => 'internal',
        'title' => '宿屋分析に想定利益を追加',
        'detail' => '管理画面の宿屋売上分析で、日々の想定支出を差し引いた利益を確認できるようにしました。',
    ],
    [
        'id' => '2026-07-02-support-shop-sale-limit',
        'date' => '2026-07-02',
        'category' => 'balance',
        'title' => '探索力回復セールを拡充',
        'detail' => '7月5日23:59まで、探索力の小瓶と薬を1日10個まで購入できるようにしました。',
    ],
    [
        'id' => '2026-07-02-guide-stat-label-fixes',
        'date' => '2026-07-02',
        'category' => 'fixed',
        'title' => '案内文言の表記を調整',
        'detail' => '街の案内所やヘルプで、SPや能力値の旧表記が残っていた箇所を修正しました。',
    ],
    [
        'id' => '2026-07-02-job-rank-extension',
        'date' => '2026-07-02',
        'category' => 'balance',
        'title' => '高位職の育成段階を拡張',
        'detail' => '超級職・冠位職・英雄職・神話職に対応し、高位転職では基礎能力値の引き継ぎが1/3になるよう調整しました。',
    ],
    [
        'id' => '2026-07-02-tavern-npc-relationship-talk',
        'date' => '2026-07-02',
        'category' => 'changed',
        'title' => '酒場会話で人物関係を強調',
        'detail' => '探索中にすれ違って酒場で再会したNPC全員が、ほかのNPCとの関係性を自然なセリフで話してくれるようになりました。',
    ],
    [
        'id' => '2026-07-02-npc-field-reunion-tavern',
        'date' => '2026-07-02',
        'category' => 'changed',
        'title' => '出会ったNPCと酒場で再会可能に',
        'detail' => '探索中にすれ違ったNPCが、その日の酒場に4人目の再会枠として登場するようになりました。',
    ],
    [
        'id' => '2026-07-02-npc-field-encounter-lines',
        'date' => '2026-07-02',
        'category' => 'changed',
        'title' => 'NPCとの出会いに一言を追加',
        'detail' => '探索中にNPCとすれ違った時、NPCらしい短い一言も表示されるようにしました。',
    ],
    [
        'id' => '2026-07-02-npc-field-encounters',
        'date' => '2026-07-02',
        'category' => 'added',
        'title' => '探索中にNPCとすれ違う演出を追加',
        'detail' => '通常探索中、ごくまれに街や一部ダンジョンにゆかりのあるNPCとすれ違うようになりました。',
    ],
    [
        'id' => '2026-07-02-admin-chat-log-history',
        'date' => '2026-07-02',
        'category' => 'internal',
        'title' => '管理人チャット履歴を拡張',
        'detail' => '管理人チャット画面で、全体チャット履歴をさらに遡って確認できるようにしました。',
    ],
    [
        'id' => '2026-07-02-material-storage-gold-expand-fix',
        'date' => '2026-07-02',
        'category' => 'fixed',
        'title' => 'Gold倉庫拡張を修正',
        'detail' => '素材倉庫Gold拡張で保管枠が増えるよう修正し、購入上限を10回に調整しました。',
    ],
    [
        'id' => '2026-07-02-notification-window-behavior',
        'date' => '2026-07-02',
        'category' => 'changed',
        'title' => '通知の開き方を調整',
        'detail' => '通知ベルから開くリンクは、公式note通知だけ新しいタブで開くようにしました。',
    ],
    [
        'id' => '2026-07-02-item-book-sell-treasure-icons',
        'date' => '2026-07-02',
        'category' => 'changed',
        'title' => '換金品アイコンを設定',
        'detail' => 'アイテム図鑑で換金品ごとの専用アイコンを表示するようにしました。',
    ],
    [
        'id' => '2026-07-02-monster-mark-book-clear-labels',
        'date' => '2026-07-02',
        'category' => 'changed',
        'title' => '印図鑑の表示を分かりやすく',
        'detail' => '印図鑑でダンジョン到達状況と印の発見数を見分けやすい表記にしました。',
    ],
    [
        'id' => '2026-07-02-item-book-sell-treasures',
        'date' => '2026-07-02',
        'category' => 'changed',
        'title' => '換金品を図鑑に掲載',
        'detail' => '売却してGoldに換えられる換金品もアイテム図鑑で確認できるようにしました。',
    ],
    [
        'id' => '2026-07-02-item-book-reconstruction-materials',
        'date' => '2026-07-02',
        'category' => 'changed',
        'title' => '復興予定素材を図鑑に表示',
        'detail' => '街素材や星屑の鍛材をアイテム図鑑に掲載し、街の復興用予定素材であることと復興機能が未実装であることを確認できるようにしました。',
    ],
    [
        'id' => '2026-07-02-remove-unused-luminous-magic-crystal',
        'date' => '2026-07-02',
        'category' => 'fixed',
        'title' => '未使用の魔導素材を整理',
        'detail' => '用途のないルミナス魔導晶を敵ドロップと素材一覧から除外し、ルミナス魔晶や魔導結晶と混同しにくくしました。',
    ],
    [
        'id' => '2026-07-02-luminous-magic-crystal-recipe-fix',
        'date' => '2026-07-02',
        'category' => 'fixed',
        'title' => '魔導素材の名前と錬成を整理',
        'detail' => '同名の魔導結晶を見分けやすくし、星導魔晶の錬成で通常探索から入手できる地域素材を使うよう修正しました。',
    ],
    [
        'id' => '2026-07-02-monster-mark-base-drop-rate-half',
        'date' => '2026-07-02',
        'category' => 'balance',
        'title' => '印の基本ドロップ率を調整',
        'detail' => 'モンスター印の基本ドロップ率を従来の半分にし、集めきった印はさらに出にくくなるよう調整しました。',
    ],
    [
        'id' => '2026-07-02-monster-mark-complete-drop-rate',
        'date' => '2026-07-02',
        'category' => 'balance',
        'title' => '印の最大解放後ドロップ率を調整',
        'detail' => '同じモンスター印を15個以上集めた後は、その印のドロップ率が通常の3分の1になるよう調整しました。',
    ],
    [
        'id' => '2026-07-02-regional-material-drop-fallback',
        'date' => '2026-07-02',
        'category' => 'fixed',
        'title' => '地域素材のドロップ候補を補正',
        'detail' => 'ネクロムやセレスティアで、地域素材が一部の敵からしか抽選されない状態を修正し、通常探索で進化用の地域素材を入手できるようにしました。',
    ],
    [
        'id' => '2026-07-02-monster-mark-book-city-accordion',
        'date' => '2026-07-02',
        'category' => 'changed',
        'title' => '印図鑑を街とダンジョン別に整理',
        'detail' => '印図鑑を街・ダンジョンごとの折りたたみ表示にし、都市カードには背景画像を添えて見分けやすくしました。',
    ],
    [
        'id' => '2026-07-02-monster-mark-book-order-fix',
        'date' => '2026-07-02',
        'category' => 'fixed',
        'title' => '印図鑑の並び順を整理',
        'detail' => '印図鑑で一部の印が一覧下部に離れて表示される問題を修正し、進行順に確認しやすくしました。',
    ],
    [
        'id' => '2026-07-02-early-inn-fee-relief',
        'date' => '2026-07-02',
        'category' => 'balance',
        'title' => '序盤の宿代を軽く調整',
        'detail' => 'Lv20までの宿屋料金を10G固定にし、冒険を始めたばかりの時期に回復しやすくしました。',
    ],
    [
        'id' => '2026-07-02-bank-quick-amount-add-buttons',
        'date' => '2026-07-02',
        'category' => 'changed',
        'title' => '銀行の金額入力を使いやすく改善',
        'detail' => '銀行の預け入れ・引き出しで、少額ボタンを押すたびに金額を足せるようにし、入力欄の横にクリアボタンも追加しました。',
    ],
    [
        'id' => '2026-07-02-job-requirement-duplicate-display',
        'date' => '2026-07-02',
        'category' => 'fixed',
        'title' => '転職条件の重複表示を修正',
        'detail' => '神殿の転職画面で、同じ必要条件が重複して表示されることがある問題を修正しました。',
    ],
    [
        'id' => '2026-07-02-valmon-unused-find-materials-hidden',
        'date' => '2026-07-02',
        'category' => 'fixed',
        'title' => 'ヴァルモン発見素材を整理',
        'detail' => 'ヴァルモンが探索中に、現在用途のない旧素材や停止中の調合素材を見つけないようにしました。',
    ],
    [
        'id' => '2026-07-02-sub-area-gate-action-fix',
        'date' => '2026-07-02',
        'category' => 'fixed',
        'title' => '未知の入口へ進みやすく修正',
        'detail' => '未知の入口を発見した戦闘結果画面から、地図に記録した入口へ直接向かえるようにしました。',
    ],
    [
        'id' => '2026-07-02-secret-realm-lord-tier-balance',
        'date' => '2026-07-02',
        'category' => 'balance',
        'title' => '秘境主の強さと報酬を調整',
        'detail' => '弱いダンジョンの秘境主も一定以上の強さになるよう調整し、序盤エリアでは秘境晶片の獲得量を控えめにしました。',
    ],
    [
        'id' => '2026-07-01-exploration-stamina-stability-fix',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '探索力表示の不安定さを修正',
        'detail' => '探索力の確認や戦闘結果画面の切り替えで、自然回復の表示が二重に進んだように見える問題を起きにくくしました。',
    ],
    [
        'id' => '2026-07-01-ranking-total-assets-inn',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '総資産番付に宿屋が登場',
        'detail' => '番付掲示板の成金番付を総資産番付に改め、宿屋の累計売上も冒険者と同じ並びで確認できるようにしました。',
    ],
    [
        'id' => '2026-07-01-admin-only-deploy',
        'date' => '2026-07-01',
        'category' => 'internal',
        'title' => '管理画面限定デプロイを追加',
        'detail' => '管理画面関連ファイルだけを反映し、通常のビルドやデータ更新を伴わない限定デプロイ手順を追加しました。',
    ],
    [
        'id' => '2026-07-01-admin-daily-new-users',
        'date' => '2026-07-01',
        'category' => 'internal',
        'title' => '新規ユーザー数を日別確認',
        'detail' => '管理ダッシュボードで今日の新規ユーザー数を押すと、直近30日の日別新規ユーザー数を確認できるようにしました。',
    ],
    [
        'id' => '2026-07-01-player-encounter-herb-rate',
        'date' => '2026-07-01',
        'category' => 'balance',
        'title' => '探索中の出会い頻度を調整',
        'detail' => '探索中に冒険者とすれ違って薬草を受け取る出来事を、同じダンジョン探索中の相手だけにし、発生頻度を控えめにしました。',
    ],
    [
        'id' => '2026-07-01-battle-stamina-timer-cleanup',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '探索力表示の揺れを再修正',
        'detail' => '戦闘結果画面で連続探索した時、古い画面の更新処理が残って探索力表示が揺れる問題を修正しました。',
    ],
    [
        'id' => '2026-07-01-item-book-category-groups',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '図鑑カテゴリを見やすく整理',
        'detail' => 'アイテム図鑑の素材カテゴリを大きめにまとめ、素材を探しやすくしました。',
    ],
    [
        'id' => '2026-07-01-item-book-usage-material-links',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '図鑑の用途素材へ移動可能に',
        'detail' => 'アイテム図鑑の用途欄に出る素材名をタップすると、その素材の項目へ移動できるようにしました。',
    ],
    [
        'id' => '2026-07-01-material-name-sr-suffix-hidden',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '素材名のレアリティ表記を整理',
        'detail' => '素材名の末尾に表示されていた[SR]表記を外し、素材一覧を読みやすくしました。',
    ],
    [
        'id' => '2026-07-01-missing-material-icon-fallback',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '素材アイコンの表示崩れを修正',
        'detail' => '素材アイコン画像が未配置の場合に、壊れた画像表示にならないよう調整しました。',
    ],
    [
        'id' => '2026-07-01-enhancement-fragment-icons-fix',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '強化素材のアイコンを修正',
        'detail' => '強化石・守護石・調律石系素材のアイコン表示を見直し、素材の種類を見分けやすくしました。',
    ],
    [
        'id' => '2026-07-01-recovery-brewing-disabled',
        'date' => '2026-07-01',
        'category' => 'balance',
        'title' => '回復アイテム調合を一時停止',
        'detail' => '探索継続力のバランスを調整するため、素材交換所で薬草などの回復アイテムを作るレシピを一時停止しました。',
    ],
    [
        'id' => '2026-07-01-item-book-hide-deprecated-materials',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '図鑑の廃止済み素材を非表示化',
        'detail' => 'アイテム図鑑に、現在は使わない廃止済み素材が表示されないようにしました。',
    ],
    [
        'id' => '2026-07-01-item-book-hide-legacy-materials',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => 'アイテム図鑑を見やすく整理',
        'detail' => 'アイテム図鑑に表示する素材を見直し、素材カードを開閉式にして必要な情報を探しやすくしました。',
    ],
    [
        'id' => '2026-07-01-sub-area-battle-count-fix',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '亜域探索の戦闘エラーを修正',
        'detail' => '共有サブエリアの探索時に、存在しない戦闘回数カラムへ保存しようとして失敗する問題を修正しました。',
    ],
    [
        'id' => '2026-07-01-admin-inn-analytics',
        'date' => '2026-07-01',
        'category' => 'internal',
        'title' => '宿屋売上分析を追加',
        'detail' => '管理画面で宿屋のGold売上、宿泊回数、利用者数、最近の宿泊履歴を確認できるようにしました。',
    ],
    [
        'id' => '2026-07-01-item-book-active-materials',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => 'アイテム図鑑の表示素材を整理',
        'detail' => 'アイテム図鑑に載せる素材を、合成・鍛冶・敵ドロップなど現在使い道があるもの中心に整理しました。',
    ],
    [
        'id' => '2026-07-01-item-book-material-recipes',
        'date' => '2026-07-01',
        'category' => 'added',
        'title' => 'アイテム図鑑を追加',
        'detail' => '素材の入手方法、作り方、用途を未所持のものも含めて確認できるアイテム図鑑を追加しました。',
    ],
    [
        'id' => '2026-07-01-accessory-sss-primordial-crystal',
        'date' => '2026-07-01',
        'category' => 'balance',
        'title' => '装飾SSS進化素材を調整',
        'detail' => '装飾品のSSからSSSへの進化素材を見直し、複数の秘境晶から作る専用素材を使う形にしました。',
    ],
    [
        'id' => '2026-07-01-sss-secret-crystal-cost',
        'date' => '2026-07-01',
        'category' => 'balance',
        'title' => 'SSS進化の秘境晶数を調整',
        'detail' => '武器・防具のSSからSSSへの分岐進化で必要な秘境晶の数を増やし、最上位進化の重みを調整しました。',
    ],
    [
        'id' => '2026-07-01-material-storage-gold-expand',
        'date' => '2026-07-01',
        'category' => 'added',
        'title' => 'Goldで素材倉庫を拡張可能に',
        'detail' => '補給商会に、Goldを使って素材倉庫の保管枠を少しずつ増やせる商品を追加しました。',
    ],
    [
        'id' => '2026-07-01-accessory-enhance-total-bonus',
        'date' => '2026-07-01',
        'category' => 'balance',
        'title' => '装飾品強化の伸び方を調整',
        'detail' => '多くの能力が上がる装飾品だけが強化で大きく伸びすぎないよう、装飾品の強化ボーナス配分を調整しました。',
    ],
    [
        'id' => '2026-07-01-depth-battle-header-colors',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '深度戦闘のヘッダー色を変更',
        'detail' => '深層・最深層・異界層で戦闘した時、戦闘開始ヘッダーも深度に合わせた暗色カラーで表示するようにしました。',
    ],
    [
        'id' => '2026-07-01-equipment-enhance-stat-fix',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '装備強化のステータス反映を修正',
        'detail' => '防具や装飾品を強化した時、装備中のステータスにも強化分が正しく反映されるようにしました。',
    ],
    [
        'id' => '2026-07-01-deep-battle-backgrounds',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '深層以降の戦闘背景を変更',
        'detail' => '深層・最深層・異界層で戦闘した時、戦闘結果画面の背景を深度に合わせた暗色グラデーションで表示するようにしました。',
    ],
    [
        'id' => '2026-07-01-otherworld-battle-background',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '異界層の戦闘背景を変更',
        'detail' => '異界層で戦闘した時、戦闘結果画面の背景を黒と紫を基調にした異界カラーで表示するようにしました。',
    ],
    [
        'id' => '2026-07-01-battle-stamina-refresh-sync',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '結果画面の探索力更新を修正',
        'detail' => '戦闘結果画面を更新した時も、自然回復後の最新探索力が表示されるようにしました。',
    ],
    [
        'id' => '2026-07-01-battle-stamina-button-sync',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '戦闘後の探索力ボタンを同期',
        'detail' => '戦闘結果画面で探索力が自然回復した時、再探索ボタンと回復モーダルが同じ探索力残量で動くようにしました。',
    ],
    [
        'id' => '2026-07-01-battle-stamina-item-purchase',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '探索中の探索力回復を改善',
        'detail' => '戦闘結果画面で探索力が足りない時、探索力の小瓶や薬をその場で購入して使い、探索を続けられるようにしました。',
    ],
    [
        'id' => '2026-07-01-otherworld-depth-badge',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '異界層の表示を強調',
        'detail' => '探索深度の異界層ラベルを黒背景と赤文字にし、危険な深度であることが分かりやすい見た目にしました。',
    ],
    [
        'id' => '2026-07-01-depth-gate-confirm-fix',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '探索深度の入場処理を修正',
        'detail' => '深度入口から進んだ時に、直前の結果画面の入口情報も確認して正しい深度へ入れるようにしました。',
    ],
    [
        'id' => '2026-07-01-batch-depth-gate-label-fix',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '深度入口の案内文を修正',
        'detail' => '10回探索で新しい探索深度の入口に到達した時、実際の進行ボタン名で案内し、入口操作が表示されるよう調整しました。',
    ],
    [
        'id' => '2026-07-01-battle-material-reward-summary',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '素材報酬の重複表示を整理',
        'detail' => '戦闘結果の素材報酬で同じ素材が複数出た時、まとめて数量表示するようにしました。',
    ],
    [
        'id' => '2026-07-01-batch-depth-gate-action',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '10回探索の深度入口を修正',
        'detail' => '10回探索中に新しい探索深度の入口へ到達した時、次の深度へ進む操作が表示されるようにしました。',
    ],
    [
        'id' => '2026-07-01-player-encounter-herb-visibility',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '出会いの薬草表示を改善',
        'detail' => '探索中に冒険者から受け取った薬草が、所持品と探索中の回復アイテム残数で分かるようにしました。',
    ],
    [
        'id' => '2026-07-01-stamina-display-sync',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '探索力表示の揺れを修正',
        'detail' => '戦闘後や10回探索後の探索力表示が増減して見える問題を修正しました。',
    ],
    [
        'id' => '2026-07-01-batch-explore-stamina-fix',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '10回探索の探索力表示を修正',
        'detail' => '探索力が少ない時の10回探索と回復表示を見直し、残量分だけ探索して自然に止まるようにしました。',
    ],
    [
        'id' => '2026-07-01-equipment-category-label-short',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '装備カテゴリ表示を簡略化',
        'detail' => '装備屋などのカテゴリ表示から重複した説明を減らし、装備の種類をすっきり確認できるようにしました。',
    ],
    [
        'id' => '2026-07-01-equipment-category-icons',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '装備種別アイコンを追加',
        'detail' => '武器種、防具材、装飾品ごとの汎用アイコンを表示し、装備の種類を見分けやすくしました。',
    ],
    [
        'id' => '2026-07-01-player-encounter-herb-gift',
        'date' => '2026-07-01',
        'category' => 'added',
        'title' => '出会いで薬草を入手',
        'detail' => '探索中に別の冒険者とすれ違った時、薬草を1個受け取れるようにしました。',
    ],
    [
        'id' => '2026-07-01-battle-equipment-drop-display',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '戦闘結果の装備獲得表示を整理',
        'detail' => '戦闘で装備品を獲得した時の表示を見直し、複数獲得時も同じ欄にまとめて確認できるようにしました。',
    ],
    [
        'id' => '2026-07-01-growth-log-milestone-tuning',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '成長ログの表示頻度を調整',
        'detail' => 'レベル到達の全体チャット通知をLv100以上の節目に絞り、通常ログに近い表示へ整えました。',
    ],
    [
        'id' => '2026-07-01-player-encounter-portrait',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '探索中の出会いに姿を表示',
        'detail' => '探索中に別の冒険者と出会った時、相手のキャラ画像と職業が結果画面に表示されるようにしました。',
    ],
    [
        'id' => '2026-07-01-player-field-encounters',
        'date' => '2026-07-01',
        'category' => 'added',
        'title' => '探索中の冒険者との出会いを追加',
        'detail' => '探索中、同じ街で活動している別の冒険者とすれ違う小さな出来事が起きるようにしました。',
    ],
    [
        'id' => '2026-07-01-newcomer-public-log',
        'date' => '2026-07-01',
        'category' => 'added',
        'title' => '新規冒険者の到着を街へ通知',
        'detail' => '新しい冒険者が作成された時、全体チャットにヴァルゼリア到着の知らせが流れるようにしました。',
    ],
    [
        'id' => '2026-07-01-newcomer-campaign-auto-gift',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '7月登録支援を自動配布',
        'detail' => '6月30日以降に登録した冒険者へ、探索力の小瓶10個とキャンペーン通知を自動で届けるようにしました。',
    ],
    [
        'id' => '2026-07-01-newcomer-stamina-bottle-gift',
        'date' => '2026-07-01',
        'category' => 'added',
        'title' => '新規冒険者への支援配布を追加',
        'detail' => '登録直後の冒険者へ、探索力の小瓶をまとめて届けられる運営機能を追加しました。',
    ],
    [
        'id' => '2026-07-01-support-stamina-item-discount',
        'date' => '2026-07-01',
        'category' => 'balance',
        'title' => '探索力回復アイテムを割引',
        'detail' => '補給商会の探索力の小瓶と探索力の薬を割引価格にし、旧価格も分かるように表示しました。',
    ],
    [
        'id' => '2026-07-01-adventurer-card-hide-arena-record',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '冒険者カードの戦績表示を整理',
        'detail' => '冒険者カードの冒険の記録から、闘技場の勝利数・敗北数表示を外しました。',
    ],
    [
        'id' => '2026-07-01-batch-explore-event-clarity',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '10回探索のイベント表示を整理',
        'detail' => '10回探索中の秘境入口、未知の入口、秘境主、深度入口などの停止理由をより分かりやすくしました。',
    ],
    [
        'id' => '2026-07-01-secret-realm-lord-result-clarity',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '秘境主戦の結果表示を改善',
        'detail' => '10回探索中に秘境主と戦った時、勝利・敗北や停止理由が分かりやすく表示されるようにしました。',
    ],
    [
        'id' => '2026-07-01-depth-gate-batch-guidance',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '10回探索の深度案内を改善',
        'detail' => '10回探索中に深度入口へ到達した時、まだ深度が切り替わっていないことと進み方を分かりやすくしました。',
    ],
    [
        'id' => '2026-07-01-ranking-comment-default',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '番付コメントの初期表示を追加',
        'detail' => '番付掲示板で一言コメント未設定の冒険者にも「よろしくお願いします」と表示するようにしました。',
    ],
    [
        'id' => '2026-07-01-profile-comment-edit-link',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '一言コメント編集を近くに配置',
        'detail' => '自分の冒険者カードから、一言コメントをすぐ編集できる導線を追加しました。',
    ],
    [
        'id' => '2026-07-01-town-ranking-profile-comments',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '番付に一言コメントを表示',
        'detail' => '番付掲示板の冒険者名の近くに、冒険者カードで設定した一言コメントを表示するようにしました。',
    ],
    [
        'id' => '2026-07-01-external-notification-new-tab',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '外部通知を別タブで表示',
        'detail' => 'note更新など外部サイトへ移動する通知を、新しいタブで開くようにしました。',
    ],
    [
        'id' => '2026-07-01-town-ranking-voice',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '番付に街の声を追加',
        'detail' => '番付掲示板に街の人のセリフを添え、掲示板が街で話題になっている雰囲気を加えました。',
    ],
    [
        'id' => '2026-07-01-town-ranking-random-leader',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '番付1位を街で紹介',
        'detail' => '街の番付案内に、画面更新ごとに各番付からランダムに選んだ1位の冒険者を表示するようにしました。',
    ],
    [
        'id' => '2026-07-01-town-ranking-spotlight',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '番付掲示板を街で案内',
        'detail' => '番付掲示板を見つけやすいよう、一定期間だけ街の施設一覧上部にも案内を表示しました。',
    ],
    [
        'id' => '2026-07-01-town-ranking-spa-tabs',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '番付の切り替えを高速化',
        'detail' => '番付掲示板の各番付をページ遷移なしで切り替えられるようにし、記録を見比べやすくしました。',
    ],
    [
        'id' => '2026-07-01-town-ranking-icons',
        'date' => '2026-07-01',
        'category' => 'changed',
        'title' => '番付に冒険者アイコンを表示',
        'detail' => '番付掲示板の各順位と一番手表示に冒険者アイコンを添え、誰の記録か見分けやすくしました。',
    ],
    [
        'id' => '2026-07-01-town-ranking-board',
        'date' => '2026-07-01',
        'category' => 'added',
        'title' => '街に番付掲示板を追加',
        'detail' => '勝利数、ヴァルモン所持数、印収集数、素材所持数、市場売上など、冒険者たちの各種番付を街から確認できるようにしました。',
    ],
    [
        'id' => '2026-07-01-equipment-evolution-affix-inherit',
        'date' => '2026-07-01',
        'category' => 'fixed',
        'title' => '銘付き装備の合成を改善',
        'detail' => '銘付き装備を進化合成した時、接頭辞や種族特性、良品・逸品の状態が進化後も残るようにしました。',
    ],
    [
        'id' => '2026-06-30-note-rss-notifications',
        'date' => '2026-06-30',
        'category' => 'added',
        'title' => 'note更新通知を追加',
        'detail' => '公式noteの最新記事が更新された時、ゲーム内の通知ベルから新着を確認できるようにしました。',
    ],
    [
        'id' => '2026-06-30-enemy-drop-material-icons',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '敵ドロップ素材アイコンを追加',
        'detail' => '敵から入手できる骨片や鍛材、地域素材にも専用アイコンを表示し、素材を見分けやすくしました。',
    ],
    [
        'id' => '2026-06-30-common-region-material-icons',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '共通素材アイコンを追加',
        'detail' => '共通素材や地域素材にも専用アイコンを表示し、素材交換所や倉庫で見分けやすくしました。',
    ],
    [
        'id' => '2026-06-30-job-art-save-fallback',
        'date' => '2026-06-30',
        'category' => 'fixed',
        'title' => '奥義保存エラーを修正',
        'detail' => '奥義セット変更時に保存できない場合がある問題を修正し、スロット変更を反映しやすくしました。',
    ],
    [
        'id' => '2026-06-30-job-art-tabs',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '奥義セット画面をタブ化',
        'detail' => '通常戦用とボス戦用の奥義セットをタブで切り替えられるようにし、設定画面を見やすくしました。',
    ],
    [
        'id' => '2026-06-30-job-art-slot-policies',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '奥義方針をスロット別に',
        'detail' => '奥義ごとに積極・通常・温存の発動方針を設定できるようにし、通常戦用/ボス戦用セットの使い分けを調整しやすくしました。',
    ],
    [
        'id' => '2026-06-30-path-stone-icons',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '導石素材アイコンを追加',
        'detail' => '聖剣・魔剣・迅刃・重魔装・軽旅装の導石にも専用アイコンを表示し、進化素材を見分けやすくしました。',
    ],
    [
        'id' => '2026-06-30-job-art-normal-boss-sets',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '奥義セットを通常/ボス別に',
        'detail' => '通常戦用とボス戦用の奥義をそれぞれ3枠まで設定できるようにし、戦う相手に合わせて使い分けやすくしました。',
    ],
    [
        'id' => '2026-06-30-accessory-evolution-icons',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '装飾進化素材アイコンを追加',
        'detail' => '装飾の核や各種結晶素材にも専用アイコンを表示し、進化素材を見分けやすくしました。',
    ],
    [
        'id' => '2026-06-30-special-skill-sp-half',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '必殺技のSP消費を軽減',
        'detail' => '現在職の必殺技で消費するSPを半分にし、奥義との併用時もSPを管理しやすくしました。',
    ],
    [
        'id' => '2026-06-30-branch-evolution-icons',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '分岐進化素材アイコンを追加',
        'detail' => '複合素材や秘境晶、極印にも専用アイコンを表示し、進化素材を見分けやすくしました。',
    ],
    [
        'id' => '2026-06-30-city-material-icons',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '都市素材アイコンを追加',
        'detail' => '都市素材や高位都市素材にも専用アイコンを表示し、素材交換所や倉庫で見分けやすくしました。',
    ],
    [
        'id' => '2026-06-30-material-specific-icons',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '素材専用アイコンを追加',
        'detail' => '強化石や精錬核など一部素材に専用アイコンを表示し、倉庫や素材交換所で見分けやすくしました。',
    ],
    [
        'id' => '2026-06-30-secret-realm-reward-balance',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '秘境報酬を欠片中心に調整',
        'detail' => '秘境採取で秘境晶が直接出る確率を下げ、秘境主報酬は秘境晶片だけになるよう調整しました。',
    ],
    [
        'id' => '2026-06-30-ancient-composite-evolution',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => 'S装備進化素材を複合化',
        'detail' => 'SからSSへの分岐進化で、古代片に加えて都市素材をまとめた複合素材を使う形に調整しました。',
    ],
    [
        'id' => '2026-06-30-enhance-fragment-drop-rate',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '強化欠片ドロップ率を低確率化',
        'detail' => '強化石・守護石・調律石の欠片を、各通常ダンジョンの約半数の敵から1%で落ちる形に調整しました。',
    ],
    [
        'id' => '2026-06-30-enhance-drop-fragments-only',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '強化素材ドロップを欠片中心に調整',
        'detail' => '敵から直接落ちる強化系素材を欠片中心にし、石や精錬核系素材は素材交換所で作る流れに整理しました。',
    ],
    [
        'id' => '2026-06-30-accessory-enhance-tuning-stone',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '装飾強化素材を調律石に改名',
        'detail' => '装飾品強化に使う素材名を、調律石の欠片・調律石・高純度調律石に変更しました。',
    ],
    [
        'id' => '2026-06-30-material-exchange-guide-cleanup',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '素材交換所の表示を整理',
        'detail' => '素材交換所の説明ボックスを減らし、交換一覧を見やすくしました。',
    ],
    [
        'id' => '2026-06-30-common-beast-fang-routing',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '獣牙素材の分類を整理',
        'detail' => '牙や爪、小鬼・ゴブリン系の敵素材を、汎用素材の獣牙へ集約しやすくしました。',
    ],
    [
        'id' => '2026-06-30-smith-gold-rank-multiplier',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '鍛冶Gold費用をランク別に調整',
        'detail' => '装備強化のGold費用を、装備ランクが高いほど重くなるように調整しました。',
    ],
    [
        'id' => '2026-06-30-material-commonization-cleanup',
        'date' => '2026-06-30',
        'category' => 'fixed',
        'title' => '素材交換の共通化候補を整理',
        'detail' => '同じ素材への自己変換を表示しないようにし、黒結晶系素材が黒結晶へ変換されやすいよう分類順を調整しました。',
    ],
    [
        'id' => '2026-06-30-refining-core-chain-recipe',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '精錬核を段階錬成に調整',
        'detail' => '粗精錬核に魔物の欠片とGoldを追加し、精錬核は粗精錬核を経由して作る形に整理しました。',
    ],
    [
        'id' => '2026-06-30-low-refining-core-always-visible',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '粗精錬核レシピを常時表示',
        'detail' => '素材交換所で粗精錬核と前段素材のレシピを、素材不足の状態でも確認できるようにしました。',
    ],
    [
        'id' => '2026-06-30-material-exchange-usage-modal',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '素材交換の用途確認を改善',
        'detail' => '素材交換所で受け取る素材名を押すと、ページ移動せずに用途や必要素材をその場で確認できるようにしました。',
    ],
    [
        'id' => '2026-06-30-refining-core-part-materials',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '精錬核の錬成素材を整理',
        'detail' => '精錬核の錬成素材を覇王黒晶、蒼炉魔晶、星樹氷晶の3段階にまとめ、必要素材を確認しやすくしました。',
    ],
    [
        'id' => '2026-06-30-material-exchange-usage-links',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '素材交換先の用途表示を追加',
        'detail' => '素材交換所で受け取る素材名から素材詳細へ移動でき、鍛冶や進化での使い道も確認できるようにしました。',
    ],
    [
        'id' => '2026-06-30-low-refining-core-smithing-recipes',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '鍛冶強化素材を核素材で整理',
        'detail' => '鍛冶+4は粗精錬核、+5は精錬核を使う形に整理し、粗精錬核を織成核殻と晶糸核芯から錬成できるようにしました。',
    ],
    [
        'id' => '2026-06-30-refining-core-all-city-high-materials',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '精錬核の錬成素材を調整',
        'detail' => '精錬核の錬成は、王紋鋼からヴァルゼリア黒核までの都市高位武器素材を各5個ずつ使うレシピにしました。',
    ],
    [
        'id' => '2026-06-30-batch-defeat-loss-summary',
        'date' => '2026-06-30',
        'category' => 'fixed',
        'title' => '10回探索の敗北ロスト表示を追加',
        'detail' => '10回探索が敗北で止まった時、失ったGoldや戦利品も結果画面で確認できるようにしました。',
    ],
    [
        'id' => '2026-06-30-batch-defeat-reason-clarity',
        'date' => '2026-06-30',
        'category' => 'fixed',
        'title' => '10回探索の敗北表示を明確化',
        'detail' => '10回探索が敗北で止まった時、何回目の戦闘で倒れたかと敗北後HPであることが分かるようにしました。',
    ],
    [
        'id' => '2026-06-30-depth-gate-batch-summary',
        'date' => '2026-06-30',
        'category' => 'fixed',
        'title' => '入口発見時の探索結果表示を修正',
        'detail' => '10回探索中に深部などの入口を見つけた時も、それまでの探索ごとの報酬サマリを確認できるようにしました。',
    ],
    [
        'id' => '2026-06-30-battle-result-exp-progress',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '戦闘結果の経験値表示を改善',
        'detail' => '戦闘結果のEXPとJob EXPに、現在値と次の必要値を括弧つきでまとめて表示するようにしました。',
    ],
    [
        'id' => '2026-06-30-necrom-enhance-city-materials',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '最終強化素材をネクロム到達前提へ調整',
        'detail' => '装備の+4強化は王都から魔導都市まで、+5強化は死霊街ネクロムまでの各地域素材を1つずつ使う固定レシピにしました。',
    ],
    [
        'id' => '2026-06-30-fixed-enhance-city-materials',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '高段階強化の都市素材を固定化',
        'detail' => '装備の+4/+5強化で必要な都市素材を、入手できる王都・グランベルグ素材に固定しました。',
    ],
    [
        'id' => '2026-06-30-accessory-enhance-city-material-fix',
        'date' => '2026-06-30',
        'category' => 'fixed',
        'title' => '装飾強化の都市素材を修正',
        'detail' => '装飾品の高段階強化で、実際に入手できる都市素材を要求するように調整しました。',
    ],
    [
        'id' => '2026-06-30-enhancement-recipe-rebalance',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '装備強化の必要素材を調整',
        'detail' => '装備強化の+1〜+5に必要な素材を見直し、欠片を使いやすくしつつ高段階では高純度素材や精錬核を使う形にしました。',
    ],
    [
        'id' => '2026-06-30-high-purity-stone-drop-removal',
        'date' => '2026-06-30',
        'category' => 'balance',
        'title' => '高純度強化素材のドロップ調整',
        'detail' => '高純度強化石・高純度守護石・高純度調律石は敵から直接落ちないようにし、欠片を集めて強化素材を作る流れに寄せました。',
    ],
    [
        'id' => '2026-06-30-material-common-fragment-recipes',
        'date' => '2026-06-30',
        'category' => 'changed',
        'title' => '敵素材の使い道を拡張',
        'detail' => '素材交換所で敵固有素材を共通素材へ変換し、共通素材から強化系の欠片を作れるようにしました。',
    ],
    [
        'id' => '2026-06-30-arena-npc-rank-gap-fix',
        'date' => '2026-06-30',
        'category' => 'fixed',
        'title' => '闘技場NPC順位の飛びを修正',
        'detail' => '闘技場ランキングでNPCの順位が途中で飛んで表示される場合がある不具合を修正しました。',
    ],
    [
        'id' => '2026-06-30-adventurer-card-name-layout',
        'date' => '2026-06-30',
        'category' => 'fixed',
        'title' => '冒険者カードの名前表示を調整',
        'detail' => '冒険者カードで長い名前が省略されないよう、名前の位置と文字サイズを調整しました。',
    ],
    [
        'id' => '2026-06-30-batch-explore-empty-return-label',
        'date' => '2026-06-30',
        'category' => 'fixed',
        'title' => '10回探索停止時の戻る表示を修正',
        'detail' => '10回探索を開始できず戦利品がない場合、戻るボタンを街に戻ると表示するようにしました。',
    ],
    [
        'id' => '2026-06-29-support-shop-item-order',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '補給商会の商品順を整理',
        'detail' => '探索支援の商品を先に表示し、その後に倉庫拡張を表示する並びへ変更しました。',
    ],
    [
        'id' => '2026-06-29-stripe-admin-mail-fallback',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '売上通知メールの宛先設定を修正',
        'detail' => 'Stripe決済完了時の運営向け通知メールが、管理者宛先未設定でも問い合わせ先へ届くようにしました。',
        'internal' => true,
    ],
    [
        'id' => '2026-06-29-batch-explore-golden-goblin-continues',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '10回探索の黄金ゴブリン処理を調整',
        'detail' => '10回探索中に黄金ゴブリンと戦った場合、特殊イベント停止ではなく通常の敵として探索を続けるようにしました。',
    ],
    [
        'id' => '2026-06-29-drain-job-art-error-fix',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '吸収系奥義の戦闘エラーを修正',
        'detail' => 'スピリットスティールなどの吸収系奥義が発動した時、戦闘がエラーになる場合がある不具合を修正しました。',
    ],
    [
        'id' => '2026-06-29-recorded-entrance-power-error-fix',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '記録済み入口の表示エラーを修正',
        'detail' => '地図に記録した入口を開いた時、目安戦力の計算で画面が表示できない場合がある不具合を修正しました。',
    ],
    [
        'id' => '2026-06-29-battle-result-chat-retained',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '探索結果画面のチャット表示を修正',
        'detail' => '深部入口や探索継続の画面でも、下部チャットと戦利品を持って帰るボタンが表示されるようにしました。',
    ],
    [
        'id' => '2026-06-29-secret-realm-repeat-decay',
        'date' => '2026-06-29',
        'category' => 'balance',
        'title' => '秘境入口の再出現率を調整',
        'detail' => '同じ場所で秘境を見つけるたび、次回以降の秘境入口の出現率が大きく下がるようにしました。',
    ],
    [
        'id' => '2026-06-29-secret-realm-gate-rate-down',
        'date' => '2026-06-29',
        'category' => 'balance',
        'title' => '秘境入口の出現率を調整',
        'detail' => '探索度が高い場所でも秘境入口が出すぎないよう、基本出現率を控えめにしました。',
    ],
    [
        'id' => '2026-06-29-batch-explore-dungeon-lord-stop',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '10回探索の主遭遇表示を修正',
        'detail' => '10回探索中にダンジョン主と遭遇した時、敗北ではなく遭遇による停止として表示するようにしました。',
    ],
    [
        'id' => '2026-06-29-batch-explore-hp-warning-inline',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '10回探索のHP警告を改善',
        'detail' => 'HPが少ない時の10回探索警告を、探索ボタンの近くに表示して分かりやすくしました。',
    ],
    [
        'id' => '2026-06-29-batch-explore-mark-results',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '10回探索の印結果を表示',
        'detail' => '10回探索中に獲得した印を、結果画面で回数ごとに確認できるようにしました。',
    ],
    [
        'id' => '2026-06-29-storage-expand-bonus-adjusted',
        'date' => '2026-06-29',
        'category' => 'balance',
        'title' => '倉庫拡張の増加枠を調整',
        'detail' => '素材倉庫は+500、装備倉庫は+100に増やし、過去の購入分にも差分を補填しました。',
    ],
    [
        'id' => '2026-06-29-home-horizontal-scroll-fix',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '画面の横スクロールを修正',
        'detail' => 'ホーム画面などで意図せず横にスライドできる場合がある表示崩れを修正しました。',
    ],
    [
        'id' => '2026-06-29-adventurer-records-expanded',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '冒険者カードの記録を拡充',
        'detail' => '冒険者カードの冒険の記録に、勝率・称号数・所持装備数・素材数・闘技場成績などを追加しました。',
    ],
    [
        'id' => '2026-06-29-valmon-case-color-select',
        'date' => '2026-06-29',
        'category' => 'added',
        'title' => 'ヴァルモンケース色替えを追加',
        'detail' => 'プロフィール編集で、冒険者カード内のヴァルモンケースの色違いを選べるようにしました。',
    ],
    [
        'id' => '2026-06-29-adventurer-card-equipment-restore',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '冒険者カードの装備表示を復旧',
        'detail' => '冒険者カード内で、現在装備している武器・防具・装飾品を再び確認できるようにしました。',
    ],
    [
        'id' => '2026-06-29-profile-edit-card-options-simplified',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => 'プロフィール編集を整理',
        'detail' => 'プロフィール編集の冒険者カード設定から大きなプレビューを外し、牧場背景の選択表示も停止しました。',
    ],
    [
        'id' => '2026-06-29-adventurer-card-asset-select',
        'date' => '2026-06-29',
        'category' => 'added',
        'title' => '冒険者カード装飾を選択可能に',
        'detail' => 'プロフィール編集で、入手済みの冒険者カード背景・四角枠・キャラ枠を選べるようにしました。',
    ],
    [
        'id' => '2026-06-29-valmon-badge-case-profile',
        'date' => '2026-06-29',
        'category' => 'added',
        'title' => 'ヴァルモンケースを追加',
        'detail' => '冒険者カードに、仲間にしたヴァルモンを3行7列のバッジケース風に確認できる表示を追加しました。',
    ],
    [
        'id' => '2026-06-29-adventurer-card-profile-modal',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '冒険者カード表示を追加',
        'detail' => '現在の冒険者名をタップした時のプロフィール表示を、冒険者カード風の見た目に変更しました。',
    ],
    [
        'id' => '2026-06-29-profile-frame-disabled',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => 'プロフィール枠を一時停止',
        'detail' => 'プロフィール枠の選択・解放機能をいったん停止し、プロフィール編集はコメントと背景の編集に絞りました。',
    ],
    [
        'id' => '2026-06-29-batch-explore-stamina-modal',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '10回探索の回復確認を追加',
        'detail' => '探索力が10回分に足りない時、小瓶や薬を選んで回復してから探索を続けられるようにしました。',
    ],
    [
        'id' => '2026-06-29-batch-explore-10',
        'date' => '2026-06-29',
        'category' => 'added',
        'title' => '10回探索ボタンを追加',
        'detail' => '探索力を使って通常探索を最大10回まとめて進め、途中停止時も合計報酬を確認できるようにしました。',
    ],
    [
        'id' => '2026-06-29-battle-stamina-badge-position',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '戦闘後の探索力表示を調整',
        'detail' => '戦闘後に続けて探索する時、探索力の残量を再探索ボタンのすぐ上で確認できるようにしました。',
    ],
    [
        'id' => '2026-06-29-profile-frame-home-error-fix',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => 'ホーム表示エラーを修正',
        'detail' => '冒険者アイコン枠の表示処理を調整し、ホーム画面が開けなくなる場合がある不具合を修正しました。',
    ],
    [
        'id' => '2026-06-29-player-icon-frame-images',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '冒険者アイコン枠を画像化',
        'detail' => '冒険者プロフィールや闘技場表示のアイコン枠を、専用画像の枠デザインに変更しました。',
    ],
    [
        'id' => '2026-06-29-inn-rescue-streak-limit',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '宿屋の救済宿泊に連続制限',
        'detail' => '宿代が足りない救済宿泊が続いた場合、宿屋のおばちゃんが素材売却や補給所利用を案内して宿泊を断るようにしました。',
    ],
    [
        'id' => '2026-06-29-inn-rescue-message-screen',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '宿屋の救済時案内を追加',
        'detail' => '宿代が足りない状態で救済宿泊した場合、宿屋のおばちゃんから案内される専用画面を表示するようにしました。',
    ],
    [
        'id' => '2026-06-29-stamina-initial-max-by-wins',
        'date' => '2026-06-29',
        'category' => 'balance',
        'title' => '探索力の初期値を調整',
        'detail' => '探索力制へ切り替えた際、各冒険者の探索力が勝利数に応じた最大値から始まるようにしました。',
    ],
    [
        'id' => '2026-06-29-inn-no-cooldown-full-block',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '宿屋の待機時間を廃止',
        'detail' => '宿屋で休んだ後の探索待機をなくし、HP/SPが満タンの場合は案内を出して宿泊しないようにしました。',
    ],
    [
        'id' => '2026-06-29-depth-gate-retreat-direct',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '深層入口からの引き返しを短縮',
        'detail' => '次の層への入口で引き返した場合、確認画面を挟まずそのまま現在エリアの探索を続けられるようにしました。',
    ],
    [
        'id' => '2026-06-29-toast-header-gap-fix',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '通知表示時の上部余白を修正',
        'detail' => 'トースト通知が出た際に画面上部へ余白ができないようにし、ヘッダー位置がずれないよう調整しました。',
    ],
    [
        'id' => '2026-06-29-inn-gold-shortage-toast',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '宿屋の所持金不足案内を改善',
        'detail' => '宿屋の料金を手持ちGoldで払えない場合、銀行から引き出す必要があることを画面上部に表示するようにしました。',
    ],
    [
        'id' => '2026-06-29-stamina-item-use-confirm',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '探索力回復アイテムの使用確認を追加',
        'detail' => '探索力の小瓶と薬を見分けやすくし、使用前に現在の探索力と回復後の見込みを確認できるようにしました。',
    ],
    [
        'id' => '2026-06-29-stamina-items-inventory-use',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '探索力回復アイテムを所持品化',
        'detail' => '探索力の小瓶と薬を購入後すぐに回復する形式から、倉庫の所持品欄で使える形式に変更しました。',
    ],
    [
        'id' => '2026-06-29-support-item-icons',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '補給商会の商品アイコンを追加',
        'detail' => '補給商会の商品に専用アイコンを表示し、商品を見分けやすくしました。',
    ],
    [
        'id' => '2026-06-29-stamina-overcap-recovery',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '探索力回復の上限超過に対応',
        'detail' => '補給商会の探索力回復商品で、上限を超えた分も探索力として蓄積できるようにしました。',
    ],
    [
        'id' => '2026-06-29-stamina-recovery-items',
        'date' => '2026-06-29',
        'category' => 'added',
        'title' => '補給商会に探索力回復商品を追加',
        'detail' => '補給商会で、探索力を回復できる小瓶と薬を輝石で購入できるようにしました。',
    ],
    [
        'id' => '2026-06-29-stamina-review-fixes',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '探索力制の細かな不具合を修正',
        'detail' => 'ダンジョン主の遭遇案内では探索力を消費しないようにし、ボス挑戦の連続送信対策も追加しました。',
    ],
    [
        'id' => '2026-06-29-stamina-reward-one-times',
        'date' => '2026-06-29',
        'category' => 'balance',
        'title' => '探索力制の報酬倍率を調整',
        'detail' => '探索力制の通常探索で得られるEXP・Gold・職業EXPを、従来の1探索分に揃えました。',
    ],
    [
        'id' => '2026-06-29-stamina-job-exp-cap-three',
        'date' => '2026-06-29',
        'category' => 'balance',
        'title' => '探索力制の職業EXP上限を調整',
        'detail' => '探索力制の通常探索でも、1回の職業EXP獲得が1〜3の範囲に収まるよう調整しました。',
    ],
    [
        'id' => '2026-06-29-stamina-counter-display',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '探索力表示を自動更新',
        'detail' => '画面表示中に探索力が回復した場合、探索力の数字だけが自然に増えるようにしました。',
    ],
    [
        'id' => '2026-06-29-exploration-mode-unified',
        'date' => '2026-06-29',
        'category' => 'internal',
        'title' => '探索方式の切替設定を一本化',
        'detail' => '運営設定の探索方式をクールダウン/探索力の1項目に整理し、切替時の混乱を防ぐようにしました。',
    ],
    [
        'id' => '2026-06-29-treasure-log-cleanup',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '宝箱ログの重複表示を整理',
        'detail' => '輝く宝箱の獲得ログで同じ素材内容が重複して表示されないようにしました。',
    ],
    [
        'id' => '2026-06-29-result-stamina-status-badge',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => '探索状況に探索力を表示',
        'detail' => '戦闘後の探索状況カード上部で、現在の探索力を確認できるようにしました。',
    ],
    [
        'id' => '2026-06-29-monster-mark-one-roll',
        'date' => '2026-06-29',
        'category' => 'balance',
        'title' => '印ドロップの抽選を調整',
        'detail' => '探索力制の通常探索でも、モンスターが落とす印は従来の1探索分として抽選されるようにしました。',
    ],
    [
        'id' => '2026-06-29-battle-result-retry-busy-fix',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '再探索ボタンの待機表示を修正',
        'detail' => '探索直後に再探索ボタンを押した際、探索処理中の案内だけが残って探索を続けられなくなる問題を修正しました。',
    ],
    [
        'id' => '2026-06-29-stamina-button-cost-label',
        'date' => '2026-06-29',
        'category' => 'balance',
        'title' => '探索力の消費表示を追加',
        'detail' => '探索力制の通常探索・ボス挑戦ボタンに消費量を表示し、ボス挑戦も探索力を消費するようにしました。',
    ],
    [
        'id' => '2026-06-29-stamina-progress-one-roll',
        'date' => '2026-06-29',
        'category' => 'balance',
        'title' => '探索力制の進行量を調整',
        'detail' => '探索力制の通常探索で、ドロップ抽選・探索度・開拓度の進行は従来の1探索分になるよう調整しました。',
    ],
    [
        'id' => '2026-06-29-header-exploration-stamina',
        'date' => '2026-06-29',
        'category' => 'changed',
        'title' => 'ヘッダー表示に探索力を追加',
        'detail' => '画面上部のプレイヤー情報欄を整理し、探索力制の利用時は残り探索力も確認できるようにしました。',
    ],
    [
        'id' => '2026-06-29-exploration-request-delay',
        'date' => '2026-06-29',
        'category' => 'fixed',
        'title' => '探索連打の負荷対策を追加',
        'detail' => '探索ボタンを短時間に連続実行できないようにし、探索中の二重送信や連打による負荷を抑えるよう調整しました。',
    ],
    [
        'id' => '2026-06-28-exploration-stamina-switch',
        'date' => '2026-06-28',
        'category' => 'balance',
        'title' => '探索力制の切替準備を追加',
        'detail' => '通常探索を探索力消費方式へ切り替えられるようにし、探索力を消費して探索できる仕組みを準備しました。',
    ],
    [
        'id' => '2026-06-28-top-x-link-as-updates',
        'date' => '2026-06-28',
        'category' => 'changed',
        'title' => 'TOP更新情報リンクを調整',
        'detail' => 'トップページ下部のXリンクを、公式Xではなく更新情報として案内する表示に変更しました。',
    ],
    [
        'id' => '2026-06-28-top-beta-notice-update',
        'date' => '2026-06-28',
        'category' => 'changed',
        'title' => 'β版のお知らせを追記',
        'detail' => 'トップページのβ版案内に、バランス調整や不具合修正に伴う変更の可能性を追記しました。',
    ],
    [
        'id' => '2026-06-28-limit-a-rank-drop-public-logs',
        'date' => '2026-06-28',
        'category' => 'changed',
        'title' => 'Aランク装備ログを調整',
        'detail' => 'Aランク装備の通常獲得は全体チャットへ流さず、特別な装備獲得だけを知らせるようにしました。',
    ],
    [
        'id' => '2026-06-28-pve-enemy-hit-rate-floor',
        'date' => '2026-06-28',
        'category' => 'balance',
        'title' => '敵攻撃の命中率を調整',
        'detail' => '通常探索やボス戦で、敵の攻撃を回避だけで受け流し続けにくいよう命中率を調整しました。',
    ],
    [
        'id' => '2026-06-28-valzeria-castle-enemy-stats-110',
        'date' => '2026-06-28',
        'category' => 'balance',
        'title' => '魔王城の敵を強化',
        'detail' => '魔王城ヴァルゼリアの通常敵とボスを強化し、敵の攻撃を回避だけで突破しにくいよう調整しました。',
    ],
    [
        'id' => '2026-06-28-admin-battle-simulator-all-enemies',
        'date' => '2026-06-28',
        'category' => 'internal',
        'title' => '戦闘シミュの敵候補を全件表示',
        'detail' => '管理画面の戦闘シミュレーションで、登録済みの敵を全件候補として選べるようにしました。',
        'internal' => true,
    ],
    [
        'id' => '2026-06-28-admin-update-summary-limit-50',
        'date' => '2026-06-28',
        'category' => 'internal',
        'title' => '更新情報の保持件数を拡張',
        'detail' => '管理ダッシュボードの最近の更新情報を、最大50件まで確認できるようにしました。',
        'internal' => true,
    ],
    [
        'id' => '2026-06-28-top-official-x-embed',
        'date' => '2026-06-28',
        'category' => 'added',
        'title' => 'TOPに更新情報リンクを表示',
        'detail' => 'トップページ下部にXの更新情報リンクを表示し、最新のお知らせへアクセスしやすくしました。',
    ],
    [
        'id' => '2026-06-28-hide-top-update-list',
        'date' => '2026-06-28',
        'category' => 'changed',
        'title' => 'TOP更新情報を整理',
        'detail' => 'トップページ下部の更新情報一覧を非表示にし、ページ下部をすっきり見やすくしました。',
    ],
    [
        'id' => '2026-06-28-arena-ranking-power-display',
        'date' => '2026-06-28',
        'category' => 'changed',
        'title' => 'ランク戦に戦力を表示',
        'detail' => '闘技場トップランカーとランキング一覧で、冒険者やNPCランカーの戦力を確認できるようにしました。',
    ],
    [
        'id' => '2026-06-28-valmon-feed-submit-lock',
        'date' => '2026-06-28',
        'category' => 'fixed',
        'title' => 'ヴァルモン給餌の連打を防止',
        'detail' => 'ヴァルモンに餌を与えるボタンを押した後、処理中は再度押せないようにしました。',
    ],
    [
        'id' => '2026-06-28-equipped-rank-badge-fallback',
        'date' => '2026-06-28',
        'category' => 'fixed',
        'title' => '装備中ランク表示を修正',
        'detail' => '装備中の一部アイテムで、装備名の左にランク表示が出ない場合があった不具合を修正しました。',
    ],
    [
        'id' => '2026-06-28-admin-operator-analytics',
        'date' => '2026-06-28',
        'category' => 'internal',
        'title' => '統計分析を追加',
        'detail' => '管理画面で新規登録、活動者、戦闘、チャット、売上の日別推移と伸び率を確認できるようにしました。',
        'internal' => true,
    ],
    [
        'id' => '2026-06-27-protect-admin-public-logs',
        'date' => '2026-06-27',
        'category' => 'fixed',
        'title' => '管理人ログの誤削除を防止',
        'detail' => '公開ログ管理で管理人メッセージが通常の選択削除に混ざらないよう、明示的に解除した場合だけ削除できるようにしました。',
        'internal' => true,
    ],
    [
        'id' => '2026-06-27-fix-production-vite-hot',
        'date' => '2026-06-27',
        'category' => 'fixed',
        'title' => '戦闘画面の表示崩れを修正',
        'detail' => '戦闘画面でCSSが効かず表示が崩れる場合があったため、本番アセットの読み込みを修正しました。',
    ],
    [
        'id' => '2026-06-27-battle-chat-log',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '戦闘画面にログ表示を追加',
        'detail' => '戦闘中や戦闘結果画面でも、ホーム画面下部と同じチャット・公開ログを確認できるようにしました。',
    ],
    [
        'id' => '2026-06-27-admin-public-log-manager',
        'date' => '2026-06-27',
        'category' => 'internal',
        'title' => '公開ログ管理を追加',
        'detail' => '管理画面で下部チャットの各種ログを検索し、選択して削除できるようにしました。',
        'internal' => true,
    ],
    [
        'id' => '2026-06-27-area-power-normal-enemies',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '目安戦力を実敵基準に変更',
        'detail' => 'ダンジョンの目安戦力を、推奨Lvではなく実際に出る通常敵の戦力範囲から表示するようにしました。',
    ],
    [
        'id' => '2026-06-27-combat-power-balance-tuning',
        'date' => '2026-06-27',
        'category' => 'balance',
        'title' => '戦力計算の評価を調整',
        'detail' => '戦力計算でSP/MPの加点を控えめにし、素早さの評価が後半まで伸びるよう調整しました。',
    ],
    [
        'id' => '2026-06-27-champ-low-level-skill-rate',
        'date' => '2026-06-27',
        'category' => 'balance',
        'title' => 'チャンプ戦の技発動率を調整',
        'detail' => 'チャンプ戦でレベルの低い側ほど必殺技が発動しやすくなり、格上相手にも見せ場を作りやすくしました。',
    ],
    [
        'id' => '2026-06-27-power-calc-logic',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '戦力算出ロジックの改善',
        'detail' => '総合戦力の算出ロジックを最適化し、防御・精神の偏りや攻撃・魔力の特化がより正確に評価されるようにしました。またダンジョンでは連戦・踏破を前提とした「開拓目安」を表示するようにしました。',
    ],
    [
        'id' => '2026-06-27-champ-battle-skills',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => 'チャンプ戦で必殺技が発動',
        'detail' => 'チャンプ戦で挑戦者とチャンピオンが現在職の必殺技を使うようにし、戦闘ログでも発動内容を確認できるようにしました。',
    ],
    [
        'id' => '2026-06-27-combat-power-scale',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '戦力表示の値を調整',
        'detail' => '戦力の表示値を見直し、計算結果を10倍せずそのまま表示するようにしました。',
    ],
    [
        'id' => '2026-06-27-champ-card-power',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => 'チャンプ戦力を表示',
        'detail' => 'チャンプカードに現在チャンピオンの戦力とHP/SPバーを表示し、挑戦前に強さを比べやすくしました。',
    ],
    [
        'id' => '2026-06-27-mobile-header-power',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '上部バーに戦力を追加',
        'detail' => 'スマホ上部のステータスバーで、名前・レベル・職業・戦力を縦に確認できるよう表示を調整しました。',
    ],
    [
        'id' => '2026-06-27-combat-power-guidance',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '探索目安を戦力表示に変更',
        'detail' => 'ダンジョンや入口の目安を推奨Lvから目安戦力に変更し、転職後でも現在の強さと比べやすくしました。',
    ],
    [
        'id' => '2026-06-27-job-change-requires-bp-allocation',
        'date' => '2026-06-27',
        'category' => 'fixed',
        'title' => '転職前のBP割振りを必須化',
        'detail' => '未使用BPが残ったまま転職できてしまう問題を修正し、転職前にすべて能力へ割り振る必要があるようにしました。',
    ],
    [
        'id' => '2026-06-27-job-exp-gain-cap',
        'date' => '2026-06-27',
        'category' => 'balance',
        'title' => '職業EXPの獲得量を調整',
        'detail' => '探索やチャンプ戦などで一度に得られる職業EXPを抑え、職業ランクの成長ペースを調整しました。',
    ],
    [
        'id' => '2026-06-27-job-art-sp-recovery-fix',
        'date' => '2026-06-27',
        'category' => 'fixed',
        'title' => '奥義のSP回復を修正',
        'detail' => 'MP回復と表示されていた奥義をSP表記に統一し、対象の奥義で説明どおりSPが回復するよう修正しました。',
    ],
    [
        'id' => '2026-06-27-accessory-hidden-area-condition-fix',
        'date' => '2026-06-27',
        'category' => 'fixed',
        'title' => 'アクセ進化条件を修正',
        'detail' => 'アクセサリー進化の秘境条件が街道解放で満たされないようにし、裏ダンジョン解放・撃破を正しく参照するよう修正しました。',
    ],
    [
        'id' => '2026-06-27-champ-streak-fatigue',
        'date' => '2026-06-27',
        'category' => 'balance',
        'title' => 'チャンプ連勝疲労を追加',
        'detail' => 'チャンプが連勝するほど戦闘能力が少しずつ下がるようにし、挑戦者が追い上げやすいバランスに調整しました。',
    ],
    [
        'id' => '2026-06-27-header-level-job-layout',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '上部ステータス表示を調整',
        'detail' => '上部ステータスのLvと職業を縦並びにし、スマホでも職業名が読みやすい表示に調整しました。',
    ],
    [
        'id' => '2026-06-27-enemy-equipment-drop-rate-reduced',
        'date' => '2026-06-27',
        'category' => 'balance',
        'title' => '敵装備ドロップ率を調整',
        'detail' => '通常探索で敵から装備品がドロップする確率を下げ、装備更新ペースを調整しました。',
    ],
    [
        'id' => '2026-06-27-champ-level-gap-upset-damage',
        'date' => '2026-06-27',
        'category' => 'balance',
        'title' => 'チャンプ戦の格上挑戦を調整',
        'detail' => 'チャンプ戦で相手とのレベル差が大きい場合、まれに大きな追加ダメージを与えられるようにしました。',
    ],
    [
        'id' => '2026-06-27-champ-material-reward-reduced',
        'date' => '2026-06-27',
        'category' => 'balance',
        'title' => 'チャンプ戦の素材報酬を調整',
        'detail' => 'チャンプ戦で勝敗に関わらず得られる素材報酬を1〜2個に調整しました。',
    ],
    [
        'id' => '2026-06-27-sandra-exp-curve-softened',
        'date' => '2026-06-27',
        'category' => 'balance',
        'title' => 'サンドラ以降のEXPを調整',
        'detail' => '砂都サンドラ以降の敵から得られるEXPの伸びを緩やかにし、後半のレベル上昇ペースを調整しました。',
    ],
    [
        'id' => '2026-06-27-magic-seed-job-art-fix',
        'date' => '2026-06-27',
        'category' => 'fixed',
        'title' => '魔力の火種の効果を修正',
        'detail' => '魔法使いの奥義「魔力の火種」が、説明どおり小さな魔法攻撃と自身の魔力上昇を行うように修正しました。',
    ],
    [
        'id' => '2026-06-27-admin-mobile-sidebar-menu',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '管理画面メニューをスマホ改善',
        'detail' => 'スマホ表示の管理画面メニューを、左上ボタンから開閉できるサイドバー形式に変更しました。',
    ],
    [
        'id' => '2026-06-27-admin-npc-market-analytics',
        'date' => '2026-06-27',
        'category' => 'added',
        'title' => 'NPC市場の運用分析を追加',
        'detail' => '管理画面でNPCごとの調達素材、在庫、出品中数量、販売済み数量と販売額を確認できるようにしました。',
    ],
    [
        'id' => '2026-06-27-champ-next-time-jst',
        'date' => '2026-06-27',
        'category' => 'fixed',
        'title' => 'チャンプ戦の次回時刻を修正',
        'detail' => 'チャンプ戦の次回挑戦時刻が日本時間で表示されるように修正しました。',
    ],
    [
        'id' => '2026-06-27-market-npc-seller-rank-limit',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '市場NPC出品の対象を調整',
        'detail' => '市場に素材を出品するNPCから、上級職・レジェンド枠のNPCを除外しました。',
    ],
    [
        'id' => '2026-06-27-market-npc-listings-integrated',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '市場のNPC出品表示を整理',
        'detail' => 'NPCの素材出品を専用枠ではなく、通常の買う一覧に混ぜて表示するようにしました。',
    ],
    [
        'id' => '2026-06-27-affix-species-labels',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '銘付き装備の種族表示を改善',
        'detail' => '種族特効や種族耐性の説明を、対象が分かりやすい直接的な表現に調整しました。',
    ],
    [
        'id' => '2026-06-27-arena-top-rankers-five',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '闘技場トップ表示を5位まで拡張',
        'detail' => '闘技場画面のトップランカー欄で、1位から5位まで確認できるようにしました。',
    ],
    [
        'id' => '2026-06-27-npc-procurement-market-loop',
        'date' => '2026-06-27',
        'category' => 'added',
        'title' => 'NPC依頼と市場出品を連動',
        'detail' => '調達依頼の依頼者が酒場NPC本人として表示され、納品された素材をもとにNPCが市場へ出品するようになりました。',
    ],
    [
        'id' => '2026-06-27-arena-npc-equipment-names',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '闘技場NPC装備名を個性化',
        'detail' => '闘技場NPCの詳細で表示される装備名を、各NPCの雰囲気に合う固有名へ調整しました。',
    ],
    [
        'id' => '2026-06-27-arena-npc-equipment-modal',
        'date' => '2026-06-27',
        'category' => 'changed',
        'title' => '闘技場NPC詳細の表示を調整',
        'detail' => '闘技場ランキングのNPC詳細で、プレイヤーと同じように現在の装備を確認できるようにしました。',
    ],
    [
        'id' => '2026-06-27-arena-rank-gap-fix',
        'date' => '2026-06-27',
        'category' => 'fixed',
        'title' => '闘技場順位の空き番を修正',
        'detail' => 'NPC順位調整後に一部の冒険者順位が飛んで表示される場合があったため、順位が自然に並ぶよう修正しました。',
    ],
    [
        'id' => '2026-06-27-arena-npc-rank-balance',
        'date' => '2026-06-27',
        'category' => 'balance',
        'title' => '闘技場NPCの順位帯を調整',
        'detail' => '序盤の番付が詰まりすぎないよう、上級職NPCは一旦ランク外にし、NPCは下位帯から参戦して勝利で少しずつ成長するよう調整しました。',
    ],
    [
        'id' => '2026-06-27-arena-npc-rankers',
        'date' => '2026-06-27',
        'category' => 'added',
        'title' => '闘技場にNPCランカーを追加',
        'detail' => 'ランク戦の相手に酒場NPC由来の冒険者が混ざり、11位以降のランキングや詳細表示、自動順位変動にも登場するようになりました。',
    ],
    [
        'id' => '2026-06-26-tavern-npc-portraits',
        'date' => '2026-06-26',
        'category' => 'added',
        'title' => '酒場NPCのキャラ画像表示を追加',
        'detail' => '酒場で出会える冒険者や名簿に、NPCごとのキャラ画像を表示するようにしました。',
    ],
    [
        'id' => '2026-06-26-drop-armor-affixes',
        'date' => '2026-06-26',
        'category' => 'added',
        'title' => '銘付きドロップ防具を追加',
        'detail' => '敵から落ちる一部の防具に、能力銘や種族耐性が付くことがあります。',
    ],
    [
        'id' => '2026-06-26-storage-expand-price-50',
        'date' => '2026-06-26',
        'category' => 'balance',
        'title' => '倉庫拡張を利用しやすく調整',
        'detail' => '素材倉庫・装備倉庫の+50拡張に必要な輝石を50個にしました。',
    ],
    [
        'id' => '2026-06-26-job-master-rank-10-balance',
        'date' => '2026-06-26',
        'category' => 'balance',
        'title' => '職業マスター条件を統一',
        'detail' => '職業は全てランク10でマスターし、上位職ほど必要職業EXPが多くなるよう調整しました。',
    ],
    [
        'id' => '2026-06-26-job-master-display-error-fix',
        'date' => '2026-06-26',
        'category' => 'fixed',
        'title' => '職業マスター表示を修正',
        'detail' => '職業ランク表示で画面が開けなくなる場合があった不具合を修正しました。',
    ],
    [
        'id' => '2026-06-26-material-storage-limit-500',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '素材倉庫の標準枠を拡張',
        'detail' => '素材倉庫の標準上限を300個から500個に増やしました。',
    ],
    [
        'id' => '2026-06-26-job-growth-display-fix',
        'date' => '2026-06-26',
        'category' => 'fixed',
        'title' => '職業の伸びやすさ表示を修正',
        'detail' => '神殿の職業詳細で、成長倍率が高い能力を確認できるようにしました。',
    ],
    [
        'id' => '2026-06-26-job-detail-modal',
        'date' => '2026-06-26',
        'category' => 'added',
        'title' => '職業の詳細確認を追加',
        'detail' => '神殿で各職業の特徴、伸びやすい能力、奥義、マスター恩恵、必要条件を確認できるようにしました。',
    ],
    [
        'id' => '2026-06-26-profile-scrollbar-modern',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => 'プロフィール表示をさらに調整',
        'detail' => 'PC表示時のプロフィール内スクロールバーを見やすく整えました。',
    ],
    [
        'id' => '2026-06-26-profile-modal-frame-cleanup',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => 'プロフィール表示をすっきり調整',
        'detail' => '冒険者プロフィールの外周フレームを外し、内容を見やすくしました。',
    ],
    [
        'id' => '2026-06-26-valmon-toast-front',
        'date' => '2026-06-26',
        'category' => 'fixed',
        'title' => 'ヴァルモン通知を見やすく修正',
        'detail' => '餌やり後の通知がアプリ追加バナーに隠れないようにしました。',
    ],
    [
        'id' => '2026-06-26-home-action-job-change',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '転職の案内を分かりやすく',
        'detail' => '現在の職業をマスターした冒険者に、神殿で転職を確認する案内を表示するようにしました。',
    ],
    [
        'id' => '2026-06-26-valmon-feed-tab-toast',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => 'ヴァルモン餌やりを改善',
        'detail' => '餌を与えた後も餌タブに残り、結果をトーストで確認できるようにしました。',
    ],
    [
        'id' => '2026-06-26-storage-full-link',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '倉庫満杯時の導線を改善',
        'detail' => '倉庫がいっぱいの案内から、そのまま倉庫整理へ移動できるようにしました。',
    ],
    [
        'id' => '2026-06-26-drop-weapon-affixes',
        'date' => '2026-06-26',
        'category' => 'added',
        'title' => '銘付きドロップ武器を追加',
        'detail' => '敵から落ちる一部の武器に、能力銘や種族特効が付くことがあります。',
    ],
    [
        'id' => '2026-06-26-material-source-highlight',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '素材の入手場所を見つけやすく',
        'detail' => '素材の入手場所へ移動したとき、対象の探索先がより分かりやすく表示されるようにしました。',
    ],
    [
        'id' => '2026-06-26-supply-stock-breakdown',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '補給所の保管数を見やすく',
        'detail' => '補給所に残る回復アイテムを、持ち越し分と本日分に分けて確認できるようにしました。',
    ],
    [
        'id' => '2026-06-26-battle-enemy-family-display',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '敵の種族を見やすく表示',
        'detail' => '戦闘画面の敵情報で、属性等ではなく種族が分かるようにしました。',
    ],
    [
        'id' => '2026-06-26-remove-guild-chat-option',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => 'チャット送信先を整理',
        'detail' => '未使用のギルド送信先を外し、全体と個人を選びやすくしました。',
    ],
    [
        'id' => '2026-06-26-chat-history-expand',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => 'チャット履歴を見返しやすく',
        'detail' => '下部チャットの展開時に、通常より15行多く履歴を表示できるようにしました。',
    ],
    [
        'id' => '2026-06-26-depth-cooldown-tuning',
        'date' => '2026-06-26',
        'category' => 'balance',
        'title' => '探索待機を階層別に調整',
        'detail' => '表層10秒、深部15秒、深層以降20秒にし、浅い探索を進めやすくしました。',
    ],
    [
        'id' => '2026-06-26-chat-polling-interval',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '全体チャットの更新間隔を調整',
        'detail' => 'サーバー負荷を抑えるため、下部チャットの自動更新間隔を30秒にしました。',
    ],
    [
        'id' => '2026-06-26-route-area-exp-rebalance',
        'date' => '2026-06-26',
        'category' => 'balance',
        'title' => '街道の経験値を上方調整',
        'detail' => '次の街へつながる道ダンジョンの敵から、強さに見合う経験値を得られるようにしました。',
    ],
    [
        'id' => '2026-06-26-next-action-frontline-area',
        'date' => '2026-06-26',
        'category' => 'fixed',
        'title' => '次やることの探索案内を修正',
        'detail' => '到達済みの新しい街に未完了ダンジョンがある場合、前の街道ではなく本来進める場所を案内するようにしました。',
    ],
    [
        'id' => '2026-06-26-depth-recommended-level-display',
        'date' => '2026-06-26',
        'category' => 'fixed',
        'title' => '深い階層の推奨Lv表示を修正',
        'detail' => '探索中に深い階層へ進む画面で、現在の強さ設定に合う推奨Lvを表示するようにしました。',
    ],
    [
        'id' => '2026-06-26-laravel-deploy-cache',
        'date' => '2026-06-26',
        'category' => 'internal',
        'title' => '表示速度の土台を調整',
        'detail' => 'デプロイ時にLaravelの本番キャッシュを作成し、画面表示の土台を軽くしました。',
    ],
    [
        'id' => '2026-06-26-admin-chat-message',
        'date' => '2026-06-26',
        'category' => 'added',
        'title' => '管理人メッセージを追加',
        'detail' => '管理画面から全体チャットへ管理人メッセージを投稿できるようにしました。',
    ],
    [
        'id' => '2026-06-26-hide-complete-exploration-progress',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '探索結果の表示をすっきり調整',
        'detail' => '探索の進展が100%になった場所では、戦闘結果の進展表示を出し続けないようにしました。',
    ],
    [
        'id' => '2026-06-26-help-text-accordion',
        'date' => '2026-06-26',
        'category' => 'internal',
        'title' => 'ヘルプ文言編集を見やすく',
        'detail' => 'ヘルプ文言管理の各項目を開閉できるようにしました。',
    ],
    [
        'id' => '2026-06-26-help-text-admin',
        'date' => '2026-06-26',
        'category' => 'internal',
        'title' => 'ヘルプ文言を管理しやすく',
        'detail' => 'ヘルプと案内所の説明文を管理画面から編集できるようにしました。',
    ],
    [
        'id' => '2026-06-26-material-exchange-cleanup',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '素材交換所の表示を整理',
        'detail' => '現在使う交換だけを探しやすくし、使わない装備素材変換を表示から外しました。',
    ],
    [
        'id' => '2026-06-26-material-exchange-filters',
        'date' => '2026-06-26',
        'category' => 'changed',
        'title' => '素材交換所を探しやすく改善',
        'detail' => '交換カテゴリと説明文を整理し、必要な素材交換を見つけやすくしました。',
    ],
    [
        'id' => '2026-06-26-equipment-plus-five',
        'date' => '2026-06-26',
        'category' => 'balance',
        'title' => '装備をさらに鍛えられるように',
        'detail' => '鍛冶屋で装備を+5まで強化でき、欠片から強化用の石を作れるようにしました。',
    ],
    [
        'id' => '2026-06-26-admin-summary-copy-controls',
        'date' => '2026-06-26',
        'category' => 'internal',
        'title' => '更新情報をコピーしやすく改善',
        'detail' => '管理者が公開用の文面を選んでコピーできるようにしました。',
    ],
    [
        'id' => '2026-06-26-admin-update-summary',
        'date' => '2026-06-26',
        'category' => 'internal',
        'title' => '更新情報の管理機能を追加',
        'detail' => '今後の更新内容を管理画面で確認できるようにしました。',
    ],
    [
        'id' => '2026-06-25-depth-danger-reset',
        'date' => '2026-06-25',
        'category' => 'balance',
        'title' => '深い階層の探索バランスを調整',
        'detail' => '深部以降に進んだときの危険度と敵の強さを調整し、階層ごとの手応えが分かりやすくなりました。',
    ],
    [
        'id' => '2026-06-25-shop-rank-badges',
        'date' => '2026-06-25',
        'category' => 'changed',
        'title' => '装備屋でランクが見やすく',
        'detail' => '装備屋の一覧や現在の装備にランク表示を追加し、装備の強さを比べやすくしました。',
    ],
    [
        'id' => '2026-06-25-arena-rank-logs',
        'date' => '2026-06-25',
        'category' => 'changed',
        'title' => '闘技場の順位変動を分かりやすく',
        'detail' => '格上に勝つと順位が大きく上がり、順位上昇やTOP10入りが全体チャットに流れるようになりました。',
    ],
    [
        'id' => '2026-06-25-private-chat-scope',
        'date' => '2026-06-25',
        'category' => 'fixed',
        'title' => '個別チャットの表示を修正',
        'detail' => '個別チャットや手紙の内容が、全体チャット側に表示されないようにしました。',
    ],
    [
        'id' => '2026-06-25-material-drop-tuning',
        'date' => '2026-06-25',
        'category' => 'fixed',
        'title' => '地域素材を入手しやすく調整',
        'detail' => '一部の地域素材が探索で手に入る機会を増やし、素材集めを進めやすくしました。',
    ],
    [
        'id' => '2026-06-25-sell-treasure-display',
        'date' => '2026-06-25',
        'category' => 'changed',
        'title' => '換金素材が分かりやすく',
        'detail' => '探索で手に入れた換金素材を、通常素材と見分けやすい表示にしました。',
    ],
];
