<?php

return [
    'items' => [
        'explore_stamina_small_bottle' => [
            'name' => '探索力の小瓶',
            'category' => '探索支援',
            'icon_image' => 'images/icon/icon_088.webp',
            'price' => 5,
            'original_price' => 10,
            'sale_ends_at' => '2026-07-05 23:59',
            'description' => '使用すると探索力を50回復します。回復分は上限を超えて蓄積できます。',
            'effect_type' => 'explore_stamina_recovery',
            'effect_value' => 50,
            'daily_purchase_limit' => 10,
        ],
        'explore_stamina_potion' => [
            'name' => '探索力の薬',
            'category' => '探索支援',
            'icon_image' => 'images/icon/icon_089.webp',
            'price' => 12,
            'original_price' => 25,
            'sale_ends_at' => '2026-07-05 23:59',
            'description' => '使用すると探索力を150回復します。回復分は上限を超えて蓄積できます。',
            'effect_type' => 'explore_stamina_recovery',
            'effect_value' => 150,
            'daily_purchase_limit' => 10,
        ],
        'support_pass_30d' => [
            'name' => '冒険者支援パス 30日',
            'category' => '冒険者支援パス',
            'icon_image' => 'images/icon/icon_084.webp',
            'price' => 50,
            'description' => '30日間、冒険を少し快適にする支援パスです。探索力上限が+250され、冒険者カードの特別な見た目を選べるようになります。強さに直接影響する効果はありません。',
            'effect_type' => 'support_pass_30d',
            'effects' => [
                '探索力上限 +250',
                '冒険者カード見た目「支援パスカード」解放',
                '有効期間：30日',
                '自動更新なし',
            ],
        ],
        'adventurer_supply_box' => [
            'name' => '冒険者補給箱',
            'category' => '探索支援',
            'icon_image' => 'images/icon/icon_087.webp',
            'price' => 10,
            'description' => '薬草・回復薬・魔力水を各10個補充します。探索に持ち込める数は、これまで通り各10個までです。',
            'daily_purchase_limit' => 1,
        ],
        'material_storage_expand' => [
            'name' => '素材倉庫拡張',
            'category' => '保管拡張',
            'icon_image' => 'images/icon/icon_085.webp',
            'price' => 50,
            'description' => '素材の保管枠を+500します。進化素材や秘境素材を多く保管したい冒険者向けです。',
            'effect_value' => 500,
            'purchase_limit' => 10,
        ],
        'material_storage_gold_expand' => [
            'name' => '素材倉庫Gold拡張',
            'category' => '保管拡張',
            'icon_image' => 'images/icon/icon_085.webp',
            'currency' => 'gold',
            'price' => 100000,
            'description' => 'Goldを支払って素材の保管枠を+50します。少しずつ倉庫を広げたい冒険者向けです。',
            'effect_value' => 50,
            'purchase_limit' => 10,
        ],
        'equipment_storage_expand' => [
            'name' => '装備倉庫拡張',
            'category' => '保管拡張',
            'icon_image' => 'images/icon/icon_086.webp',
            'price' => 50,
            'description' => '武器・防具・装飾品の保管枠を+100します。分岐装備やレア装備を集めたい冒険者向けです。',
            'effect_value' => 100,
            'purchase_limit' => 10,
        ],
        'rescue_insurance' => [
            'name' => '救助保険証',
            'category' => '救助',
            'icon_image' => 'images/icon/icon_090.webp',
            'price' => 10,
            'description' => '探索開始前に使うと、全滅時の入手品ロストを25%に抑えます。危険な連戦に挑む前の備えです。',
            'sale_suspended' => true,
        ],
        'emergency_rescue_request' => [
            'name' => '緊急救助要請',
            'category' => '救助',
            'icon_image' => 'images/icon/icon_091.webp',
            'price' => 50,
            'description' => '全滅時に使用すると、今回の入手品ロストを0にします。ただし、探索は終了し、街へ帰還します。',
            'daily_use_limit' => 1,
            'sale_suspended' => true,
        ],
    ],
];
