<?php

return [
    'submission_price_kiseki' => 40,
    'max_message_attachments' => 4,
    'max_attachment_kilobytes' => 5120,

    'statuses' => [
        'eligible' => '下書き',
        'draft' => 'ヒアリングシート作成中',
        'submitted' => '提出済み',
        'in_progress' => '候補制作中',
        'adjustment' => '微調整中',
        'completed' => '制作完了',
    ],

    'admin_editable_statuses' => [
        'submitted',
        'in_progress',
        'adjustment',
        'completed',
    ],

    'chat_open_statuses' => [
        'submitted',
        'in_progress',
        'adjustment',
        'completed',
    ],

    'options' => [
        'usage_scenes' => [
            'game_avatar' => 'ゲーム内アバター',
        ],
        'priority' => [
            'cool' => 'かっこよさ重視',
            'cute' => 'かわいさ重視',
            'beautiful' => '美しさ重視',
            'friendly' => '親しみやすさ重視',
            'unique' => '個性重視',
            'world' => '世界観重視',
            'omakase' => 'おまかせ',
        ],
        'gender' => [
            'male' => '男性',
            'female' => '女性',
            'neutral' => '中性的',
            'any' => 'どちらでもよい',
        ],
        'age' => [
            'child' => '少年 / 少女',
            'late_teens' => '10代後半',
            'early_twenty' => '20代前半',
            'late_twenty' => '20代後半',
            'thirty_plus' => '30代以上',
            'omakase' => 'おまかせ',
        ],
        'body_type' => [
            'small' => '小柄',
            'normal' => '普通',
            'slender' => '細身',
            'muscular' => '筋肉質',
            'solid' => 'がっしり',
            'omakase' => 'おまかせ',
        ],
        'atmosphere' => [
            'fresh' => '爽やか',
            'cool' => 'クール',
            'energetic' => '元気',
            'calm' => '落ち着いた',
            'gentle' => '優しい',
            'mysterious' => 'ミステリアス',
            'noble' => '高貴',
            'wild' => 'ワイルド',
            'dark' => 'ダーク',
            'omakase' => 'おまかせ',
        ],
        'hair_color' => [
            'black' => '黒',
            'brown' => '茶',
            'blonde' => '金',
            'silver' => '白 / 銀',
            'blue' => '青',
            'red' => '赤',
            'green' => '緑',
            'purple' => '紫',
            'omakase' => 'おまかせ',
        ],
        'hairstyles' => [
            'short' => 'ショート',
            'medium' => 'ミディアム',
            'long' => 'ロング',
            'ponytail' => 'ポニーテール',
            'twintail' => 'ツインテール',
            'wavy' => 'くせ毛',
            'bangs' => '前髪あり',
            'no_bangs' => '前髪なし',
            'omakase' => 'おまかせ',
        ],
        'face_impression' => [
            'cute' => 'かわいい',
            'beautiful' => '美人 / イケメン',
            'young' => '幼め',
            'mature' => '大人っぽい',
            'dignified' => '凛々しい',
            'soft' => 'やわらかい',
            'sleepy' => '眠たげ',
            'sharp' => 'キリッとした',
            'omakase' => 'おまかせ',
        ],
        'additional_elements' => [
            'glasses' => '眼鏡',
            'mask' => '仮面',
            'eyepatch' => '眼帯',
            'animal_ears' => '獣耳',
            'horns' => '角',
            'wings' => '羽',
            'hair_accessory' => '髪飾り',
            'hat' => '帽子',
            'hood' => 'フード',
            'omakase' => 'おまかせ',
        ],
        'role' => [
            'adventurer' => '冒険者',
            'knight' => '騎士',
            'samurai' => '侍',
            'mage' => '魔法使い',
            'archer' => '弓使い',
            'priest' => '僧侶 / 司祭',
            'blacksmith' => '鍛冶師',
            'merchant' => '商人',
            'scholar' => '学者 / 研究者',
            'pirate' => '海賊 / 船長',
            'mercenary' => '傭兵',
            'royal' => '王族 / 貴族',
            'other' => 'その他',
            'omakase' => 'おまかせ',
        ],
        'region' => [
            'grandford' => '王都グランフォード',
            'arven' => '港町アーヴェン',
            'granberg' => 'グランベルグ',
            'marines' => 'マリネス',
            'frostoria' => 'フロストリア',
            'luminous' => 'ルミナス',
            'necrom' => 'ネクロム',
            'celestia' => 'セレスティア',
            'sandra' => 'サンドラ',
            'elfia' => 'エルフィア',
            'none' => '特になし',
            'new_region' => '架空の新地域でもよい',
            'omakase' => 'おまかせ',
        ],
        'motifs' => [
            'fire' => '炎',
            'ice' => '氷',
            'thunder' => '雷',
            'wind' => '風',
            'light' => '光',
            'dark' => '闇',
            'star' => '星',
            'moon' => '月',
            'flower' => '花',
            'sea' => '海',
            'forest' => '森',
            'desert' => '砂漠',
            'machine' => '機械',
            'japanese' => '和風',
            'sacred' => '神聖',
            'mysterious' => '妖しい',
            'omakase' => 'おまかせ',
        ],
        'held_item' => [
            'sword' => '片手剣',
            'great_sword' => '大剣',
            'dual_blades' => '双剣',
            'spear' => '槍',
            'bow' => '弓',
            'staff' => '杖',
            'fan' => '扇',
            'scythe' => '鎌',
            'gun' => '銃 / ガンブレード',
            'shield' => '盾',
            'hammer' => 'ハンマー',
            'book' => '本 / 魔導書',
            'instrument' => '楽器',
            'lantern' => 'ランタン',
            'none' => 'なし',
            'other' => 'その他',
            'omakase' => 'おまかせ',
        ],
        'weapon_mood' => [
            'simple' => 'シンプル',
            'gorgeous' => '豪華',
            'heavy' => '重厚',
            'agile' => '俊敏そう',
            'sacred' => '神聖',
            'ominous' => '禍々しい',
            'mechanical' => '機械的',
            'japanese' => '和風',
            'omakase' => 'おまかせ',
        ],
        'outfit_directions' => [
            'light' => '軽装',
            'medium' => '中装',
            'armor' => '鎧あり',
            'robe' => 'ローブ',
            'japanese' => '和装',
            'military' => '軍服風',
            'noble' => '貴族風',
            'exotic' => '異国風',
            'cute' => 'かわいい系',
            'cool' => 'かっこいい系',
            'omakase' => 'おまかせ',
        ],
        'expression' => [
            'smile' => '笑顔',
            'gentle_smile' => '優しい微笑み',
            'serious' => '真面目',
            'expressionless' => '無表情',
            'sharp' => 'キリッとした表情',
            'strong' => '強気',
            'mysterious' => 'ミステリアス',
            'omakase' => 'おまかせ',
        ],
        'personalities' => [
            'cheerful' => '明るい',
            'serious' => '真面目',
            'quiet' => '寡黙',
            'gentle' => '優しい',
            'passionate' => '熱血',
            'calm' => '冷静',
            'proud' => '高飛車',
            'mysterious' => '不思議系',
            'omakase' => 'おまかせ',
        ],
    ],

    'one_line_examples' => [
        '王道・主人公系' => [
            '王都を守る正義感の強い近衛騎士',
            '仲間思いの若き冒険者',
            '竜退治を夢見る見習い剣士',
            'どんな困難にも立ち向かう熱血槍使い',
            '聖剣に選ばれた寡黙な青年',
            '笑顔を絶やさない旅の治癒術師',
            '故郷を守るために戦う弓使い',
            '正義と自由を重んじる双剣士',
            '未熟だが勇気だけは誰にも負けない騎士',
            '世界を巡る好奇心旺盛な冒険者',
        ],
        'クール・かっこいい系' => [
            '無口で冷静な黒衣の剣士',
            '戦場では一切迷わない銃剣使い',
            '孤独を好む白銀の大剣士',
            '常に一歩先を読む若き軍師',
            '感情を表に出さない魔導騎士',
            '夜の任務を請け負う仮面の密偵',
            '誰にも仕えない流浪の双剣士',
            '無敗を誇る王都の決闘士',
            '影のように敵を仕留める暗殺者',
            '古びた外套をまとう歴戦の傭兵',
        ],
        '高貴・限定キャラ系' => [
            '滅びた王国の誇りを背負う騎士',
            '王家に忠誠を誓う近衛総長',
            '氷の大剣を振るう気高い姫騎士',
            '天空神殿を守る翼槍騎士',
            '神託を受けた月白の剣巫',
            '王都の秘密を守る封印守護者',
            '海軍を率いる若き銃剣提督',
            '古代の聖剣を継いだ王子',
            '星の力を操る宮廷魔術師',
            '王国最強と称される白焔騎士',
        ],
        'ダーク・ミステリアス系' => [
            '死者の魂を導く静かな墓守',
            '呪われた大剣を手放せない騎士',
            '素顔を誰にも見せない仮面の剣士',
            '失った記憶を探す機装兵',
            '月夜にだけ現れる黒鎌使い',
            '禁術を研究する孤独な魔術師',
            '魔王軍を抜けた元精鋭兵',
            '砕けた王冠を戴く亡国の黒騎士',
            '黒いランタンで魂を集める旅人',
            '自らの力を恐れている異能の少女',
        ],
        '明るい・親しみやすい系' => [
            '誰とでもすぐ仲良くなる元気な槍使い',
            'お祭りが大好きな扇の舞姫',
            '失敗してもめげない見習い魔術師',
            '豪快に笑う港町の双剣船長',
            '料理と冒険を愛する旅の料理人',
            '魔獣にも優しい陽気な獣医師',
            '酒場の人気者である世話焼き傭兵',
            '宝探しが大好きな遺跡探索士',
            '小さな竜を連れた人懐っこい薬師',
            '仲間を励ますムードメーカーの拳闘士',
        ],
        'かわいい・癒やし系' => [
            '小さな精霊と旅をする花守り',
            '星を眺めるのが好きな見習い占い師',
            '黒猫を連れた少し臆病な魔女',
            '大きな杖を抱えた眠たげな魔術師',
            '竜の卵を大切に守る飼育員',
            '森の動物に慕われる薬草師',
            'お菓子で魔法を使う菓子職人',
            '雲上牧場で働くのんびりした羊飼い',
            '小柄なのに巨大な槌を振るう少女',
            'ふわふわした白狐の旅巫女',
        ],
        '知的・専門職系' => [
            '古代遺物を研究する片眼鏡の学者',
            '星の動きから未来を読む観測士',
            '魔導機械を自作する若き技師',
            '禁書を管理する王立図書塔の司書',
            '地図にない土地を探す秘境測量士',
            '戦況を冷静に分析する扇の軍師',
            '魔法陣の研究に没頭する紋章術士',
            '深海遺跡を調査する遺物潜り',
            '魔獣の生態に詳しい研究員',
            '王都の事件を追う魔導探偵',
        ],
        '和風・東方系' => [
            '潮風を受けて旅する浪人侍',
            '桜のように美しく戦う扇武者',
            '妖を祓う狐面の退魔師',
            '主君を失って旅を続ける剣客',
            '神札と刀を扱う月白の巫女',
            '雷を宿した鉄扇で戦う女武者',
            '静かな漁村を守る弓侍',
            '花びらとともに舞う双剣士',
            '古い神社を守る白狐の神官',
            '戦場の風を読む東方の軍師',
        ],
        '港町・海洋系' => [
            '自由を愛する若き海賊船長',
            '海獣を追う寡黙な銛使い',
            '潮風になびく軍服姿の提督',
            '海底遺跡を探す冒険潜水士',
            '波止場の事件を解決する秘銃士',
            '小型海獣を連れた陽気な調教師',
            '嵐の海でも笑う豪快な航海士',
            '沈没船から宝を持ち帰る探索者',
            '海の魔法を操る穏やかな術師',
            '港の平和を守る白浪の双剣士',
        ],
        '渋い・大人系' => [
            '若者を陰から支える歴戦の騎士',
            '傷だらけの盾を持つ辺境の傭兵',
            '無口だが面倒見の良い鍛冶長',
            '数々の海を越えてきた老練な船長',
            '王都の裏事情に詳しい元宮廷銃士',
            '二度と剣を抜かないと誓った剣豪',
            '冒険者たちを見守る酒場の料理長',
            '失敗を笑い飛ばす豪快な戦鍛冶師',
            '弟子の成長を静かに見守る槍の達人',
            '過去を語らない灰狼の大盾使い',
        ],
        '特殊・印象に残る系' => [
            '巨大な鍵剣で封印門を守る騎士',
            '銀糸で精霊人形を操る貴族',
            '聖なる鏡で罪を裁く審問官',
            '砂時計を使って時間を操る術師',
            '棺に封じた剣を解放して戦う騎士',
            '浮遊する結晶だけで戦う魔導士',
            '音楽で仲間を強化する奏術師',
            '大筆で空中に術式を描く書術師',
            '双盾を武器に前線を押し上げる近衛兵',
            '魔導炉を背負って戦う機甲鍛士',
        ],
    ],

    'display_fields' => [
        ['key' => 'usage_scenes', 'label' => '使用したい場面', 'options' => 'usage_scenes'],
        ['key' => 'priority', 'label' => 'イメージ優先度', 'options' => 'priority'],
        ['key' => 'gender', 'label' => '性別イメージ', 'options' => 'gender'],
        ['key' => 'age', 'label' => '年齢イメージ', 'options' => 'age'],
        ['key' => 'body_type', 'label' => '体格', 'options' => 'body_type'],
        ['key' => 'atmosphere', 'label' => '雰囲気', 'options' => 'atmosphere'],
        ['key' => 'hair_color', 'label' => '髪色', 'options' => 'hair_color'],
        ['key' => 'hairstyles', 'label' => '髪型', 'options' => 'hairstyles'],
        ['key' => 'face_impression', 'label' => '顔の印象', 'options' => 'face_impression'],
        ['key' => 'additional_elements', 'label' => '追加したい要素', 'options' => 'additional_elements'],
        ['key' => 'role', 'label' => '職業・立場', 'options' => 'role'],
        ['key' => 'role_other', 'label' => 'その他の職業・立場'],
        ['key' => 'region', 'label' => '地域イメージ', 'options' => 'region'],
        ['key' => 'motifs', 'label' => 'モチーフ', 'options' => 'motifs'],
        ['key' => 'held_item', 'label' => '武器・小物', 'options' => 'held_item'],
        ['key' => 'held_item_other', 'label' => 'その他の武器・小物'],
        ['key' => 'weapon_mood', 'label' => '武器の雰囲気', 'options' => 'weapon_mood'],
        ['key' => 'outfit_directions', 'label' => '衣装の方向性', 'options' => 'outfit_directions'],
        ['key' => 'main_color_1', 'label' => 'メインカラー1'],
        ['key' => 'main_color_2', 'label' => 'メインカラー2'],
        ['key' => 'main_color_3', 'label' => 'メインカラー3'],
        ['key' => 'avoid_colors', 'label' => '避けたい色'],
        ['key' => 'expression', 'label' => '表情', 'options' => 'expression'],
        ['key' => 'personalities', 'label' => '性格', 'options' => 'personalities'],
        ['key' => 'must_have', 'label' => '絶対に入れたい要素'],
        ['key' => 'ng_elements', 'label' => '避けてほしい要素（NG）'],
        ['key' => 'reference_mood', 'label' => '参考にしたい雰囲気・世界観'],
        ['key' => 'one_line', 'label' => '一言で表すキャラクター像'],
    ],
];
