<?php

return [
    /*
    |--------------------------------------------------------------------------
    | 戦闘用の敵種族
    |--------------------------------------------------------------------------
    |
    | species_key は特攻・耐性・誘魔香に使う戦闘上の種族です。
    | family_key は能力値生成用の系統なので、この割り当てでは変更しません。
    |
    */
    'labels' => [
        'beast' => '獣',
        'undead' => '不死',
        'dragon' => '竜',
        'demon' => '悪魔',
        'aquatic' => '水棲',
        'flying' => '飛行',
        'insect' => '虫',
        'machine' => '機械',
        'slime' => 'スライム',
        'soldier' => '人型',
        'mage' => '魔法型',
        'spirit' => '精霊',
    ],

    /*
    |--------------------------------------------------------------------------
    | 「通常」のまま残っていた既存敵の種族
    |--------------------------------------------------------------------------
    |
    | マスターIDだけの誤更新を避けるため、Seeder と移行処理の両方で
    | ID・敵名を照合してから species_key を設定します。
    |
    */
    'assignments' => [
        18 => ['name' => '洞窟の番人スカルナイト', 'species_key' => 'undead'],
        21 => ['name' => 'ハーピー', 'species_key' => 'flying'],
        22 => ['name' => 'ならず者斥候', 'species_key' => 'soldier'],
        23 => ['name' => '群れの長', 'species_key' => 'beast'],
        28 => ['name' => '呪いガラス', 'species_key' => 'undead'],
        59 => ['name' => '船底クラーケン', 'species_key' => 'aquatic'],
        70 => ['name' => '爆弾使い', 'species_key' => 'soldier'],
        74 => ['name' => 'リーフガーディアン', 'species_key' => 'aquatic'],
        75 => ['name' => '迷宮クラブ', 'species_key' => 'aquatic'],
        76 => ['name' => '毒イソギンチャク', 'species_key' => 'aquatic'],
        86 => ['name' => '若葉ツリースピリット', 'species_key' => 'spirit'],
        88 => ['name' => '若葉毒キノコ', 'species_key' => 'spirit'],
        103 => ['name' => '中層世界樹精', 'species_key' => 'spirit'],
        105 => ['name' => '中層ハーピー', 'species_key' => 'flying'],
        107 => ['name' => '中層枝守護者', 'species_key' => 'spirit'],
        109 => ['name' => '上層世界樹精', 'species_key' => 'spirit'],
        111 => ['name' => '上層ハーピー', 'species_key' => 'flying'],
        113 => ['name' => '上層枝守護者', 'species_key' => 'spirit'],
        123 => ['name' => '月光光蝶', 'species_key' => 'insect'],
        125 => ['name' => '月光庭園番人', 'species_key' => 'spirit'],
        129 => ['name' => '鉱夫ゴースト', 'species_key' => 'undead'],
        136 => ['name' => '穴掘りモール', 'species_key' => 'beast'],
        137 => ['name' => '廃坑の主', 'species_key' => 'machine'],
        139 => ['name' => '火の精', 'species_key' => 'spirit'],
        142 => ['name' => '炎トカゲ', 'species_key' => 'dragon'],
        143 => ['name' => '溶鉱の番人', 'species_key' => 'machine'],
        157 => ['name' => '地底雷球', 'species_key' => 'machine'],
        161 => ['name' => '地底守護機', 'species_key' => 'machine'],
        171 => ['name' => '雪原ウサギ', 'species_key' => 'beast'],
        173 => ['name' => '氷の番人', 'species_key' => 'soldier'],
        175 => ['name' => '吹雪ハーピー', 'species_key' => 'flying'],
        177 => ['name' => '谷の雪男', 'species_key' => 'beast'],
        179 => ['name' => '峡谷の主', 'species_key' => 'beast'],
        184 => ['name' => '氷結トカゲ', 'species_key' => 'dragon'],
        185 => ['name' => '氷結洞窟主', 'species_key' => 'mage'],
        188 => ['name' => '雪樹の精', 'species_key' => 'spirit'],
        189 => ['name' => '氷キノコ', 'species_key' => 'spirit'],
        194 => ['name' => '氷封封印守', 'species_key' => 'soldier'],
        197 => ['name' => '氷封神殿主', 'species_key' => 'mage'],
        201 => ['name' => 'フロストリザード', 'species_key' => 'dragon'],
        206 => ['name' => 'ブリザードイーグル', 'species_key' => 'flying'],
        220 => ['name' => '流砂ミイラ', 'species_key' => 'undead'],
        222 => ['name' => '流砂の暗殺者サンドシェイド', 'species_key' => 'soldier'],
        226 => ['name' => '砂遺跡呪文壁', 'species_key' => 'machine'],
        227 => ['name' => '砂遺跡守護者', 'species_key' => 'machine'],
        229 => ['name' => '王墓ミイラ', 'species_key' => 'undead'],
        231 => ['name' => '黄金スカラベ', 'species_key' => 'insect'],
        233 => ['name' => '王家の呪霊', 'species_key' => 'undead'],
        236 => ['name' => '砂嵐封印守', 'species_key' => 'mage'],
        239 => ['name' => '砂嵐神殿主', 'species_key' => 'undead'],
        248 => ['name' => '太陽封印守', 'species_key' => 'soldier'],
        251 => ['name' => '太陽神殿主', 'species_key' => 'mage'],
        257 => ['name' => '図書館の番人', 'species_key' => 'mage'],
        262 => ['name' => '黒インクの魔物', 'species_key' => 'slime'],
        265 => ['name' => 'ホムンクルス', 'species_key' => 'mage'],
        269 => ['name' => '研究所の怪物', 'species_key' => 'demon'],
        273 => ['name' => '浮遊光蝶', 'species_key' => 'insect'],
        275 => ['name' => '浮遊庭園番人', 'species_key' => 'spirit'],
        281 => ['name' => '星見塔守護者', 'species_key' => 'soldier'],
        283 => ['name' => '異界雷球', 'species_key' => 'mage'],
        287 => ['name' => '異界守護機', 'species_key' => 'machine'],
        288 => ['name' => '異界の観測者オブザーバー', 'species_key' => 'mage'],
        290 => ['name' => '次元時空影', 'species_key' => 'mage'],
        292 => ['name' => '次元空間裂け目', 'species_key' => 'mage'],
        293 => ['name' => '次元回廊主', 'species_key' => 'mage'],
        296 => ['name' => '黒骨犬', 'species_key' => 'undead'],
        298 => ['name' => '魂喰い', 'species_key' => 'undead'],
        305 => ['name' => '呪城の主', 'species_key' => 'undead'],
        306 => ['name' => '呪城伯爵ヴラド', 'species_key' => 'undead'],
        309 => ['name' => '魂の群れ', 'species_key' => 'undead'],
        323 => ['name' => '要塞司令', 'species_key' => 'soldier'],
        327 => ['name' => '谷の死霊', 'species_key' => 'undead'],
        329 => ['name' => '瘴気の主', 'species_key' => 'demon'],
        331 => ['name' => '奈落の影', 'species_key' => 'demon'],
        334 => ['name' => '階段の番人', 'species_key' => 'machine'],
        344 => ['name' => '天空時空影', 'species_key' => 'mage'],
        346 => ['name' => '天空空間裂け目', 'species_key' => 'mage'],
        347 => ['name' => '天空回廊主', 'species_key' => 'mage'],
        350 => ['name' => '雷鳴封印守', 'species_key' => 'machine'],
        353 => ['name' => '雷鳴神殿主', 'species_key' => 'mage'],
        358 => ['name' => '天空呪文壁', 'species_key' => 'machine'],
        359 => ['name' => '天空遺跡守護者', 'species_key' => 'machine'],
        363 => ['name' => '天使光蝶', 'species_key' => 'insect'],
        365 => ['name' => '天使庭園番人', 'species_key' => 'spirit'],
        366 => ['name' => '庭園の癒天使ラファエラ', 'species_key' => 'spirit'],
        371 => ['name' => '星辰塔守護者', 'species_key' => 'soldier'],
        374 => ['name' => '神域祭壇天使', 'species_key' => 'spirit'],
        375 => ['name' => '神域星守護者', 'species_key' => 'spirit'],
        376 => ['name' => '神域神官', 'species_key' => 'mage'],
        377 => ['name' => '雷神ヴォルト', 'species_key' => 'spirit'],
        378 => ['name' => '神々の代行者プロヴィデンス', 'species_key' => 'spirit'],
        381 => ['name' => '外郭ガーゴイル', 'species_key' => 'demon'],
        382 => ['name' => '魔城の番犬', 'species_key' => 'beast'],
        386 => ['name' => '絶望時空影', 'species_key' => 'demon'],
        388 => ['name' => '絶望空間裂け目', 'species_key' => 'demon'],
        389 => ['name' => '絶望回廊主', 'species_key' => 'demon'],
        390 => ['name' => '絶望の幻影ディスペア', 'species_key' => 'demon'],
        401 => ['name' => '牢獄の主', 'species_key' => 'demon'],
        402 => ['name' => '深淵の獄卒タルタロス', 'species_key' => 'demon'],
        407 => ['name' => '黒き玉座の主', 'species_key' => 'demon'],
        410 => ['name' => '中枢守護機', 'species_key' => 'machine'],
        413 => ['name' => '中枢の守護者', 'species_key' => 'machine'],
        416 => ['name' => '終焉祭壇天使', 'species_key' => 'spirit'],
        417 => ['name' => '終焉星守護者', 'species_key' => 'spirit'],
        418 => ['name' => '終焉神官', 'species_key' => 'mage'],
        419 => ['name' => '終焉ヴォルト', 'species_key' => 'spirit'],
        422 => ['name' => '錬成炉守護者オルディオン', 'species_key' => 'machine'],
        424 => ['name' => '次元回廊の支配者クロノアーク', 'species_key' => 'mage'],
    ],
];
