<?php

return [
    'seed_secret' => env('MAP_SEED_SECRET', env('APP_KEY', 'local-map-seed-secret')),
    'enabled' => env('EXPLORATION_MAPS_ENABLED', true),
    'public_hours' => 72,
    'closed_map_display_hours' => 6,
    'survey' => [
        'base_cost' => 5000,
        'base_minutes' => 0,
    ],
    'entry_fee' => [
        // The expected value is intentionally conservative until live economy data exists.
        'recommended_rate' => 0.15,
        'maximum_rate' => 0.35,
        'expected_value_per_level' => 12,
        'minimum' => 0,
        'owner_share' => 70,
        'town_share' => 20,
        'system_share' => 10,
    ],
    'reward_balance' => [
        // 地図の補正後戦力に最も近い既存通常敵を基準に、少し上回る報酬を設定する。
        'reference_city_range' => [1, 10],
        'reference_premium_multiplier' => 1.10,
    ],
    'material_drop' => [
        // 公開地図では地域・敵固有素材を狙いやすくするため、汎用素材の候補重みだけを抑える。
        'common_material_weight_multiplier' => 0.5,
    ],
    'reward_profiles' => [
        'experience' => ['label' => '経験の導き', 'modifiers' => ['exp_multiplier' => 1.20]],
        'wealth' => ['label' => '金運上昇', 'modifiers' => ['gold_multiplier' => 1.50]],
        'training' => ['label' => '修練の導き', 'modifiers' => ['job_exp_multiplier' => 2.0, 'job_exp_cap' => 6]],
        'material' => ['label' => '素材探索', 'modifiers' => ['material_drop_bonus_points' => 5]],
        'equipment' => ['label' => '装備の兆し', 'modifiers' => ['equipment_drop_bonus_points' => ['weapon' => 0.10, 'armor' => 0.10, 'accessory' => 0.03]]],
        'windfall' => ['label' => '落銭の気配', 'modifiers' => ['gold_drop_rate_bonus_points' => 3]],
        'vitality' => ['label' => '精気の余韻', 'modifiers' => ['victory_hp_recovery_percent' => 1.5, 'victory_sp_recovery_percent' => 0.5]],
    ],
    'drop_rates_basis_points' => [
        'normal' => 20,
        'elite' => 120,
        'boss' => 300,
        'local_boss' => 700,
        'map_normal' => 30,
        'map_elite' => 200,
    ],
    'launch_bonus' => [
        'enabled' => true,
        'multiplier' => 3,
        'ends_at' => '2026-07-29 23:59:59',
    ],
    'grade_limits' => [
        'normal' => ['min' => 600, 'max' => 1000],
        'rare' => ['min' => 1000, 'max' => 1400],
        'hero' => ['min' => 1400, 'max' => 1800],
        'legend' => ['min' => 1800, 'max' => 2000],
    ],
    'grade_level_offsets' => [
        'normal' => ['min' => 0, 'max' => 5],
        'rare' => ['min' => 8, 'max' => 15],
        'hero' => ['min' => 20, 'max' => 30],
        'legend' => ['min' => 35, 'max' => 50],
    ],
    // 探索地の系統は、アークレアからヴァルゼリアまで均等に抽選する。
    'target_city_weights' => [1 => 1, 2 => 1, 3 => 1, 4 => 1, 5 => 1, 6 => 1, 7 => 1, 8 => 1, 9 => 1, 10 => 1],
    // 出現敵Lvは探索地の系統と切り離し、中級〜上級帯を基本にする。
    'target_enemy_level_range' => ['min' => 45, 'max' => 140],
    'map_name_parts' => [
        'mine' => [
            ['灰燼に沈む', '炎に呑まれた', '赤熱する', '溶岩に揺らぐ', '焦土に眠る', '煉獄を映す', '火花散る', '燃え盛る', '鉄煙に霞む', '業火に包まれた', '炉心に近づく', '鉱炎が渦巻く'],
            ['黒炉', '赤晶', '熔鉄', '火喰', '焦岩', '灰鉄', '炉心', '煉火', '鉄火', '紅蓮', '火脈', '熔岩', '烈火'],
            ['深坑', '廃鉱', '溶岩洞', '坑道', '鍛冶遺構', '鉱脈', '炉跡', '地底炉', '火口洞', '採掘場', '焼けた坑', '鉄塊墓', '灼鉱洞'],
        ],
        'ice' => [
            ['氷晶に閉ざされた', '白雪に眠る', '凍てついた', '月光に凍る', '吹雪に消えた', '蒼氷に沈む', '霜風が鳴く', '永久凍土の', '銀世界に埋もれた', '寒星に照らされた'],
            ['白氷', '霜月', '凍晶', '銀雪', '氷華', '蒼霜', '雪影', '冬星', '氷冠', '凍雲'],
            ['氷窟', '凍結回廊', '氷晶宮', '霜穴', '雪原洞', '氷河墓所', '白銀洞', '凍土遺跡', '氷壁迷宮', '寒月峡谷'],
        ],
        'forest' => [
            ['精霊が眠る', '深緑に覆われた', '古樹に守られた', '月影に揺れる', '花霧に隠れた', '木漏れ日に沈む', '獣たちが囁く', '翠風が吹き抜ける', '永樹に抱かれた', '妖精火の灯る'],
            ['翠霊', '古樹', '月葉', '深緑', '花霞', '樹影', '風詠', '碧森', '森羅', '若葉'],
            ['樹海', '森宮', '大樹洞', '霊域', '深森', '花園跡', '木霊の谷', '古木迷宮', '月影林', '精霊庭園'],
        ],
        'desert' => [
            ['黄金を秘めた', '王家に封じられた', '財宝眠る', '陽炎に揺らぐ', '砂嵐に埋もれた', '灼砂に沈む', '太陽に焼かれた', '古王の呪われた', '流砂に呑まれた', '月砂が照らす'],
            ['黄金', '砂王', '陽炎', '古王', '砂月', '紅砂', '王印', '炎砂', '乾坤', '白砂'],
            ['王墓', '地下神殿', '砂宮', '埋没遺跡', '砂海洞', '流砂迷宮', '石棺廟', '太陽塔', '砂嵐谷', '王都跡'],
        ],
        'magic' => [
            ['星影に揺らぐ', '禁呪に閉ざされた', '幻光に沈む', '闇に呑まれた', '魔力が渦巻く', '虚空に浮かぶ', '蒼雷に照らされた', '秘術に封じられた', '宵闇を映す', '星詠みが眠る'],
            ['星魔', '蒼晶', '禁呪', '虚空', '虚無', '幻月', '雷光', '深識', '宵星', '天文'],
            ['研究塔', '魔導回廊', '禁書庫', '異空間', '魔宮', '虚無魔宮', '星詠みの塔', '封印実験場', '幻光迷宮', '魔導書院'],
        ],
        'abyss' => [
            ['深淵に侵された', '闇に呑まれた', '奈落へ続く', '冥き海に沈む', '絶望が満ちる', '魔瘴に覆われた', '黒月に照らされた', '魂を喰らう', '終焉を告げる', '虚無に裂かれた'],
            ['黒月', '奈落', '冥界', '虚無', '深魔', '滅び', '魔哭', '終焉', '黒炎', '冥王'],
            ['魔宮', '深層域', '黒き裂け目', '奈落門', '奈落魔宮', '冥府迷宮', '魔界回廊', '黒曜要塞', '終焉洞', '虚無裂界'],
        ],
    ],
    'level_scaling' => [
        'hp_per_level' => 0.04,
        'combat_stat_per_level' => 0.02,
    ],
    'threat_tiers' => [
        ['min' => 1, 'max' => 14, 'name' => '見習い級', 'max_fee_multiplier' => 1.0],
        ['min' => 15, 'max' => 29, 'name' => '駆け出し級', 'max_fee_multiplier' => 1.0],
        ['min' => 30, 'max' => 44, 'name' => '熟練級', 'max_fee_multiplier' => 1.0],
        ['min' => 45, 'max' => 59, 'name' => '強敵級', 'max_fee_multiplier' => 1.0],
        ['min' => 60, 'max' => 74, 'name' => '猛者級', 'max_fee_multiplier' => 1.0],
        ['min' => 75, 'max' => 89, 'name' => '英雄級', 'max_fee_multiplier' => 1.2],
        ['min' => 90, 'max' => 104, 'name' => '伝説級', 'max_fee_multiplier' => 1.4],
        ['min' => 105, 'max' => 119, 'name' => '覇者級', 'max_fee_multiplier' => 1.6],
        ['min' => 120, 'max' => 134, 'name' => '極地級', 'max_fee_multiplier' => 2.0],
        ['min' => 135, 'max' => 149, 'name' => '深淵級', 'max_fee_multiplier' => 2.5],
        ['min' => 150, 'max' => 164, 'name' => '冥府級', 'max_fee_multiplier' => 3.0],
        ['min' => 165, 'max' => 179, 'name' => '魔境級', 'max_fee_multiplier' => 3.5],
        ['min' => 180, 'max' => 194, 'name' => '奈落級', 'max_fee_multiplier' => 4.5],
        ['min' => 195, 'max' => 209, 'name' => '終焉級', 'max_fee_multiplier' => 5.5],
        ['min' => 210, 'max' => 224, 'name' => '滅界級', 'max_fee_multiplier' => 6.5],
        ['min' => 225, 'max' => 239, 'name' => '冥界級', 'max_fee_multiplier' => 7.5],
        ['min' => 240, 'max' => 255, 'name' => '神話級', 'max_fee_multiplier' => 9.0],
    ],
    'town_biomes' => [
        1 => ['ruins', 'fortress', 'underground_waterway'],
        2 => ['coastal_cave', 'sunken_ship', 'undersea_ruins'],
        3 => ['forest', 'great_tree', 'spirit_realm'],
        4 => ['mine_volcano', 'ancient_forge', 'abyss_cave'],
        5 => ['ice_cave', 'snow_mountain', 'frozen_ruins'],
        6 => ['royal_tomb', 'desert_cave', 'underground_temple'],
        7 => ['magic_tower', 'laboratory', 'otherworld'],
        8 => ['graveyard', 'catacomb', 'cursed_ruins'],
        9 => ['sky_ruins', 'temple', 'sanctuary'],
        10 => ['abyss', 'demon_realm', 'demon_fortress'],
    ],
    'dungeon_type_labels' => [
        'ruins' => '古代遺跡', 'fortress' => '城塞跡', 'underground_waterway' => '地下水路',
        'coastal_cave' => '海岸洞窟', 'sunken_ship' => '沈没船', 'undersea_ruins' => '海底遺跡',
        'forest' => '深い森', 'great_tree' => '大樹の洞', 'spirit_realm' => '精霊の住処',
        'mine_volcano' => '火山鉱山', 'ancient_forge' => '古い鍛冶遺跡', 'abyss_cave' => '深淵の洞窟',
        'ice_cave' => '氷の洞窟', 'snow_mountain' => '雪山', 'frozen_ruins' => '凍った遺跡',
        'royal_tomb' => '王家の墓', 'desert_cave' => '砂漠の洞窟', 'underground_temple' => '地下神殿',
        'magic_tower' => '魔導塔', 'laboratory' => '研究所跡', 'otherworld' => '異界',
        'graveyard' => '墓地', 'catacomb' => '地下墓所', 'cursed_ruins' => '呪われた廃墟',
        'sky_ruins' => '天空遺跡', 'temple' => '神殿', 'sanctuary' => '聖域',
        'abyss' => '深淵', 'demon_realm' => '魔界', 'demon_fortress' => '魔族の要塞',
    ],
    'dungeon_card_backgrounds' => [
        'ruins' => 'images/chizu/map-bg-mossy-ruins.webp',
        'fortress' => 'images/chizu/map-bg-fallen-fortress.webp',
        'underground_waterway' => 'images/chizu/map-bg-underground-waterway-new.webp',
        'coastal_cave' => 'images/chizu/map-bg-blue-coastal-cave.webp',
        'sunken_ship' => 'images/chizu/map-bg-blue-coastal-cave.webp',
        'undersea_ruins' => 'images/chizu/map-bg-sunken-temple.webp',
        'forest' => 'images/chizu/map-bg-deep-forest.webp',
        'great_tree' => 'images/chizu/map-bg-ancient-great-tree.webp',
        'spirit_realm' => 'images/chizu/map-bg-luminous-mushrooms.webp',
        'mine_volcano' => 'images/chizu/map-bg-lava-cave.webp',
        'ancient_forge' => 'images/chizu/map-bg-ancient-furnace.webp',
        'abyss_cave' => 'images/chizu/map-bg-flame-tunnel.webp',
        'ice_cave' => 'images/chizu/map-bg-ice-crystal-cave.webp',
        'snow_mountain' => 'images/chizu/map-bg-blizzard-mountain.webp',
        'frozen_ruins' => 'images/chizu/map-bg-snowy-ruins.webp',
        'royal_tomb' => 'images/chizu/map-bg-golden-tomb.webp',
        'desert_cave' => 'images/chizu/map-bg-buried-desert-cave.webp',
        'underground_temple' => 'images/chizu/map-bg-underground-temple.webp',
        'magic_tower' => 'images/chizu/map-bg-arcane-tower.webp',
        'laboratory' => 'images/chizu/map-bg-magic-laboratory.webp',
        'otherworld' => 'images/chizu/map-bg-otherworld-crystal-new.webp',
        'graveyard' => 'images/chizu/map-bg-graveyard-new.webp',
        'catacomb' => 'images/chizu/map-bg-catacomb-new.webp',
        'cursed_ruins' => 'images/chizu/map-bg-cursed-ruins.webp',
        'sky_ruins' => 'images/chizu/map-bg-floating-sanctuary.webp',
        'temple' => 'images/chizu/map-bg-underground-temple.webp',
        'sanctuary' => 'images/chizu/map-bg-floating-sanctuary.webp',
        'abyss' => 'images/chizu/map-bg-dark-rift.webp',
        'demon_realm' => 'images/chizu/map-bg-crimson-demon-realm.webp',
        'demon_fortress' => 'images/chizu/map-bg-demon-castle.webp',
    ],
];
