<?php

return [
    'trial_masters' => [
        'aurora' => [
            'name' => '双極天騎アウローラ',
            'species_keys' => ['spirit', 'soldier'],
        ],
        'lunagrim' => [
            'name' => '月喰影獣ルナグリム',
            'species_keys' => ['beast', 'demon'],
        ],
        'asterion' => [
            'name' => '天象魔導核アステリオン',
            'species_keys' => ['mage', 'machine'],
        ],
        'azragion' => [
            'name' => '蒼穹古竜アズラギオン',
            'species_keys' => ['dragon', 'flying'],
        ],
        'seeker' => [
            'name' => '天機偵察機シーカー',
            'species_keys' => ['machine', 'flying'],
        ],
        'bastion' => [
            'name' => '天機重装機バスティオン',
            'species_keys' => ['machine', 'soldier'],
        ],
        'oracle' => [
            'name' => '天機演算核オラクル',
            'species_keys' => ['machine', 'mage'],
        ],
        'justia' => [
            'name' => '天秤聖獣ユスティア',
            'species_keys' => ['beast', 'spirit'],
        ],
        'necrodia' => [
            'name' => '魂葬王ネクロディア',
            'species_keys' => ['undead', 'mage'],
        ],
        'aeon' => [
            'name' => '時環の観測者エオン',
            'species_keys' => ['mage', 'spirit'],
        ],
        'tempesta' => [
            'name' => '雷嵐神獣テンペスタ',
            'species_keys' => ['beast', 'spirit'],
        ],
        'argeon' => [
            'name' => '白銀城塞アルジェオン',
            'species_keys' => ['machine', 'spirit'],
        ],
    ],
    'hall_cards' => [
        'dawn_hero' => [
            'label' => '暁の試練場',
            'symbol_image' => 'symbol/hero_trial_070.webp',
            'facility_desc' => '夜明けを告げる光が、静かに挑戦者を待っている。',
        ],
        'black_moon_executor' => [
            'label' => '月蝕の試練場',
            'symbol_image' => 'symbol/hero_trial_071.webp',
            'facility_desc' => '欠けた月の影が、音もなく殿内へ伸びている。',
        ],
        'star_heaven_sage' => [
            'label' => '星天の試練場',
            'symbol_image' => 'symbol/hero_trial_072.webp',
            'facility_desc' => '遥かな星々の光が、一つの扉へ集まっている。',
        ],
        'azure_dragon_warrior_king' => [
            'label' => '蒼竜の試練場',
            'symbol_image' => 'symbol/hero_trial_073.webp',
            'facility_desc' => '蒼穹の彼方から、天地を揺らす気配が響く。',
        ],
        'heavenly_machina_chancellor' => [
            'label' => '天機の試練場',
            'symbol_image' => 'symbol/hero_trial_074.webp',
            'facility_desc' => '閉ざされた機構が、訪れる者を測るように脈動する。',
        ],
        'sanctuary_judge' => [
            'label' => '聖域の試練場',
            'symbol_image' => 'symbol/hero_trial_075.webp',
            'facility_desc' => '穢れなき静寂の奥で、厳かな光が揺れている。',
        ],
        'phantom_funeral_demon_king' => [
            'label' => '幻葬の試練場',
            'symbol_image' => 'symbol/hero_trial_076.webp',
            'facility_desc' => '遠い鐘の音とともに、淡い魂火が漂っている。',
        ],
        'time_reader_traveler' => [
            'label' => '時環の試練場',
            'symbol_image' => 'symbol/hero_trial_077.webp',
            'facility_desc' => '止まったはずの刻が、扉の向こうで巡り続ける。',
        ],
        'storm_overlord' => [
            'label' => '荒天の試練場',
            'symbol_image' => 'symbol/hero_trial_078.webp',
            'facility_desc' => '黒雲の奥で雷光が走り、殿堂の空気を震わせる。',
        ],
        'silver_guardian_king' => [
            'label' => '白銀の試練場',
            'symbol_image' => 'symbol/hero_trial_079.webp',
            'facility_desc' => '白銀に輝く門が、微動だにせず行く手を阻んでいる。',
        ],
    ],
    'released_trials' => [
        'dawn_hero' => [
            'label' => '暁の試練場',
            'profile_key' => 'dawn_hero_balanced',
            'area_id' => 84,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'dawn_hero',
            'hero_job_name' => '暁の勇者',
            'required_job_key' => 'crown_sword_knight',
            'required_job_name' => '剣冠騎士',
            'symbol_image' => 'symbol/hero_trial_070.webp',
            'job_badge_image' => 'jobbadge/jobbadge_070.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '二形態連続戦闘',
            'facility_desc' => '光と剣、二つの相が挑戦者を待つ。',
            'cleared_desc' => '二つの相を越えた者に、暁の道が開かれる。',
            'challenge_action' => '二形態試練に挑む',
            'mechanic_details' => [
                '剣相から術相へHP/SPを引き継いで連戦',
                '両形態撃破で暁の勇者解放',
            ],
            'victory_title' => '双極天騎アウローラの二つの相を打ち破った！',
            'retry_message' => '宿屋でHP/SPを整えれば、暁の試練場から再挑戦できる。',
        ],
        'black_moon_executor' => [
            'label' => '月蝕の試練場',
            'profile_key' => 'black_moon_executor_balanced',
            'area_id' => 85,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'black_moon_executor',
            'hero_job_name' => '黒月の執行者',
            'required_job_key' => 'shadow_crown_hunter',
            'required_job_name' => '影冠狩人',
            'symbol_image' => 'symbol/hero_trial_071.webp',
            'job_badge_image' => 'jobbadge/jobbadge_071.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '月蝕高速戦',
            'facility_desc' => '月影を渡る獣が、挑戦者の一瞬の隙を狙っている。',
            'cleared_desc' => '月影を捉えた者に、黒月の道が開かれる。',
            'challenge_action' => '月蝕の試練に挑む',
            'mechanic_details' => [
                '高い敏捷と回避を持つ月喰影獣との一騎討ち',
                '月影縛りで敏捷を奪い、長期戦では攻撃性能が上昇',
                'ルナグリム撃破で黒月の執行者解放',
            ],
            'victory_title' => '月喰影獣ルナグリムの月影を捉えた！',
            'retry_message' => '宿屋でHP/SPを整えれば、月蝕の試練場から再挑戦できる。',
        ],
        'star_heaven_sage' => [
            'label' => '星天の試練場',
            'profile_key' => 'star_heaven_sage_balanced',
            'area_id' => 86,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'star_heaven_sage',
            'hero_job_name' => '星天導師',
            'required_job_key' => 'star_crown_sage',
            'required_job_name' => '星冠導師',
            'symbol_image' => 'symbol/hero_trial_072.webp',
            'job_badge_image' => 'jobbadge/jobbadge_072.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '星天魔導戦',
            'facility_desc' => '星図を巡る魔導核が、挑戦者の精神を見定めている。',
            'cleared_desc' => '星々の導きを掴んだ者に、星天の道が開かれる。',
            'challenge_action' => '星天の試練に挑む',
            'mechanic_details' => [
                '精神を揺らす魔法と、予兆を伴う大魔法を放つ',
                'アステリオン撃破で星天導師解放',
            ],
            'victory_title' => '天象魔導核アステリオンの星図を打ち破った！',
            'retry_message' => '宿屋でHP/SPを整えれば、星天の試練場から再挑戦できる。',
        ],
        'time_reader_traveler' => [
            'label' => '時環の試練場',
            'profile_key' => 'time_reader_traveler_balanced',
            'area_id' => 87,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'time_reader_traveler',
            'hero_job_name' => '時詠みの旅人',
            'required_job_key' => 'gold_crown_alchemist',
            'required_job_name' => '金冠錬師',
            'symbol_image' => 'symbol/hero_trial_077.webp',
            'job_badge_image' => 'jobbadge/jobbadge_077.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '時環高速魔導戦',
            'facility_desc' => '巡る刻の観測者が、挑戦者の一瞬先を見つめている。',
            'cleared_desc' => '時の流れを越えた者に、時詠みの道が開かれる。',
            'challenge_action' => '時環の試練に挑む',
            'mechanic_details' => [
                '敏捷を奪う魔法と連続魔法で行動の主導権を握る',
                '長期戦では加速し、さらに先手を取りやすくなる',
                'エオン撃破で時詠みの旅人解放',
            ],
            'victory_title' => '時環の観測者エオンの刻を越えた！',
            'retry_message' => '宿屋でHP/SPを整えれば、時環の試練場から再挑戦できる。',
        ],
    ],
    'profiles' => [
        'dawn_hero_balanced' => [
            'trial_key' => 'dawn_hero',
            'label' => '暁の勇者・標準候補',
            'hero_job_key' => 'dawn_hero',
            'required_job_key' => 'crown_sword_knight',
            'required_job_name' => '剣冠騎士',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => true,
            'benchmark' => [
                'measured_on' => '2026-08-03',
                'runs' => 60,
                'passes' => 44,
                'pass_rate' => 73.3,
                'basis' => '測定時点の首位10冠キャラクターを剣冠騎士へ仮想切替',
                'note' => '術相の通常攻撃を魔法固定へ変更する前の参考値。現行設定は再測定が必要。',
            ],
            'phases' => [
                [
                    'key' => 'sword_form',
                    'trial_master_key' => 'aurora',
                    'label' => '第1形態・剣相',
                    'image_path' => 'images/enemy/enemy_723.webp',
                    'type_name' => '物理型',
                    'max_hp' => 70_000,
                    'str' => 6_750,
                    'def' => 5_250,
                    'agi' => 5_000,
                    'mag' => 3_000,
                    'spr' => 4_500,
                    'luk' => 4_500,
                ],
                [
                    'key' => 'spell_form',
                    'trial_master_key' => 'aurora',
                    'label' => '第2形態・術相',
                    'image_path' => 'images/enemy/enemy_735.webp',
                    'type_name' => '魔法型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 70_000,
                    'str' => 3_000,
                    'def' => 4_500,
                    'agi' => 5_000,
                    'mag' => 7_250,
                    'spr' => 5_750,
                    'luk' => 4_500,
                    'transition_title' => '双極天騎アウローラを倒した！',
                    'transition_body' => 'が、その姿が変わっていく……！！',
                ],
            ],
        ],
        'black_moon_executor_balanced' => [
            'trial_key' => 'black_moon_executor',
            'label' => '黒月の執行者・標準候補',
            'hero_job_key' => 'black_moon_executor',
            'required_job_key' => 'shadow_crown_hunter',
            'required_job_name' => '影冠狩人',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => false,
            'benchmark' => [
                'measured_on' => '2026-08-04',
                'runs' => 500,
                'passes' => 407,
                'pass_rate' => 81.4,
                'basis' => 'ローカルLv250キャラクター、開始HP/SP全快、保存・報酬なし',
                'note' => '装備中の精霊特攻はルナグリムの獣/悪魔に不一致。ATK 7,500の最終候補値で測定。',
            ],
            'phases' => [
                [
                    'key' => 'lunar_eclipse',
                    'trial_master_key' => 'lunagrim',
                    'label' => '月蝕相',
                    'image_path' => 'images/enemy/enemy_724.webp',
                    'type_name' => '高速妨害型',
                    'max_hp' => 52_000,
                    'str' => 7_500,
                    'def' => 4_000,
                    'agi' => 8_500,
                    'mag' => 3_200,
                    'spr' => 4_200,
                    'luk' => 6_500,
                    'actions' => [
                        [
                            'action_key' => 'moon_shadow_bind',
                            'name' => '月影縛り',
                            'action_type' => 'slow',
                            'selection_weight' => 100,
                            'power_percent' => 80,
                            'effect_percent' => 20,
                            'duration_turns' => 2,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'guarantee_first_use' => true,
                        ],
                        [
                            'action_key' => 'eclipse_fang_dance',
                            'name' => '蝕牙連舞',
                            'action_type' => 'multi_hit',
                            'selection_weight' => 100,
                            'power_percent' => 80,
                            'hit_count' => 2,
                            'cooldown_turns' => 2,
                        ],
                        [
                            'action_key' => 'deepening_eclipse',
                            'name' => '月蝕深化',
                            'action_type' => 'self_buff',
                            'selection_weight' => 100,
                            'effect_percent' => 15,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 6,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 6,
                            'can_use_on_first_turn' => false,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
        'star_heaven_sage_balanced' => [
            'trial_key' => 'star_heaven_sage',
            'label' => '星天導師・標準候補',
            'hero_job_key' => 'star_heaven_sage',
            'required_job_key' => 'star_crown_sage',
            'required_job_name' => '星冠導師',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => false,
            'benchmark' => [
                'measured_on' => '2026-09-08',
                'runs' => 500,
                'passes' => 391,
                'pass_rate' => 78.2,
                'basis' => 'Lv255相当の魔法型標準プロファイル、開始HP/SP全快、保存・報酬なし',
                'note' => '固定シード20260909〜20261408。戦技・装備特攻・種族耐性・探索補助・ヴァルモン追撃なし。',
            ],
            'phases' => [
                [
                    'key' => 'celestial_core',
                    'trial_master_key' => 'asterion',
                    'label' => '天象核',
                    'image_path' => 'images/enemy/enemy_725.webp',
                    'type_name' => '魔法火力型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 58_000,
                    'str' => 2_600,
                    'def' => 4_300,
                    'agi' => 5_600,
                    'mag' => 9_800,
                    'spr' => 6_200,
                    'luk' => 4_700,
                    'actions' => [
                        [
                            'action_key' => 'celestial_analysis',
                            'name' => '天象解析',
                            'action_type' => 'magical_spr_down',
                            'selection_weight' => 100,
                            'power_percent' => 80,
                            'effect_percent' => 18,
                            'duration_turns' => 3,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'guarantee_first_use' => true,
                        ],
                        [
                            'action_key' => 'stellar_collapse',
                            'name' => '星天崩落',
                            'action_type' => 'magical',
                            'selection_weight' => 100,
                            'power_percent' => 180,
                            'cooldown_turns' => 5,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 4,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 4,
                            'can_use_on_first_turn' => false,
                            'is_telegraphed' => true,
                            'telegraph_turns' => 1,
                            'can_be_guarded' => true,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
        'time_reader_traveler_balanced' => [
            'trial_key' => 'time_reader_traveler',
            'label' => '時詠みの旅人・標準候補',
            'hero_job_key' => 'time_reader_traveler',
            'required_job_key' => 'gold_crown_alchemist',
            'required_job_name' => '金冠錬師',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => false,
            'benchmark' => [
                'measured_on' => '2026-09-08',
                'runs' => 800,
                'passes' => 434,
                'pass_rate' => 54.3,
                'basis' => '本番の全冠位職マスター済み匿名スナップショット8人（総合戦力27.0万〜52.3万）、開始HP/SP全快、保存・報酬なし',
                'note' => '固定100シード×8人。総合戦力30万は入場条件ではなく難易度目安。現行の装備・ボス用戦技を反映。',
            ],
            'phases' => [
                [
                    'key' => 'time_observer',
                    'trial_master_key' => 'aeon',
                    'label' => '時環相',
                    'image_path' => 'images/enemy/enemy_732.webp',
                    'type_name' => '魔法敏捷型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 80_000,
                    'str' => 2_400,
                    'def' => 5_800,
                    'agi' => 11_500,
                    'mag' => 9_600,
                    'spr' => 6_600,
                    'luk' => 6_200,
                    'actions' => [
                        [
                            'action_key' => 'time_bind',
                            'name' => '時縛り',
                            'action_type' => 'magical_slow',
                            'selection_weight' => 100,
                            'power_percent' => 75,
                            'effect_percent' => 30,
                            'duration_turns' => 2,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'guarantee_first_use' => true,
                        ],
                        [
                            'action_key' => 'clockwork_barrage',
                            'name' => '刻針連奏',
                            'action_type' => 'magical_multi_hit',
                            'selection_weight' => 100,
                            'power_percent' => 85,
                            'hit_count' => 2,
                            'cooldown_turns' => 2,
                        ],
                        [
                            'action_key' => 'aeon_acceleration',
                            'name' => '時環加速',
                            'action_type' => 'self_speed_buff',
                            'selection_weight' => 100,
                            'effect_percent' => 25,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 6,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 6,
                            'can_use_on_first_turn' => false,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
    ],
];
