<?php

return [
    'trial_masters' => [
        'aurora' => [
            'name' => '双極天騎アウローラ',
            'species_keys' => ['spirit', 'soldier'],
        ],
        'lunagrim' => [
            'name' => '月喰影獣ルナグリム',
            'species_keys' => ['beast', 'demon'],
        ],
        'asterion' => [
            'name' => '天象魔導核アステリオン',
            'species_keys' => ['mage', 'machine'],
        ],
        'azragion' => [
            'name' => '蒼穹古竜アズラギオン',
            'species_keys' => ['dragon', 'flying'],
        ],
        'seeker' => [
            'name' => '天機偵察機シーカー',
            'species_keys' => ['machine', 'flying'],
        ],
        'bastion' => [
            'name' => '天機重装機バスティオン',
            'species_keys' => ['machine', 'soldier'],
        ],
        'oracle' => [
            'name' => '天機演算核オラクル',
            'species_keys' => ['machine', 'mage'],
        ],
        'justia' => [
            'name' => '天秤聖獣ユスティア',
            'species_keys' => ['beast', 'spirit'],
        ],
        'necrodia' => [
            'name' => '魂葬王ネクロディア',
            'species_keys' => ['undead', 'mage'],
        ],
        'aeon' => [
            'name' => '時環の観測者エオン',
            'species_keys' => ['mage', 'spirit'],
        ],
        'tempesta' => [
            'name' => '雷嵐神獣テンペスタ',
            'species_keys' => ['beast', 'spirit'],
        ],
        'argeon' => [
            'name' => '白銀城塞アルジェオン',
            'species_keys' => ['machine', 'spirit'],
        ],
    ],
    'hall_cards' => [
        'dawn_hero' => [
            'label' => '暁の試練場',
            'symbol_image' => 'symbol/hero_trial_070.webp',
            'facility_desc' => '夜明けを告げる光が、静かに挑戦者を待っている。',
        ],
        'black_moon_executor' => [
            'label' => '月蝕の試練場',
            'symbol_image' => 'symbol/hero_trial_071.webp',
            'facility_desc' => '欠けた月の影が、音もなく殿内へ伸びている。',
        ],
        'star_heaven_sage' => [
            'label' => '星天の試練場',
            'symbol_image' => 'symbol/hero_trial_072.webp',
            'facility_desc' => '遥かな星々の光が、一つの扉へ集まっている。',
        ],
        'azure_dragon_warrior_king' => [
            'label' => '蒼竜の試練場',
            'symbol_image' => 'symbol/hero_trial_073.webp',
            'facility_desc' => '蒼穹の彼方から、天地を揺らす気配が響く。',
        ],
        'heavenly_machina_chancellor' => [
            'label' => '天機の試練場',
            'symbol_image' => 'symbol/hero_trial_074.webp',
            'facility_desc' => '閉ざされた機構が、訪れる者を測るように脈動する。',
        ],
        'sanctuary_judge' => [
            'label' => '聖域の試練場',
            'symbol_image' => 'symbol/hero_trial_075.webp',
            'facility_desc' => '穢れなき静寂の奥で、厳かな光が揺れている。',
        ],
        'phantom_funeral_demon_king' => [
            'label' => '幻葬の試練場',
            'symbol_image' => 'symbol/hero_trial_076.webp',
            'facility_desc' => '遠い鐘の音とともに、淡い魂火が漂っている。',
        ],
        'time_reader_traveler' => [
            'label' => '時環の試練場',
            'symbol_image' => 'symbol/hero_trial_077.webp',
            'facility_desc' => '止まったはずの刻が、扉の向こうで巡り続ける。',
        ],
        'storm_overlord' => [
            'label' => '荒天の試練場',
            'symbol_image' => 'symbol/hero_trial_078.webp',
            'facility_desc' => '黒雲の奥で雷光が走り、殿堂の空気を震わせる。',
        ],
        'silver_guardian_king' => [
            'label' => '白銀の試練場',
            'symbol_image' => 'symbol/hero_trial_079.webp',
            'facility_desc' => '白銀に輝く門が、微動だにせず行く手を阻んでいる。',
        ],
    ],
    'released_trials' => [
        'dawn_hero' => [
            'label' => '暁の試練場',
            'profile_key' => 'dawn_hero_balanced',
            'area_id' => 84,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'dawn_hero',
            'hero_job_name' => '暁の勇者',
            'required_job_key' => 'crown_sword_knight',
            'required_job_name' => '剣冠騎士',
            'symbol_image' => 'symbol/hero_trial_070.webp',
            'job_badge_image' => 'jobbadge/jobbadge_070.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '二形態連続戦闘',
            'facility_desc' => '光と剣、二つの相が挑戦者を待つ。',
            'cleared_desc' => '二つの相を越えた者に、暁の道が開かれる。',
            'challenge_action' => '二形態試練に挑む',
            'mechanic_details' => [
                '剣相から術相へHP/SPを引き継いで連戦',
                '両形態撃破で暁の勇者解放',
            ],
            'victory_title' => '双極天騎アウローラの二つの相を打ち破った！',
            'retry_message' => '宿屋でHP/SPを整えれば、暁の試練場から再挑戦できる。',
        ],
        'black_moon_executor' => [
            'label' => '月蝕の試練場',
            'profile_key' => 'black_moon_executor_balanced',
            'area_id' => 85,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'black_moon_executor',
            'hero_job_name' => '黒月の執行者',
            'required_job_key' => 'shadow_crown_hunter',
            'required_job_name' => '影冠狩人',
            'symbol_image' => 'symbol/hero_trial_071.webp',
            'job_badge_image' => 'jobbadge/jobbadge_071.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '月影二獣連続戦',
            'facility_desc' => '月影を渡る獣が、挑戦者の一瞬の隙を狙っている。',
            'cleared_desc' => '月影を捉えた者に、黒月の道が開かれる。',
            'challenge_action' => '月蝕の試練に挑む',
            'mechanic_details' => [
                '月影の分身から本体へHP/SPを引き継いで連戦',
                '分身は敏捷を奪い、本体は月蝕深化から連撃を仕掛ける',
                '二体を撃破すると黒月の執行者解放',
            ],
            'victory_title' => '月喰影獣ルナグリムの月影を捉えた！',
            'retry_message' => '宿屋でHP/SPを整えれば、月蝕の試練場から再挑戦できる。',
        ],
        'star_heaven_sage' => [
            'label' => '星天の試練場',
            'profile_key' => 'star_heaven_sage_balanced',
            'area_id' => 86,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'star_heaven_sage',
            'hero_job_name' => '星天導師',
            'required_job_key' => 'star_crown_sage',
            'required_job_name' => '星冠導師',
            'symbol_image' => 'symbol/hero_trial_072.webp',
            'job_badge_image' => 'jobbadge/jobbadge_072.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '星殻・天象核連続戦',
            'facility_desc' => '星図を巡る魔導核が、挑戦者の精神を見定めている。',
            'cleared_desc' => '星々の導きを掴んだ者に、星天の道が開かれる。',
            'challenge_action' => '星天の試練に挑む',
            'mechanic_details' => [
                '星殻相から天象核相へHP/SPを引き継いで連戦',
                '星殻は精神を崩し、露出した核は予兆を伴う大魔法を放つ',
                '二つの相を撃破すると星天導師解放',
            ],
            'victory_title' => '天象魔導核アステリオンの星図を打ち破った！',
            'retry_message' => '宿屋でHP/SPを整えれば、星天の試練場から再挑戦できる。',
        ],
        'time_reader_traveler' => [
            'label' => '時環の試練場',
            'profile_key' => 'time_reader_traveler_balanced',
            'area_id' => 87,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'time_reader_traveler',
            'hero_job_name' => '時詠みの旅人',
            'required_job_key' => 'gold_crown_alchemist',
            'required_job_name' => '金冠錬師',
            'symbol_image' => 'symbol/hero_trial_077.webp',
            'job_badge_image' => 'jobbadge/jobbadge_077.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '時環高速魔導戦',
            'facility_desc' => '巡る刻の観測者が、挑戦者の一瞬先を見つめている。',
            'cleared_desc' => '時の流れを越えた者に、時詠みの道が開かれる。',
            'challenge_action' => '時環の試練に挑む',
            'mechanic_details' => [
                '敏捷を奪う魔法と連続魔法で行動の主導権を握る',
                '長期戦では加速し、さらに先手を取りやすくなる',
                'エオン撃破で時詠みの旅人解放',
            ],
            'victory_title' => '時環の観測者エオンの刻を越えた！',
            'retry_message' => '宿屋でHP/SPを整えれば、時環の試練場から再挑戦できる。',
        ],
    ],
    'profiles' => [
        'dawn_hero_balanced' => [
            'trial_key' => 'dawn_hero',
            'label' => '暁の勇者・標準候補',
            'hero_job_key' => 'dawn_hero',
            'required_job_key' => 'crown_sword_knight',
            'required_job_name' => '剣冠騎士',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => true,
            'benchmark' => [
                'measured_on' => '2026-09-09',
                'runs' => 850,
                'passes' => 430,
                'pass_rate' => 50.6,
                'basis' => '本番の全冠位職マスター済み匿名スナップショット17人、開始HP/SP全快、装備・戦技・種族相性を保持、保存・報酬なし',
                'note' => '固定50シード×17人。35万未満32.7%、35万以上83.3%。全構成を35万へ等比補正した比較は60.5%。',
            ],
            'phases' => [
                [
                    'key' => 'sword_form',
                    'trial_master_key' => 'aurora',
                    'label' => '第1形態・剣相',
                    'image_path' => 'images/enemy/enemy_723.webp',
                    'type_name' => '物理型',
                    'max_hp' => 85_750,
                    'str' => 8_283,
                    'def' => 6_417,
                    'agi' => 5_833,
                    'mag' => 3_675,
                    'spr' => 5_542,
                    'luk' => 5_250,
                ],
                [
                    'key' => 'spell_form',
                    'trial_master_key' => 'aurora',
                    'label' => '第2形態・術相',
                    'image_path' => 'images/enemy/enemy_735.webp',
                    'type_name' => '魔法型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 85_750,
                    'str' => 3_675,
                    'def' => 5_542,
                    'agi' => 5_833,
                    'mag' => 8_867,
                    'spr' => 7_058,
                    'luk' => 5_250,
                    'transition_title' => '双極天騎アウローラを倒した！',
                    'transition_body' => 'が、その姿が変わっていく……！！',
                ],
            ],
        ],
        'black_moon_executor_balanced' => [
            'trial_key' => 'black_moon_executor',
            'label' => '黒月の執行者・標準候補',
            'hero_job_key' => 'black_moon_executor',
            'required_job_key' => 'shadow_crown_hunter',
            'required_job_name' => '影冠狩人',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => true,
            'benchmark' => [
                'measured_on' => '2026-09-10',
                'runs' => 500,
                'passes' => 344,
                'pass_rate' => 68.8,
                'basis' => 'ローカル「かんりにん」の装備・戦技・種族相性を保持し、能力を戦闘力350,003へ等比補正、固定500シード、開始HP/SP全快、保存・報酬なし',
                'note' => '同じ構成の実戦力252,271では1.4%。本番匿名17構成による二体連続戦の再測定は未実施。',
            ],
            'phases' => [
                [
                    'key' => 'moon_shadow_avatar',
                    'trial_master_key' => 'lunagrim',
                    'enemy_name' => '月喰影獣ルナグリムの影身',
                    'label' => '第一戦・月影身',
                    'image_path' => 'images/enemy/enemy_736.webp',
                    'type_name' => '月影攪乱型',
                    'max_hp' => 38_000,
                    'str' => 8_700,
                    'def' => 4_800,
                    'agi' => 11_500,
                    'mag' => 3_800,
                    'spr' => 5_000,
                    'luk' => 8_500,
                    'actions' => [
                        [
                            'action_key' => 'moon_shadow_bind',
                            'name' => '月影縛り',
                            'action_type' => 'slow',
                            'selection_weight' => 100,
                            'power_percent' => 80,
                            'effect_percent' => 20,
                            'duration_turns' => 2,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'guarantee_first_use' => true,
                        ],
                        [
                            'action_key' => 'shadow_fang_dance',
                            'name' => '影牙連舞',
                            'action_type' => 'multi_hit',
                            'selection_weight' => 100,
                            'power_percent' => 65,
                            'hit_count' => 2,
                            'cooldown_turns' => 2,
                        ],
                    ],
                ],
                [
                    'key' => 'lunar_eclipse_true_body',
                    'trial_master_key' => 'lunagrim',
                    'label' => '第二戦・月喰本体',
                    'image_path' => 'images/enemy/enemy_724.webp',
                    'type_name' => '月蝕連撃型',
                    'max_hp' => 60_000,
                    'str' => 10_033,
                    'def' => 5_367,
                    'agi' => 10_383,
                    'mag' => 4_317,
                    'spr' => 5_600,
                    'luk' => 7_933,
                    'transition_title' => '月喰影獣ルナグリムの影身を退けた！',
                    'transition_body' => 'だが、月影の奥から真のルナグリムが牙を剥く……！！',
                    'actions' => [
                        [
                            'action_key' => 'eclipse_fang_dance',
                            'name' => '蝕牙連舞',
                            'action_type' => 'multi_hit',
                            'selection_weight' => 100,
                            'power_percent' => 80,
                            'hit_count' => 2,
                            'cooldown_turns' => 2,
                        ],
                        [
                            'action_key' => 'deepening_eclipse',
                            'name' => '月蝕深化',
                            'action_type' => 'self_buff',
                            'selection_weight' => 100,
                            'effect_percent' => 15,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 1,
                            'can_use_on_first_turn' => true,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
        'star_heaven_sage_balanced' => [
            'trial_key' => 'star_heaven_sage',
            'label' => '星天導師・標準候補',
            'hero_job_key' => 'star_heaven_sage',
            'required_job_key' => 'star_crown_sage',
            'required_job_name' => '星冠導師',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => true,
            'benchmark' => [
                'measured_on' => '2026-09-10',
                'runs' => 500,
                'passes' => 312,
                'pass_rate' => 62.4,
                'basis' => 'ローカル「かんりにん」の装備・戦技・種族相性を保持し、能力を戦闘力350,003へ等比補正、固定500シード、開始HP/SP全快、保存・報酬なし',
                'note' => '同じ構成の実戦力252,271では0%。本番匿名17構成による二形態連続戦の再測定は未実施。',
            ],
            'phases' => [
                [
                    'key' => 'celestial_shell',
                    'trial_master_key' => 'asterion',
                    'enemy_name' => '天象魔導核アステリオン・星殻',
                    'label' => '第一形態・星殻相',
                    'image_path' => 'images/enemy/enemy_737.webp',
                    'type_name' => '星殻解析型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 45_000,
                    'str' => 4_000,
                    'def' => 8_500,
                    'agi' => 7_800,
                    'mag' => 12_000,
                    'spr' => 11_000,
                    'luk' => 6_500,
                    'actions' => [
                        [
                            'action_key' => 'celestial_analysis',
                            'name' => '天象解析',
                            'action_type' => 'magical_spr_down',
                            'selection_weight' => 100,
                            'power_percent' => 80,
                            'effect_percent' => 18,
                            'duration_turns' => 3,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
                [
                    'key' => 'celestial_core',
                    'trial_master_key' => 'asterion',
                    'label' => '第二形態・天象核相',
                    'image_path' => 'images/enemy/enemy_725.webp',
                    'type_name' => '崩星魔導型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 80_000,
                    'str' => 4_900,
                    'def' => 6_500,
                    'agi' => 8_500,
                    'mag' => 16_500,
                    'spr' => 8_000,
                    'luk' => 6_883,
                    'transition_title' => 'アステリオンの星殻を砕いた！',
                    'transition_body' => '露出した天象核が、星々の魔力を一点へ収束させる……！！',
                    'actions' => [
                        [
                            'action_key' => 'astral_volley',
                            'name' => '星雨連弾',
                            'action_type' => 'magical_multi_hit',
                            'selection_weight' => 100,
                            'power_percent' => 70,
                            'hit_count' => 2,
                            'cooldown_turns' => 2,
                        ],
                        [
                            'action_key' => 'stellar_collapse',
                            'name' => '星天崩落',
                            'action_type' => 'magical',
                            'selection_weight' => 100,
                            'power_percent' => 180,
                            'cooldown_turns' => 5,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 2,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 2,
                            'can_use_on_first_turn' => false,
                            'is_telegraphed' => true,
                            'telegraph_turns' => 1,
                            'can_be_guarded' => true,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
        'time_reader_traveler_balanced' => [
            'trial_key' => 'time_reader_traveler',
            'label' => '時詠みの旅人・標準候補',
            'hero_job_key' => 'time_reader_traveler',
            'required_job_key' => 'gold_crown_alchemist',
            'required_job_name' => '金冠錬師',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => false,
            'benchmark' => [
                'measured_on' => '2026-09-09',
                'runs' => 850,
                'passes' => 325,
                'pass_rate' => 38.2,
                'basis' => '本番の全冠位職マスター済み匿名スナップショット17人、開始HP/SP全快、装備・戦技・種族相性を保持、保存・報酬なし',
                'note' => '固定50シード×17人。35万未満16.0%、35万以上79.0%。全構成を35万へ等比補正した比較は40.6%。',
            ],
            'phases' => [
                [
                    'key' => 'time_observer',
                    'trial_master_key' => 'aeon',
                    'label' => '時環相',
                    'image_path' => 'images/enemy/enemy_732.webp',
                    'type_name' => '魔法敏捷型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 149_333,
                    'str' => 3_617,
                    'def' => 8_167,
                    'agi' => 14_758,
                    'mag' => 14_583,
                    'spr' => 9_217,
                    'luk' => 7_933,
                    'actions' => [
                        [
                            'action_key' => 'time_bind',
                            'name' => '時縛り',
                            'action_type' => 'magical_slow',
                            'selection_weight' => 100,
                            'power_percent' => 75,
                            'effect_percent' => 30,
                            'duration_turns' => 2,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'guarantee_first_use' => true,
                        ],
                        [
                            'action_key' => 'clockwork_barrage',
                            'name' => '刻針連奏',
                            'action_type' => 'magical_multi_hit',
                            'selection_weight' => 100,
                            'power_percent' => 85,
                            'hit_count' => 2,
                            'cooldown_turns' => 2,
                        ],
                        [
                            'action_key' => 'aeon_acceleration',
                            'name' => '時環加速',
                            'action_type' => 'self_speed_buff',
                            'selection_weight' => 100,
                            'effect_percent' => 25,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 6,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 6,
                            'can_use_on_first_turn' => false,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
    ],
];
