<?php

return [
    'trial_masters' => [
        'aurora' => [
            'name' => '双極天騎アウローラ',
            'species_keys' => ['spirit', 'soldier'],
        ],
        'lunagrim' => [
            'name' => '月喰影獣ルナグリム',
            'species_keys' => ['beast', 'demon'],
        ],
        'asterion' => [
            'name' => '天象魔導核アステリオン',
            'species_keys' => ['mage', 'machine'],
        ],
        'azragion' => [
            'name' => '蒼穹古竜アズラギオン',
            'species_keys' => ['dragon', 'flying'],
        ],
        'seeker' => [
            'name' => '天機偵察機シーカー',
            'species_keys' => ['machine', 'flying'],
        ],
        'bastion' => [
            'name' => '天機重装機バスティオン',
            'species_keys' => ['machine', 'soldier'],
        ],
        'oracle' => [
            'name' => '天機演算核オラクル',
            'species_keys' => ['machine', 'mage'],
        ],
        'justia' => [
            'name' => '天秤聖獣ユスティア',
            'species_keys' => ['beast', 'spirit'],
        ],
        'necrodia' => [
            'name' => '魂葬王ネクロディア',
            'species_keys' => ['undead', 'mage'],
        ],
        'aeon' => [
            'name' => '時環の観測者エオン',
            'species_keys' => ['mage', 'spirit'],
        ],
        'tempesta' => [
            'name' => '雷嵐神獣テンペスタ',
            'species_keys' => ['beast', 'spirit'],
        ],
        'argeon' => [
            'name' => '白銀城塞アルジェオン',
            'species_keys' => ['machine', 'spirit'],
        ],
    ],
    'hall_tiers' => [
        'first_wave' => [
            'recommended_power' => 350_000,
            'is_planned' => false,
            'trial_keys' => [
                'dawn_hero',
                'black_moon_executor',
                'star_heaven_sage',
                'time_reader_traveler',
            ],
        ],
        'second_wave' => [
            'recommended_power' => 400_000,
            'is_planned' => false,
            'trial_keys' => [
                'heavenly_machina_chancellor',
                'sanctuary_judge',
                'storm_overlord',
                'silver_guardian_king',
            ],
        ],
        'final_wave' => [
            'recommended_power' => 450_000,
            'is_planned' => false,
            'trial_keys' => [
                'azure_dragon_warrior_king',
                'phantom_funeral_demon_king',
            ],
        ],
    ],
    'hall_cards' => [
        'dawn_hero' => [
            'label' => '暁の試練場',
            'symbol_image' => 'symbol/hero_trial_070.webp',
            'facility_desc' => '夜明けを告げる光が、静かに挑戦者を待っている。',
        ],
        'black_moon_executor' => [
            'label' => '月蝕の試練場',
            'symbol_image' => 'symbol/hero_trial_071.webp',
            'facility_desc' => '欠けた月の影が、音もなく殿内へ伸びている。',
        ],
        'star_heaven_sage' => [
            'label' => '星天の試練場',
            'symbol_image' => 'symbol/hero_trial_072.webp',
            'facility_desc' => '遥かな星々の光が、一つの扉へ集まっている。',
        ],
        'time_reader_traveler' => [
            'label' => '時環の試練場',
            'symbol_image' => 'symbol/hero_trial_077.webp',
            'facility_desc' => '止まったはずの刻が、扉の向こうで巡り続ける。',
        ],
        'heavenly_machina_chancellor' => [
            'label' => '天機の試練場',
            'symbol_image' => 'symbol/hero_trial_074.webp',
            'facility_desc' => '閉ざされた機構が、訪れる者を測るように脈動する。',
        ],
        'sanctuary_judge' => [
            'label' => '聖域の試練場',
            'symbol_image' => 'symbol/hero_trial_075.webp',
            'facility_desc' => '穢れなき静寂の奥で、厳かな光が揺れている。',
        ],
        'storm_overlord' => [
            'label' => '荒天の試練場',
            'symbol_image' => 'symbol/hero_trial_078.webp',
            'facility_desc' => '黒雲の奥で雷光が走り、殿堂の空気を震わせる。',
        ],
        'silver_guardian_king' => [
            'label' => '白銀の試練場',
            'symbol_image' => 'symbol/hero_trial_079.webp',
            'facility_desc' => '白銀に輝く門が、微動だにせず行く手を阻んでいる。',
        ],
        'azure_dragon_warrior_king' => [
            'label' => '蒼竜の試練場',
            'symbol_image' => 'symbol/hero_trial_073.webp',
            'facility_desc' => '蒼穹の彼方から、天地を揺らす気配が響く。',
        ],
        'phantom_funeral_demon_king' => [
            'label' => '幻葬の試練場',
            'symbol_image' => 'symbol/hero_trial_076.webp',
            'facility_desc' => '遠い鐘の音とともに、淡い魂火が漂っている。',
        ],
    ],
    'released_trials' => [
        'dawn_hero' => [
            'label' => '暁の試練場',
            'profile_key' => 'dawn_hero_balanced',
            'area_id' => 84,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'dawn_hero',
            'hero_job_name' => '暁の勇者',
            'required_job_key' => 'crown_sword_knight',
            'required_job_name' => '剣冠騎士',
            'symbol_image' => 'symbol/hero_trial_070.webp',
            'job_badge_image' => 'jobbadge/jobbadge_070.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '二形態連続戦闘',
            'facility_desc' => '光と剣、二つの相が挑戦者を待つ。',
            'cleared_desc' => '二つの相を越えた者に、暁の道が開かれる。',
            'challenge_action' => '二形態試練に挑む',
            'mechanic_details' => [
                '剣相から術相へHP/SPを引き継いで連戦',
                '両形態撃破で暁の勇者解放',
            ],
            'victory_title' => '双極天騎アウローラの二つの相を打ち破った！',
            'retry_message' => '宿屋でHP/SPを整えれば、暁の試練場から再挑戦できる。',
        ],
        'black_moon_executor' => [
            'label' => '月蝕の試練場',
            'profile_key' => 'black_moon_executor_balanced',
            'area_id' => 85,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'black_moon_executor',
            'hero_job_name' => '黒月の執行者',
            'required_job_key' => 'shadow_crown_hunter',
            'required_job_name' => '影冠狩人',
            'symbol_image' => 'symbol/hero_trial_071.webp',
            'job_badge_image' => 'jobbadge/jobbadge_071.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '月影二獣連続戦',
            'facility_desc' => '月影を渡る獣が、挑戦者の一瞬の隙を狙っている。',
            'cleared_desc' => '月影を捉えた者に、黒月の道が開かれる。',
            'challenge_action' => '月蝕の試練に挑む',
            'mechanic_details' => [
                '月影の分身から本体へHP/SPを引き継いで連戦',
                '分身は敏捷を奪い、本体は月蝕深化から連撃を仕掛ける',
                '二体を撃破すると黒月の執行者解放',
            ],
            'victory_title' => '月喰影獣ルナグリムの月影を捉えた！',
            'retry_message' => '宿屋でHP/SPを整えれば、月蝕の試練場から再挑戦できる。',
        ],
        'star_heaven_sage' => [
            'label' => '星天の試練場',
            'profile_key' => 'star_heaven_sage_balanced',
            'area_id' => 86,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'star_heaven_sage',
            'hero_job_name' => '星天導師',
            'required_job_key' => 'star_crown_sage',
            'required_job_name' => '星冠導師',
            'symbol_image' => 'symbol/hero_trial_072.webp',
            'job_badge_image' => 'jobbadge/jobbadge_072.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '星殻・天象核連続戦',
            'facility_desc' => '星図を巡る魔導核が、挑戦者の精神を見定めている。',
            'cleared_desc' => '星々の導きを掴んだ者に、星天の道が開かれる。',
            'challenge_action' => '星天の試練に挑む',
            'mechanic_details' => [
                '星殻相から天象核相へHP/SPを引き継いで連戦',
                '星殻は精神を崩し、露出した核は予兆を伴う大魔法を放つ',
                '二つの相を撃破すると星天導師解放',
            ],
            'victory_title' => '天象魔導核アステリオンの星図を打ち破った！',
            'retry_message' => '宿屋でHP/SPを整えれば、星天の試練場から再挑戦できる。',
        ],
        'time_reader_traveler' => [
            'label' => '時環の試練場',
            'profile_key' => 'time_reader_traveler_balanced',
            'area_id' => 87,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'time_reader_traveler',
            'hero_job_name' => '時詠みの旅人',
            'required_job_key' => 'gold_crown_alchemist',
            'required_job_name' => '金冠錬師',
            'symbol_image' => 'symbol/hero_trial_077.webp',
            'job_badge_image' => 'jobbadge/jobbadge_077.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '時環高速魔導戦',
            'facility_desc' => '巡る刻の観測者が、挑戦者の一瞬先を見つめている。',
            'cleared_desc' => '時の流れを越えた者に、時詠みの道が開かれる。',
            'challenge_action' => '時環の試練に挑む',
            'mechanic_details' => [
                '敏捷を奪う魔法と連続魔法で行動の主導権を握る',
                '長期戦では加速し、さらに先手を取りやすくなる',
                'エオン撃破で時詠みの旅人解放',
            ],
            'victory_title' => '時環の観測者エオンの刻を越えた！',
            'retry_message' => '宿屋でHP/SPを整えれば、時環の試練場から再挑戦できる。',
        ],
        'heavenly_machina_chancellor' => [
            'label' => '天機の試練場',
            'profile_key' => 'heavenly_machina_chancellor_balanced',
            'release_gate' => 'hero_trials_second_wave',
            'area_id' => 88,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'heavenly_machina_chancellor',
            'hero_job_name' => '天機宰相',
            'required_job_key' => 'steel_crown_machina_sage',
            'required_job_name' => '鋼冠機導師',
            'symbol_image' => 'symbol/hero_trial_074.webp',
            'job_badge_image' => 'jobbadge/jobbadge_074.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '天機三段攻略戦',
            'facility_desc' => '偵察・重装・演算の三機構が、挑戦者の対応力を測る。',
            'cleared_desc' => '三つの機構を読み解いた者に、天機の道が開かれる。',
            'challenge_action' => '天機の試練に挑む',
            'mechanic_details' => [
                '偵察機・重装機・演算核へHP/SPを引き継いで連戦',
                '天機三機をすべて撃破すると天機宰相解放',
            ],
            'victory_title' => '天機三機の演算をすべて覆した！',
            'retry_message' => '宿屋でHP/SPを整えれば、天機の試練場から再挑戦できる。',
        ],
        'sanctuary_judge' => [
            'label' => '聖域の試練場',
            'profile_key' => 'sanctuary_judge_balanced',
            'release_gate' => 'hero_trials_second_wave',
            'area_id' => 89,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'sanctuary_judge',
            'hero_job_name' => '聖域の審判者',
            'required_job_key' => 'holy_crown_guardian',
            'required_job_name' => '聖冠守護者',
            'symbol_image' => 'symbol/hero_trial_075.webp',
            'job_badge_image' => 'jobbadge/jobbadge_075.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '聖域審判戦',
            'facility_desc' => '天秤を戴く聖獣が、護りと浄化の力を問いかける。',
            'cleared_desc' => '聖なる審判を越えた者に、聖域の道が開かれる。',
            'challenge_action' => '聖域の試練に挑む',
            'mechanic_details' => [
                '精神低下と回復阻害を受けながら、審判の大魔法を耐え抜く',
                'ユスティア撃破で聖域の審判者解放',
            ],
            'victory_title' => '天秤聖獣ユスティアの審判を越えた！',
            'retry_message' => '宿屋でHP/SPを整えれば、聖域の試練場から再挑戦できる。',
        ],
        'storm_overlord' => [
            'label' => '荒天の試練場',
            'profile_key' => 'storm_overlord_balanced',
            'release_gate' => 'hero_trials_second_wave',
            'area_id' => 90,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'storm_overlord',
            'hero_job_name' => '荒天の覇者',
            'required_job_key' => 'thunder_crown_fist_saint',
            'required_job_name' => '雷冠拳聖',
            'symbol_image' => 'symbol/hero_trial_078.webp',
            'job_badge_image' => 'jobbadge/jobbadge_078.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '荒天高速決戦',
            'facility_desc' => '雷嵐を纏う神獣が、息つく間もない猛攻を仕掛ける。',
            'cleared_desc' => '雷嵐を打ち砕いた者に、荒天の道が開かれる。',
            'challenge_action' => '荒天の試練に挑む',
            'mechanic_details' => [
                '高い敏捷から連撃と急所攻撃を繰り出す',
                '長期戦では攻撃と魔力を高め、猛攻を加速させる',
                'テンペスタ撃破で荒天の覇者解放',
            ],
            'victory_title' => '雷嵐神獣テンペスタの猛攻を制した！',
            'retry_message' => '宿屋でHP/SPを整えれば、荒天の試練場から再挑戦できる。',
        ],
        'silver_guardian_king' => [
            'label' => '白銀の試練場',
            'profile_key' => 'silver_guardian_king_balanced',
            'release_gate' => 'hero_trials_second_wave',
            'area_id' => 91,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'silver_guardian_king',
            'hero_job_name' => '白銀の守護王',
            'required_job_key' => 'war_crown_commander',
            'required_job_name' => '戦冠司令',
            'symbol_image' => 'symbol/hero_trial_079.webp',
            'job_badge_image' => 'jobbadge/jobbadge_079.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '白銀城塞攻略戦',
            'facility_desc' => '白銀の城塞が、あらゆる攻めを受け止めてなお立ちはだかる。',
            'cleared_desc' => '不落の城塞を崩した者に、白銀の道が開かれる。',
            'challenge_action' => '白銀の試練に挑む',
            'mechanic_details' => [
                '高い防御と精神を持つ城塞を、制限ターン内に攻略する',
                '防御を貫く反撃と予兆突撃を耐えながら攻め切る',
                'アルジェオン撃破で白銀の守護王解放',
            ],
            'victory_title' => '白銀城塞アルジェオンを陥落させた！',
            'retry_message' => '宿屋でHP/SPを整えれば、白銀の試練場から再挑戦できる。',
        ],
        'azure_dragon_warrior_king' => [
            'label' => '蒼竜の試練場',
            'profile_key' => 'azure_dragon_warrior_king_candidate',
            'release_gate' => 'hero_trials_final_wave',
            'area_id' => 92,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'azure_dragon_warrior_king',
            'hero_job_name' => '蒼竜武王',
            'required_job_key' => 'dragon_crown_lance_general',
            'required_job_name' => '竜冠槍将',
            'symbol_image' => 'symbol/hero_trial_073.webp',
            'job_badge_image' => 'jobbadge/jobbadge_073.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '蒼穹古竜決戦',
            'facility_desc' => '蒼穹を統べる古竜が、挑戦者の武を見定めている。',
            'cleared_desc' => '古竜の猛攻を越えた者に、蒼竜の道が開かれる。',
            'challenge_action' => '蒼竜の試練に挑む',
            'mechanic_details' => ['連続物理攻撃と防御貫通を使う古竜との決戦', '予兆を伴う竜王撃を越え、アズラギオン撃破で蒼竜武王解放'],
            'victory_title' => '蒼穹古竜アズラギオンの武を越えた！',
            'retry_message' => '宿屋でHP/SPを整えれば、蒼竜の試練場から再挑戦できる。',
        ],
        'phantom_funeral_demon_king' => [
            'label' => '幻葬の試練場',
            'profile_key' => 'phantom_funeral_demon_king_candidate',
            'release_gate' => 'hero_trials_final_wave',
            'area_id' => 93,
            'city_id' => 10,
            'appearance_required_area_id' => 70,
            'hero_job_key' => 'phantom_funeral_demon_king',
            'hero_job_name' => '幻葬の魔王',
            'required_job_key' => 'black_crown_magic_knight',
            'required_job_name' => '黒冠魔騎士',
            'symbol_image' => 'symbol/hero_trial_076.webp',
            'job_badge_image' => 'jobbadge/jobbadge_076.webp',
            'requires_full_hp_sp' => true,
            'battle_heading' => '魂葬王決戦',
            'facility_desc' => '漂う魂火の奥で、魂葬王が静かに待っている。',
            'cleared_desc' => '魂葬の終鐘を越えた者に、幻葬の道が開かれる。',
            'challenge_action' => '幻葬の試練に挑む',
            'mechanic_details' => ['精神を崩す魔法と、与えた実ダメージからHPを取り戻す吸収魔法', '予兆を伴う終鐘を越え、ネクロディア撃破で幻葬の魔王解放'],
            'victory_title' => '魂葬王ネクロディアの終鐘を越えた！',
            'retry_message' => '宿屋でHP/SPを整えれば、幻葬の試練場から再挑戦できる。',
        ],
    ],
    'profiles' => [
        'dawn_hero_balanced' => [
            'trial_key' => 'dawn_hero',
            'label' => '暁の勇者・標準候補',
            'hero_job_key' => 'dawn_hero',
            'required_job_key' => 'crown_sword_knight',
            'required_job_name' => '剣冠騎士',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => true,
            'benchmark' => [
                'measured_on' => '2026-09-09',
                'runs' => 850,
                'passes' => 430,
                'pass_rate' => 50.6,
                'basis' => '本番の全冠位職マスター済み匿名スナップショット17人、開始HP/SP全快、装備・戦技・種族相性を保持、保存・報酬なし',
                'note' => '固定50シード×17人。35万未満32.7%、35万以上83.3%。全構成を35万へ等比補正した比較は60.5%。',
            ],
            'phases' => [
                [
                    'key' => 'sword_form',
                    'trial_master_key' => 'aurora',
                    'label' => '第1形態・剣相',
                    'image_path' => 'images/enemy/enemy_723.webp',
                    'type_name' => '物理型',
                    'max_hp' => 85_750,
                    'str' => 8_283,
                    'def' => 6_417,
                    'agi' => 5_833,
                    'mag' => 3_675,
                    'spr' => 5_542,
                    'luk' => 5_250,
                ],
                [
                    'key' => 'spell_form',
                    'trial_master_key' => 'aurora',
                    'label' => '第2形態・術相',
                    'image_path' => 'images/enemy/enemy_735.webp',
                    'type_name' => '魔法型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 85_750,
                    'str' => 3_675,
                    'def' => 5_542,
                    'agi' => 5_833,
                    'mag' => 8_867,
                    'spr' => 7_058,
                    'luk' => 5_250,
                    'transition_title' => '双極天騎アウローラを倒した！',
                    'transition_body' => 'が、その姿が変わっていく……！！',
                ],
            ],
        ],
        'black_moon_executor_balanced' => [
            'trial_key' => 'black_moon_executor',
            'label' => '黒月の執行者・標準候補',
            'hero_job_key' => 'black_moon_executor',
            'required_job_key' => 'shadow_crown_hunter',
            'required_job_name' => '影冠狩人',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => true,
            'benchmark' => [
                'measured_on' => '2026-09-10',
                'runs' => 500,
                'passes' => 344,
                'pass_rate' => 68.8,
                'basis' => 'ローカル「かんりにん」の装備・戦技・種族相性を保持し、能力を戦闘力350,003へ等比補正、固定500シード、開始HP/SP全快、保存・報酬なし',
                'note' => '同じ構成の実戦力252,271では1.4%。本番匿名17構成による二体連続戦の再測定は未実施。',
            ],
            'phases' => [
                [
                    'key' => 'moon_shadow_avatar',
                    'trial_master_key' => 'lunagrim',
                    'enemy_name' => '月喰影獣ルナグリムの影身',
                    'label' => '第一戦・月影身',
                    'image_path' => 'images/enemy/enemy_736.webp',
                    'type_name' => '月影攪乱型',
                    'max_hp' => 38_000,
                    'str' => 8_700,
                    'def' => 4_800,
                    'agi' => 11_500,
                    'mag' => 3_800,
                    'spr' => 5_000,
                    'luk' => 8_500,
                    'actions' => [
                        [
                            'action_key' => 'moon_shadow_bind',
                            'name' => '月影縛り',
                            'action_type' => 'slow',
                            'selection_weight' => 100,
                            'power_percent' => 80,
                            'effect_percent' => 20,
                            'duration_turns' => 2,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'guarantee_first_use' => true,
                        ],
                        [
                            'action_key' => 'shadow_fang_dance',
                            'name' => '影牙連舞',
                            'action_type' => 'multi_hit',
                            'selection_weight' => 100,
                            'power_percent' => 65,
                            'hit_count' => 2,
                            'cooldown_turns' => 2,
                        ],
                    ],
                ],
                [
                    'key' => 'lunar_eclipse_true_body',
                    'trial_master_key' => 'lunagrim',
                    'label' => '第二戦・月喰本体',
                    'image_path' => 'images/enemy/enemy_724.webp',
                    'type_name' => '月蝕連撃型',
                    'max_hp' => 60_000,
                    'str' => 10_033,
                    'def' => 5_367,
                    'agi' => 10_383,
                    'mag' => 4_317,
                    'spr' => 5_600,
                    'luk' => 7_933,
                    'transition_title' => '月喰影獣ルナグリムの影身を退けた！',
                    'transition_body' => 'だが、月影の奥から真のルナグリムが牙を剥く……！！',
                    'actions' => [
                        [
                            'action_key' => 'eclipse_fang_dance',
                            'name' => '蝕牙連舞',
                            'action_type' => 'multi_hit',
                            'selection_weight' => 100,
                            'power_percent' => 80,
                            'hit_count' => 2,
                            'cooldown_turns' => 2,
                        ],
                        [
                            'action_key' => 'deepening_eclipse',
                            'name' => '月蝕深化',
                            'action_type' => 'self_buff',
                            'selection_weight' => 100,
                            'effect_percent' => 15,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 1,
                            'can_use_on_first_turn' => true,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
        'star_heaven_sage_balanced' => [
            'trial_key' => 'star_heaven_sage',
            'label' => '星天導師・標準候補',
            'hero_job_key' => 'star_heaven_sage',
            'required_job_key' => 'star_crown_sage',
            'required_job_name' => '星冠導師',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => true,
            'benchmark' => [
                'measured_on' => '2026-09-10',
                'runs' => 500,
                'passes' => 312,
                'pass_rate' => 62.4,
                'basis' => 'ローカル「かんりにん」の装備・戦技・種族相性を保持し、能力を戦闘力350,003へ等比補正、固定500シード、開始HP/SP全快、保存・報酬なし',
                'note' => '同じ構成の実戦力252,271では0%。本番匿名17構成による二形態連続戦の再測定は未実施。',
            ],
            'phases' => [
                [
                    'key' => 'celestial_shell',
                    'trial_master_key' => 'asterion',
                    'enemy_name' => '天象魔導核アステリオン・星殻',
                    'label' => '第一形態・星殻相',
                    'image_path' => 'images/enemy/enemy_737.webp',
                    'type_name' => '星殻解析型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 45_000,
                    'str' => 4_000,
                    'def' => 8_500,
                    'agi' => 7_800,
                    'mag' => 12_000,
                    'spr' => 11_000,
                    'luk' => 6_500,
                    'actions' => [
                        [
                            'action_key' => 'celestial_analysis',
                            'name' => '天象解析',
                            'action_type' => 'magical_spr_down',
                            'selection_weight' => 100,
                            'power_percent' => 80,
                            'effect_percent' => 18,
                            'duration_turns' => 3,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
                [
                    'key' => 'celestial_core',
                    'trial_master_key' => 'asterion',
                    'label' => '第二形態・天象核相',
                    'image_path' => 'images/enemy/enemy_725.webp',
                    'type_name' => '崩星魔導型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 80_000,
                    'str' => 4_900,
                    'def' => 6_500,
                    'agi' => 8_500,
                    'mag' => 16_500,
                    'spr' => 8_000,
                    'luk' => 6_883,
                    'transition_title' => 'アステリオンの星殻を砕いた！',
                    'transition_body' => '露出した天象核が、星々の魔力を一点へ収束させる……！！',
                    'actions' => [
                        [
                            'action_key' => 'astral_volley',
                            'name' => '星雨連弾',
                            'action_type' => 'magical_multi_hit',
                            'selection_weight' => 100,
                            'power_percent' => 70,
                            'hit_count' => 2,
                            'cooldown_turns' => 2,
                        ],
                        [
                            'action_key' => 'stellar_collapse',
                            'name' => '星天崩落',
                            'action_type' => 'magical',
                            'selection_weight' => 100,
                            'power_percent' => 180,
                            'cooldown_turns' => 5,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 2,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 2,
                            'can_use_on_first_turn' => false,
                            'is_telegraphed' => true,
                            'telegraph_turns' => 1,
                            'can_be_guarded' => true,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
        'time_reader_traveler_balanced' => [
            'trial_key' => 'time_reader_traveler',
            'label' => '時詠みの旅人・標準候補',
            'hero_job_key' => 'time_reader_traveler',
            'required_job_key' => 'gold_crown_alchemist',
            'required_job_name' => '金冠錬師',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => false,
            'benchmark' => [
                'measured_on' => '2026-09-09',
                'runs' => 850,
                'passes' => 325,
                'pass_rate' => 38.2,
                'basis' => '本番の全冠位職マスター済み匿名スナップショット17人、開始HP/SP全快、装備・戦技・種族相性を保持、保存・報酬なし',
                'note' => '固定50シード×17人。35万未満16.0%、35万以上79.0%。全構成を35万へ等比補正した比較は40.6%。',
            ],
            'phases' => [
                [
                    'key' => 'time_observer',
                    'trial_master_key' => 'aeon',
                    'label' => '時環相',
                    'image_path' => 'images/enemy/enemy_732.webp',
                    'type_name' => '魔法敏捷型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 149_333,
                    'str' => 3_617,
                    'def' => 8_167,
                    'agi' => 14_758,
                    'mag' => 14_583,
                    'spr' => 9_217,
                    'luk' => 7_933,
                    'actions' => [
                        [
                            'action_key' => 'time_bind',
                            'name' => '時縛り',
                            'action_type' => 'magical_slow',
                            'selection_weight' => 100,
                            'power_percent' => 75,
                            'effect_percent' => 30,
                            'duration_turns' => 2,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'guarantee_first_use' => true,
                        ],
                        [
                            'action_key' => 'clockwork_barrage',
                            'name' => '刻針連奏',
                            'action_type' => 'magical_multi_hit',
                            'selection_weight' => 100,
                            'power_percent' => 85,
                            'hit_count' => 2,
                            'cooldown_turns' => 2,
                        ],
                        [
                            'action_key' => 'aeon_acceleration',
                            'name' => '時環加速',
                            'action_type' => 'self_speed_buff',
                            'selection_weight' => 100,
                            'effect_percent' => 25,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 6,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 6,
                            'can_use_on_first_turn' => false,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
        'heavenly_machina_chancellor_balanced' => [
            'trial_key' => 'heavenly_machina_chancellor',
            'label' => '天機宰相・標準候補',
            'hero_job_key' => 'heavenly_machina_chancellor',
            'required_job_key' => 'steel_crown_machina_sage',
            'required_job_name' => '鋼冠機導師',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => true,
            'benchmark' => [
                'measured_on' => '2026-09-09',
                'runs' => 850,
                'passes' => 183,
                'pass_rate' => 21.5,
                'basis' => '本番の全冠位職マスター済み匿名スナップショット17人、開始HP/SP全快、装備・戦技・種族相性を保持、保存・報酬なし',
                'note' => '固定50シード×17人。40万未満2.2%、40万以上57.0%。全構成を40万へ等比補正した比較は35.9%。',
            ],
            'phases' => [
                [
                    'key' => 'seeker',
                    'trial_master_key' => 'seeker',
                    'label' => '第1機構・偵察機',
                    'image_path' => 'images/enemy/enemy_727.webp',
                    'type_name' => '魔法高速型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 42_000,
                    'str' => 3_000,
                    'def' => 6_240,
                    'agi' => 12_571,
                    'mag' => 10_800,
                    'spr' => 7_440,
                    'luk' => 8_000,
                    'actions' => [
                        [
                            'action_key' => 'machina_scan',
                            'name' => '天機走査',
                            'action_type' => 'magical_slow',
                            'selection_weight' => 100,
                            'power_percent' => 75,
                            'effect_percent' => 20,
                            'duration_turns' => 2,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'guarantee_first_use' => true,
                        ],
                        [
                            'action_key' => 'seeker_barrage',
                            'name' => '追尾光弾',
                            'action_type' => 'magical_multi_hit',
                            'selection_weight' => 100,
                            'power_percent' => 72,
                            'hit_count' => 2,
                            'cooldown_turns' => 2,
                        ],
                    ],
                ],
                [
                    'key' => 'bastion',
                    'trial_master_key' => 'bastion',
                    'label' => '第2機構・重装機',
                    'image_path' => 'images/enemy/enemy_728.webp',
                    'type_name' => '物理重装型',
                    'max_hp' => 56_400,
                    'str' => 12_960,
                    'def' => 13_800,
                    'agi' => 4_800,
                    'mag' => 3_600,
                    'spr' => 11_400,
                    'luk' => 4_800,
                    'transition_title' => '天機偵察機シーカーを退けた！',
                    'transition_body' => '重い駆動音とともに、次なる機構が立ちはだかる！',
                    'actions' => [
                        [
                            'action_key' => 'fortress_pierce',
                            'name' => '破城杭',
                            'action_type' => 'def_pierce',
                            'selection_weight' => 100,
                            'power_percent' => 130,
                            'effect_percent' => 45,
                            'cooldown_turns' => 3,
                        ],
                        [
                            'action_key' => 'bastion_charge',
                            'name' => '天機重圧突進',
                            'action_type' => 'charge',
                            'selection_weight' => 100,
                            'power_percent' => 180,
                            'cooldown_turns' => 5,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 4,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 4,
                            'can_use_on_first_turn' => false,
                            'is_telegraphed' => true,
                            'telegraph_turns' => 1,
                            'can_be_guarded' => true,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
                [
                    'key' => 'oracle',
                    'trial_master_key' => 'oracle',
                    'label' => '第3機構・演算核',
                    'image_path' => 'images/enemy/enemy_729.webp',
                    'type_name' => '魔法演算型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 76_800,
                    'str' => 3_000,
                    'def' => 8_400,
                    'agi' => 7_771,
                    'mag' => 15_000,
                    'spr' => 12_000,
                    'luk' => 6_629,
                    'transition_title' => '天機重装機バスティオンを破壊した！',
                    'transition_body' => '砕けた装甲の奥で、天機の演算核が覚醒する！',
                    'actions' => [
                        [
                            'action_key' => 'oracle_analysis',
                            'name' => '勝機演算',
                            'action_type' => 'magical_spr_down',
                            'selection_weight' => 100,
                            'power_percent' => 80,
                            'effect_percent' => 20,
                            'duration_turns' => 3,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'guarantee_first_use' => true,
                        ],
                        [
                            'action_key' => 'oracle_cataclysm',
                            'name' => '天機収束砲',
                            'action_type' => 'magical',
                            'selection_weight' => 100,
                            'power_percent' => 185,
                            'cooldown_turns' => 5,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 4,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 4,
                            'can_use_on_first_turn' => false,
                            'is_telegraphed' => true,
                            'telegraph_turns' => 1,
                            'can_be_guarded' => true,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
        'sanctuary_judge_balanced' => [
            'trial_key' => 'sanctuary_judge',
            'label' => '聖域の審判者・標準候補',
            'hero_job_key' => 'sanctuary_judge',
            'required_job_key' => 'holy_crown_guardian',
            'required_job_name' => '聖冠守護者',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => false,
            'benchmark' => [
                'measured_on' => '2026-09-09',
                'runs' => 850,
                'passes' => 210,
                'pass_rate' => 24.7,
                'basis' => '本番の全冠位職マスター済み匿名スナップショット17人、開始HP/SP全快、装備・戦技・種族相性を保持、保存・報酬なし',
                'note' => '固定50シード×17人。40万未満5.1%、40万以上60.7%。全構成を40万へ等比補正した比較は50.4%。',
            ],
            'phases' => [
                [
                    'key' => 'sacred_judgment',
                    'trial_master_key' => 'justia',
                    'label' => '聖域相',
                    'image_path' => 'images/enemy/enemy_730.webp',
                    'type_name' => '魔法審判型',
                    'normal_attack_type' => 'magical',
                    'max_hp' => 171_429,
                    'str' => 5_714,
                    'def' => 14_857,
                    'agi' => 7_086,
                    'mag' => 14_286,
                    'spr' => 16_000,
                    'luk' => 6_857,
                    'actions' => [
                        [
                            'action_key' => 'sanctuary_seal',
                            'name' => '聖域封印',
                            'action_type' => 'magical_spr_down',
                            'selection_weight' => 100,
                            'power_percent' => 75,
                            'effect_percent' => 20,
                            'duration_turns' => 3,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 1,
                            'guarantee_first_use' => true,
                        ],
                        [
                            'action_key' => 'healing_denial',
                            'name' => '癒やしの禁令',
                            'action_type' => 'recovery_block',
                            'selection_weight' => 100,
                            'power_percent' => 85,
                            'effect_percent' => 40,
                            'duration_turns' => 3,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                        ],
                        [
                            'action_key' => 'final_judgment',
                            'name' => '聖天秤の審判',
                            'action_type' => 'magical',
                            'selection_weight' => 100,
                            'power_percent' => 180,
                            'cooldown_turns' => 5,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 4,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 4,
                            'can_use_on_first_turn' => false,
                            'is_telegraphed' => true,
                            'telegraph_turns' => 1,
                            'can_be_guarded' => true,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
        'storm_overlord_balanced' => [
            'trial_key' => 'storm_overlord',
            'label' => '荒天の覇者・標準候補',
            'hero_job_key' => 'storm_overlord',
            'required_job_key' => 'thunder_crown_fist_saint',
            'required_job_name' => '雷冠拳聖',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => false,
            'benchmark' => [
                'measured_on' => '2026-09-09',
                'runs' => 850,
                'passes' => 193,
                'pass_rate' => 22.7,
                'basis' => '本番の全冠位職マスター済み匿名スナップショット17人、開始HP/SP全快、装備・戦技・種族相性を保持、保存・報酬なし',
                'note' => '固定50シード×17人。40万未満5.6%、40万以上54.0%。全構成を40万へ等比補正した比較は37.4%。',
            ],
            'phases' => [
                [
                    'key' => 'thunderstorm',
                    'trial_master_key' => 'tempesta',
                    'label' => '雷嵐相',
                    'image_path' => 'images/enemy/enemy_733.webp',
                    'type_name' => '物理高速型',
                    'max_hp' => 91_429,
                    'str' => 10_571,
                    'def' => 7_086,
                    'agi' => 12_286,
                    'mag' => 4_000,
                    'spr' => 6_857,
                    'luk' => 7_429,
                    'actions' => [
                        [
                            'action_key' => 'storm_barrage',
                            'name' => '迅雷連牙',
                            'action_type' => 'multi_hit',
                            'selection_weight' => 100,
                            'power_percent' => 65,
                            'hit_count' => 2,
                            'cooldown_turns' => 2,
                        ],
                        [
                            'action_key' => 'thunder_critical',
                            'name' => '天雷急所撃',
                            'action_type' => 'critical_strike',
                            'selection_weight' => 100,
                            'power_percent' => 130,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 3,
                        ],
                        [
                            'action_key' => 'storm_deepening',
                            'name' => '荒天深化',
                            'action_type' => 'self_buff',
                            'selection_weight' => 100,
                            'effect_percent' => 10,
                            'cooldown_turns' => 4,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 6,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 6,
                            'can_use_on_first_turn' => false,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
        'silver_guardian_king_balanced' => [
            'trial_key' => 'silver_guardian_king',
            'label' => '白銀の守護王・標準候補',
            'hero_job_key' => 'silver_guardian_king',
            'required_job_key' => 'war_crown_commander',
            'required_job_name' => '戦冠司令',
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => false,
            'benchmark' => [
                'measured_on' => '2026-09-09',
                'runs' => 850,
                'passes' => 127,
                'pass_rate' => 14.9,
                'basis' => '本番の全冠位職マスター済み匿名スナップショット17人、開始HP/SP全快、装備・戦技・種族相性を保持、保存・報酬なし',
                'note' => '固定50シード×17人。40万未満0.7%、40万以上41.0%。全構成を40万へ等比補正した比較は24.2%。',
            ],
            'phases' => [
                [
                    'key' => 'silver_fortress',
                    'trial_master_key' => 'argeon',
                    'label' => '白銀城塞相',
                    'image_path' => 'images/enemy/enemy_734.webp',
                    'type_name' => '物理堅牢型',
                    'max_hp' => 142_857,
                    'str' => 11_429,
                    'def' => 15_429,
                    'agi' => 5_143,
                    'mag' => 3_429,
                    'spr' => 13_143,
                    'luk' => 5_714,
                    'actions' => [
                        [
                            'action_key' => 'silver_reversal',
                            'name' => '白銀反衝',
                            'action_type' => 'def_pierce',
                            'selection_weight' => 100,
                            'power_percent' => 140,
                            'effect_percent' => 50,
                            'cooldown_turns' => 3,
                        ],
                        [
                            'action_key' => 'fortress_judgment',
                            'name' => '城塞圧壊',
                            'action_type' => 'current_hp_percent',
                            'selection_weight' => 100,
                            'effect_percent' => 30,
                            'cooldown_turns' => 5,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 3,
                            'can_use_on_first_turn' => false,
                        ],
                        [
                            'action_key' => 'silver_charge',
                            'name' => '白銀城塞突撃',
                            'action_type' => 'charge',
                            'selection_weight' => 100,
                            'power_percent' => 200,
                            'cooldown_turns' => 5,
                            'max_uses_per_battle' => 2,
                            'trigger_turn' => 5,
                            'trigger_key' => 'turn_at_least',
                            'trigger_value' => 5,
                            'can_use_on_first_turn' => false,
                            'is_telegraphed' => true,
                            'telegraph_turns' => 1,
                            'can_be_guarded' => true,
                            'guarantee_first_use' => true,
                        ],
                    ],
                ],
            ],
        ],
        // 最終陣は人間が承認した45万目安の調整候補。実プレイヤー構成での最終裁定は未実施。
        'azure_dragon_warrior_king_candidate' => [
            'trial_key' => 'azure_dragon_warrior_king',
            'label' => '蒼竜武王・45万調整候補',
            'hero_job_key' => 'azure_dragon_warrior_king',
            'required_job_key' => 'dragon_crown_lance_general',
            'required_job_name' => '竜冠槍将',
            'balance_status' => 'candidate',
            'benchmark' => [
                'measured_on' => '2026-10-06',
                'runs' => 1000, 'passes' => 809, 'pass_rate' => 80.9,
                'basis' => '人工の冠位10職の能力比率を戦力45万へ等比補正、既存冠位戦技3種を各30%で使用、各100固定シード、HP/SP全快、実BattleService、保存・報酬なし',
                'note' => '人工構成による機構確認。装備・種族相性・遺物・支援・戦技v2なし。40万 760/1000、50万 863/1000。実プレイヤー構成の最終難易度裁定は未実施。',
            ],
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => false,
            'phases' => [[
                'key' => 'azure_dragon', 'trial_master_key' => 'azragion',
                'label' => '蒼穹古竜相', 'image_path' => 'images/enemy/enemy_726.webp',
                'type_name' => '物理貫通型', 'normal_attack_type' => 'physical',
                'max_hp' => 160_000, 'str' => 14_000, 'def' => 11_000,
                'agi' => 13_000, 'mag' => 4_500, 'spr' => 12_000, 'luk' => 8_000,
                'actions' => [
                    ['action_key' => 'azure_piercing_fang', 'name' => '蒼穹穿牙',
                        'action_type' => 'def_pierce', 'selection_weight' => 100,
                        'power_percent' => 125, 'effect_percent' => 40, 'cooldown_turns' => 3],
                    ['action_key' => 'azure_claw_dance', 'name' => '蒼竜連爪',
                        'action_type' => 'multi_hit', 'selection_weight' => 100,
                        'power_percent' => 65, 'hit_count' => 2, 'cooldown_turns' => 2],
                    ['action_key' => 'azure_king_strike', 'name' => '蒼穹竜王撃',
                        'action_type' => 'charge', 'selection_weight' => 100,
                        'power_percent' => 210, 'cooldown_turns' => 5, 'max_uses_per_battle' => 2,
                        'trigger_turn' => 4, 'trigger_key' => 'turn_at_least', 'trigger_value' => 4,
                        'can_use_on_first_turn' => false, 'is_telegraphed' => true,
                        'telegraph_turns' => 1, 'can_be_guarded' => true, 'guarantee_first_use' => true],
                ],
            ]],
        ],
        'phantom_funeral_demon_king_candidate' => [
            'trial_key' => 'phantom_funeral_demon_king',
            'label' => '幻葬の魔王・45万調整候補',
            'hero_job_key' => 'phantom_funeral_demon_king',
            'required_job_key' => 'black_crown_magic_knight',
            'required_job_name' => '黒冠魔騎士',
            'balance_status' => 'candidate',
            'benchmark' => [
                'measured_on' => '2026-10-06',
                'runs' => 1000, 'passes' => 786, 'pass_rate' => 78.6,
                'basis' => '人工の冠位10職の能力比率を戦力45万へ等比補正、既存冠位戦技3種を各30%で使用、各100固定シード、HP/SP全快、実BattleService、保存・報酬なし',
                'note' => '人工構成による機構確認。装備・種族相性・遺物・支援・戦技v2なし。40万 729/1000、50万 868/1000。実プレイヤー構成の最終難易度裁定は未実施。',
            ],
            'start_full_hp' => true,
            'carry_hp_sp_between_phases' => false,
            'phases' => [[
                'key' => 'soul_funeral', 'trial_master_key' => 'necrodia',
                'label' => '魂葬王相', 'image_path' => 'images/enemy/enemy_731.webp',
                'type_name' => '魔法吸収型', 'normal_attack_type' => 'magical',
                'max_hp' => 192_000, 'str' => 6_500, 'def' => 9_500,
                'agi' => 9_000, 'mag' => 18_000, 'spr' => 16_000, 'luk' => 8_000,
                'actions' => [
                    ['action_key' => 'soul_fire_break', 'name' => '魂火崩し',
                        'action_type' => 'magical_spr_down', 'selection_weight' => 100,
                        'power_percent' => 75, 'effect_percent' => 20, 'duration_turns' => 3,
                        'cooldown_turns' => 4, 'max_uses_per_battle' => 2,
                        'trigger_turn' => 1, 'guarantee_first_use' => true],
                    ['action_key' => 'soul_funeral_drain', 'name' => '魂葬吸命',
                        'action_type' => 'magical_drain', 'selection_weight' => 100,
                        'power_percent' => 100, 'effect_percent' => 35,
                        'cooldown_turns' => 3, 'max_uses_per_battle' => 4],
                    ['action_key' => 'phantom_final_bell', 'name' => '幻葬の終鐘',
                        'action_type' => 'magical', 'selection_weight' => 100,
                        'power_percent' => 180, 'cooldown_turns' => 5, 'max_uses_per_battle' => 2,
                        'trigger_turn' => 4, 'trigger_key' => 'turn_at_least', 'trigger_value' => 4,
                        'can_use_on_first_turn' => false, 'is_telegraphed' => true,
                        'telegraph_turns' => 1, 'can_be_guarded' => true, 'guarantee_first_use' => true],
                ],
            ]],
        ],
    ],
];
