<?php

return [
    'weapon' => [
        '剣' => 'images/weapon/nameless-sword.webp',
        '短剣' => 'images/weapon/nameless-dagger.webp',
        '槍' => 'images/weapon/nameless-spear.webp',
        '斧' => 'images/weapon/nameless-axe.webp',
        '弓' => 'images/weapon/nameless-bow.webp',
        '杖' => 'images/weapon/nameless-staff.webp',
        '魔導書' => 'images/weapon/nameless-grimoire.webp',
        '銃' => 'images/weapon/nameless-gun.webp',
        '拳具' => 'images/weapon/nameless-gauntlet.webp',
    ],
    // 武器の外見だけを強化値から選ぶ。初期配布・図鑑は上の基本画像を使用。
    'weapon_forge_stages' => [
        '剣' => [
            20 => 'images/weapon/nameless-sword-forge-20.webp',
            40 => 'images/weapon/nameless-sword-forge-40.webp',
            60 => 'images/weapon/nameless-sword-forge-60.webp',
            80 => 'images/weapon/nameless-sword-forge-80.webp',
            99 => 'images/weapon/nameless-sword-forge-99.webp',
        ],
        '短剣' => [
            20 => 'images/weapon/nameless-dagger-forge-20.webp',
            40 => 'images/weapon/nameless-dagger-forge-40.webp',
            60 => 'images/weapon/nameless-dagger-forge-60.webp',
            80 => 'images/weapon/nameless-dagger-forge-80.webp',
            99 => 'images/weapon/nameless-dagger-forge-99.webp',
        ],
        '槍' => [
            20 => 'images/weapon/nameless-spear-forge-20.webp',
            40 => 'images/weapon/nameless-spear-forge-40.webp',
            60 => 'images/weapon/nameless-spear-forge-60.webp',
            80 => 'images/weapon/nameless-spear-forge-80.webp',
            99 => 'images/weapon/nameless-spear-forge-99.webp',
        ],
        '斧' => [
            20 => 'images/weapon/nameless-axe-forge-20.webp',
            40 => 'images/weapon/nameless-axe-forge-40.webp',
            60 => 'images/weapon/nameless-axe-forge-60.webp',
            80 => 'images/weapon/nameless-axe-forge-80.webp',
            99 => 'images/weapon/nameless-axe-forge-99.webp',
        ],
        '弓' => [
            20 => 'images/weapon/nameless-bow-forge-20.webp',
            40 => 'images/weapon/nameless-bow-forge-40.webp',
            60 => 'images/weapon/nameless-bow-forge-60.webp',
            80 => 'images/weapon/nameless-bow-forge-80.webp',
            99 => 'images/weapon/nameless-bow-forge-99.webp',
        ],
        '杖' => [
            20 => 'images/weapon/nameless-staff-forge-20.webp',
            40 => 'images/weapon/nameless-staff-forge-40.webp',
            60 => 'images/weapon/nameless-staff-forge-60.webp',
            80 => 'images/weapon/nameless-staff-forge-80.webp',
            99 => 'images/weapon/nameless-staff-forge-99.webp',
        ],
        '魔導書' => [
            20 => 'images/weapon/nameless-grimoire-forge-20.webp',
            40 => 'images/weapon/nameless-grimoire-forge-40.webp',
            60 => 'images/weapon/nameless-grimoire-forge-60.webp',
            80 => 'images/weapon/nameless-grimoire-forge-80.webp',
            99 => 'images/weapon/nameless-grimoire-forge-99.webp',
        ],
        '銃' => [
            20 => 'images/weapon/nameless-gun-forge-20.webp',
            40 => 'images/weapon/nameless-gun-forge-40.webp',
            60 => 'images/weapon/nameless-gun-forge-60.webp',
            80 => 'images/weapon/nameless-gun-forge-80.webp',
            99 => 'images/weapon/nameless-gun-forge-99.webp',
        ],
        '拳具' => [
            20 => 'images/weapon/nameless-gauntlet-forge-20.webp',
            40 => 'images/weapon/nameless-gauntlet-forge-40.webp',
            60 => 'images/weapon/nameless-gauntlet-forge-60.webp',
            80 => 'images/weapon/nameless-gauntlet-forge-80.webp',
            99 => 'images/weapon/nameless-gauntlet-forge-99.webp',
        ],
    ],
    'armor' => [
        '鎧' => 'images/weapon/nameless-cuirass.webp',
        '服' => 'images/weapon/nameless-tunic.webp',
        'ローブ' => 'images/weapon/nameless-robe.webp',
        '外套' => 'images/weapon/nameless-cloak.webp',
        '盾' => 'images/weapon/nameless-shield.webp',
        '装束' => 'images/weapon/nameless-garb.webp',
    ],
    'accessory' => [
        '指輪' => 'images/icon/icon_238.webp',
        '腕輪' => 'images/icon/icon_238.webp',
        '首飾り' => 'images/icon/icon_238.webp',
        '羽飾り' => 'images/icon/icon_238.webp',
        '護符' => 'images/icon/icon_238.webp',
    ],
];
