<?php

return [
    'eligible_ranks' => ['common', 'skilled', 'hero'],

    /*
     * Field encounters are rolled through the existing rare "旅の出会い"
     * chance in ExplorationService. This file only controls where each NPC can
     * appear after that chance has already passed.
     */
    'locations' => [
        1 => ['city_id' => 1],
        2 => ['city_id' => 1],
        3 => ['city_id' => 1],
        4 => ['city_id' => 1],
        5 => ['city_id' => 1, 'area_id' => 1],
        6 => ['city_id' => 1, 'area_id' => 2],
        7 => ['city_id' => 1, 'area_id' => 3],
        8 => ['city_id' => 1],
        9 => ['city_id' => 1],
        10 => ['city_id' => 1],
        11 => ['city_id' => 2],
        12 => ['city_id' => 2],
        13 => ['city_id' => 3],
        14 => ['city_id' => 4],
        15 => ['city_id' => 5],
        16 => ['city_id' => 6],
        17 => ['city_id' => 7],
        18 => ['city_id' => 8],
        19 => ['city_id' => 9],
        20 => ['city_id' => 10],
        21 => ['city_id' => 1],
        22 => ['city_id' => 1],
        23 => ['city_id' => 1],
        24 => ['city_id' => 1],
        25 => ['city_id' => 1],
        26 => ['city_id' => 1],
        27 => ['city_id' => 1],
        28 => ['city_id' => 5],
        29 => ['city_id' => 1],
        30 => ['city_id' => 1],
        31 => ['city_id' => 1],
        32 => ['city_id' => 1],
        33 => ['city_id' => 1],
        34 => ['city_id' => 1],
        35 => ['city_id' => 1],
        36 => ['city_id' => 1],
        37 => ['city_id' => 1],
        38 => ['city_id' => 1],
        39 => ['city_id' => 1],
        40 => ['city_id' => 1],
        41 => ['city_id' => 1],
        42 => ['city_id' => 7],
        43 => ['city_id' => 4],
        44 => ['city_id' => 9],
        45 => ['city_id' => 6],
        46 => ['city_id' => 9],
        47 => ['city_id' => 8],
        48 => ['city_id' => 3],
        49 => ['city_id' => 4],
        50 => ['city_id' => 2],
        51 => ['city_id' => 8],
        52 => ['city_id' => 6],
        53 => ['city_id' => 5],
        54 => ['city_id' => 3],
        55 => ['city_id' => 2],
        56 => ['city_id' => 1],
        57 => ['city_id' => 7],
        58 => ['city_id' => 9],
        59 => ['city_id' => 8],
        60 => ['city_id' => 10],
    ],
];
