<?php

return [
    'star_tree' => [
        'enabled' => env('STAR_TREE_TOWER_ENABLED', false),
        'tower_key' => 'star_tree_tower',
        // Clone-oriented surface settings: change these first when reusing the tower flow for another tower.
        'display' => [
            'name' => '星樹の塔',
            'log_label' => '星樹の塔',
            'ranking_title' => '星樹の塔ランキング',
            'location_name' => '精霊の森エルフィア',
            'generic_enemy_name' => '星樹の魔物',
            'disabled_message' => '星樹の塔は現在準備中です。',
            'locked_message' => '星樹の塔はまだ解放されていません。',
            'empty_state_title' => '星樹の塔は静まり返っている',
            'exit_label' => '星樹の塔から出る',
            'merchant_name' => '星灯の行商人',
            'merchant_found_title' => '星灯の行商人を見つけた',
            'merchant_intro' => '戦いを終えた枝道の先で、小さな灯りを掲げた行商人が待っている。',
            'merchant_appeared_message' => '星灯の行商人が、枝の上に腰かけていた。',
            'merchant_none_message' => '星灯の行商人はいません。',
            'merchant_pending_message' => '星灯の行商人が待っています。購入するか、見送ってから次の階へ進んでください。',
            'merchant_skipped_message' => '星灯の行商人を見送りました。',
            'public_log_label' => '星梯の塔',
            'breath_name' => '星樹の息吹',
            'scout_flavor' => '星樹の気配を読み、次に立ちはだかる相手を見定めた。',
        ],
        'assets' => [
            'symbol' => 'images/tower/01_tower_symbol.webp',
            'background' => 'images/tower/01_tower.webp',
            'logo' => 'images/tower/01_tower_logo.webp',
            'merchant_icon' => 'images/icon/icon_082.webp',
        ],
        'unlock' => [
            'required_city_id' => null,
        ],
        'win_recover_hp_rate' => 5,
        'win_recover_mp_rate' => 5,
        'victory_exp_base' => 50,
        'victory_exp_per_floor' => 10,
        'victory_job_exp' => 1,
        'merchant_rate' => 5,
        'merchant_cooldown_floors' => 5,
        'merchant_hp_item_price' => 500,
        'merchant_hp_item_recover_rate' => 25,
        'merchant_mp_item_price' => 800,
        'merchant_mp_item_recover_rate' => 25,
        'merchant_ward_item_price' => 1200,
        'merchant_ward_damage_reduction_rate' => 20,
        'merchant_items' => [
            'hp' => [
                'key' => 'star_leaf_herb',
                'name' => '星葉の薬草',
                'description_template' => '塔内HPを最大HPの{rate}%回復',
            ],
            'sp' => [
                'key' => 'moon_dew_vial',
                'name' => '月露の小瓶',
                'description_template' => '塔内SPを最大SPの{rate}%回復',
            ],
            'ward' => [
                'key' => 'kodama_ward',
                'name' => '木霊の護符',
                'description_template' => '次の戦闘だけ被ダメージを{rate}%軽減',
            ],
        ],
        'strategy_full_sp_cost_rate' => 8,
        'strategy_full_exp_bonus_rate' => 15,
        'strategy_breathe_recover_rate' => 10,
        'strategy_breathe_enemy_power_rate' => 5,
        'strategy_cautious_enemy_agi_luk_down_rate' => 15,
        'seed_floor_count' => 100,
        'stamina_cost_schedule' => [
            1 => 1,
            11 => 1,
            21 => 2,
            31 => 2,
            41 => 3,
            51 => 3,
            61 => 4,
            71 => 4,
            81 => 5,
            91 => 5,
        ],
        'enemy_scaling' => [
            'late_floor_threshold' => 40,
            'max_hp' => ['base' => 500, 'floor' => 90, 'floor_square' => 6, 'late_square' => 15],
            'str' => ['base' => 80, 'floor' => 7, 'floor_square' => 0.10, 'late_square' => 0.20],
            'def' => ['base' => 30, 'floor' => 5, 'floor_square' => 0.04, 'late_square' => 0.05],
            'mag' => ['base' => 70, 'floor' => 7, 'floor_square' => 0.12, 'late_square' => 0.22],
            'spr' => ['base' => 30, 'floor' => 5, 'floor_square' => 0.04, 'late_square' => 0.05],
            'agi' => ['base' => 40, 'floor' => 5, 'floor_square' => 0.05, 'late_square' => 0.08],
            'luk' => ['base' => 20, 'floor' => 2, 'floor_square' => 0, 'late_square' => 0],
        ],
        'enemy_profile_multipliers' => [
            'physical' => [
                'max_hp' => 1.00,
                'str' => 1.10,
                'def' => 1.05,
                'mag' => 0.70,
                'spr' => 0.95,
                'agi' => 1.00,
                'luk' => 1.00,
            ],
            'magical' => [
                'max_hp' => 1.00,
                'str' => 0.70,
                'def' => 0.95,
                'mag' => 1.10,
                'spr' => 1.05,
                'agi' => 1.00,
                'luk' => 1.00,
            ],
            'hybrid' => [
                'max_hp' => 1.10,
                'str' => 0.95,
                'def' => 1.00,
                'mag' => 0.95,
                'spr' => 1.00,
                'agi' => 1.00,
                'luk' => 1.00,
            ],
            'speed' => [
                'max_hp' => 0.95,
                'str' => 1.00,
                'def' => 0.90,
                'mag' => 0.90,
                'spr' => 0.90,
                'agi' => 1.20,
                'luk' => 1.00,
            ],
        ],
    ],
];
