<?php

return [
    'image_path' => 'images/map/map01.webp',
    'active_window_minutes' => 30,

    'cities' => [
        [
            'city_name' => '王都アークレア',
            'label' => '王都アークレア',
            'short_label' => 'アークレア',
            'x_percent' => 27,
            'y_percent' => 74,
        ],
        [
            'city_name' => '港町マリネス',
            'label' => '港町マリネス',
            'short_label' => 'マリネス',
            'x_percent' => 12,
            'y_percent' => 56,
        ],
        [
            'city_name' => '精霊の森エルフィア',
            'label' => '精霊の森エルフィア',
            'short_label' => 'エルフィア',
            'x_percent' => 49,
            'y_percent' => 52,
        ],
        [
            'city_name' => '鍛冶街グランベルグ',
            'label' => '鍛冶街グランベルグ',
            'short_label' => 'グランベルグ',
            'x_percent' => 28,
            'y_percent' => 34,
        ],
        [
            'city_name' => '魔王城ヴァルゼリア',
            'label' => '魔王城ヴァルゼリア',
            'short_label' => 'ヴァルゼリア',
            'x_percent' => 52,
            'y_percent' => 13,
        ],
        [
            'city_name' => '雪原の町フロストリア',
            'label' => '雪原の町フロストリア',
            'short_label' => 'フロストリア',
            'x_percent' => 74,
            'y_percent' => 24,
        ],
        [
            'city_name' => '天空神殿セレスティア',
            'label' => '天空神殿セレスティア',
            'short_label' => 'セレスティア',
            'x_percent' => 87,
            'y_percent' => 42,
        ],
        [
            'city_name' => '魔導学院ルミナス',
            'label' => '魔導学院ルミナス',
            'short_label' => 'ルミナス',
            'x_percent' => 76,
            'y_percent' => 56,
        ],
        [
            'city_name' => '死霊街ネクロム',
            'label' => '死霊街ネクロム',
            'short_label' => 'ネクロム',
            'x_percent' => 60,
            'y_percent' => 73,
        ],
        [
            'city_name' => '砂漠の宿場サンドラ',
            'label' => '砂漠の宿場サンドラ',
            'short_label' => 'サンドラ',
            'x_percent' => 59,
            'y_percent' => 88,
        ],
    ],

    'dungeons' => [
        1 => ['x_percent' => 25, 'y_percent' => 72], 2 => ['x_percent' => 32, 'y_percent' => 70], 3 => ['x_percent' => 35, 'y_percent' => 78], 4 => ['x_percent' => 21, 'y_percent' => 75],
        5 => ['x_percent' => 31, 'y_percent' => 84], 6 => ['x_percent' => 38, 'y_percent' => 71], 7 => ['x_percent' => 24, 'y_percent' => 81],
        8 => ['x_percent' => 10, 'y_percent' => 53], 9 => ['x_percent' => 14, 'y_percent' => 60], 10 => ['x_percent' => 7, 'y_percent' => 64], 11 => ['x_percent' => 16, 'y_percent' => 55],
        12 => ['x_percent' => 10, 'y_percent' => 68], 13 => ['x_percent' => 17, 'y_percent' => 64], 14 => ['x_percent' => 14, 'y_percent' => 49],
        15 => ['x_percent' => 46, 'y_percent' => 50], 16 => ['x_percent' => 49, 'y_percent' => 55], 17 => ['x_percent' => 48, 'y_percent' => 62], 18 => ['x_percent' => 54, 'y_percent' => 57],
        19 => ['x_percent' => 54, 'y_percent' => 48], 20 => ['x_percent' => 44, 'y_percent' => 58], 21 => ['x_percent' => 58, 'y_percent' => 53],
        22 => ['x_percent' => 24, 'y_percent' => 31], 23 => ['x_percent' => 30, 'y_percent' => 36], 24 => ['x_percent' => 33, 'y_percent' => 31], 25 => ['x_percent' => 24, 'y_percent' => 41],
        26 => ['x_percent' => 36, 'y_percent' => 41], 27 => ['x_percent' => 30, 'y_percent' => 27], 28 => ['x_percent' => 19, 'y_percent' => 34],
        29 => ['x_percent' => 70, 'y_percent' => 25], 30 => ['x_percent' => 75, 'y_percent' => 21], 31 => ['x_percent' => 80, 'y_percent' => 31], 32 => ['x_percent' => 68, 'y_percent' => 35],
        33 => ['x_percent' => 82, 'y_percent' => 24], 34 => ['x_percent' => 85, 'y_percent' => 32], 35 => ['x_percent' => 75, 'y_percent' => 15],
        36 => ['x_percent' => 57, 'y_percent' => 87], 37 => ['x_percent' => 62, 'y_percent' => 83], 38 => ['x_percent' => 62, 'y_percent' => 91], 39 => ['x_percent' => 56, 'y_percent' => 95],
        40 => ['x_percent' => 70, 'y_percent' => 89], 41 => ['x_percent' => 51, 'y_percent' => 82], 42 => ['x_percent' => 63, 'y_percent' => 94],
        43 => ['x_percent' => 74, 'y_percent' => 53], 44 => ['x_percent' => 78, 'y_percent' => 50], 45 => ['x_percent' => 82, 'y_percent' => 57], 46 => ['x_percent' => 72, 'y_percent' => 61],
        47 => ['x_percent' => 83, 'y_percent' => 47], 48 => ['x_percent' => 69, 'y_percent' => 56], 49 => ['x_percent' => 76, 'y_percent' => 64],
        50 => ['x_percent' => 55, 'y_percent' => 69], 51 => ['x_percent' => 60, 'y_percent' => 73], 52 => ['x_percent' => 65, 'y_percent' => 71], 53 => ['x_percent' => 61, 'y_percent' => 80],
        54 => ['x_percent' => 67, 'y_percent' => 77], 55 => ['x_percent' => 54, 'y_percent' => 76], 56 => ['x_percent' => 62, 'y_percent' => 66],
        57 => ['x_percent' => 84, 'y_percent' => 43], 58 => ['x_percent' => 88, 'y_percent' => 39], 59 => ['x_percent' => 91, 'y_percent' => 45], 60 => ['x_percent' => 82, 'y_percent' => 48],
        61 => ['x_percent' => 90, 'y_percent' => 37], 62 => ['x_percent' => 86, 'y_percent' => 34], 63 => ['x_percent' => 91, 'y_percent' => 50],
        64 => ['x_percent' => 50, 'y_percent' => 17], 65 => ['x_percent' => 53, 'y_percent' => 20], 66 => ['x_percent' => 55, 'y_percent' => 15], 67 => ['x_percent' => 47, 'y_percent' => 13],
        68 => ['x_percent' => 52, 'y_percent' => 10], 69 => ['x_percent' => 55, 'y_percent' => 10], 70 => ['x_percent' => 49, 'y_percent' => 7],
        71 => ['x_percent' => 57, 'y_percent' => 67], 72 => ['x_percent' => 32, 'y_percent' => 30], 73 => ['x_percent' => 88, 'y_percent' => 36], 74 => ['x_percent' => 75, 'y_percent' => 51],
        75 => ['x_percent' => 18, 'y_percent' => 65], 76 => ['x_percent' => 31, 'y_percent' => 60], 77 => ['x_percent' => 40, 'y_percent' => 42], 78 => ['x_percent' => 46, 'y_percent' => 33],
        79 => ['x_percent' => 64, 'y_percent' => 29], 80 => ['x_percent' => 67, 'y_percent' => 74], 81 => ['x_percent' => 70, 'y_percent' => 63], 82 => ['x_percent' => 75, 'y_percent' => 45], 83 => ['x_percent' => 68, 'y_percent' => 22],
    ],
];
