<x-layouts.facility :title="$shop->name" headerIconImage="images/icon/icon_032.webp" bgImage="images/facilities/item.webp" :exitUrl="route('shops.index')" exitLabel="個人店舗一覧へ戻る">
    <div class="mx-auto w-full space-y-4 pb-10">
        <section class="rounded-lg border border-amber-200 bg-white p-4 shadow-sm"><div class="flex justify-between gap-3"><div><div class="text-xl font-black text-slate-900">{{ $shop->name }}</div><div class="mt-1 text-sm font-bold text-slate-500">店主：{{ $shop->character?->name }} / {{ $shop->description }}</div></div>@if((int)$shop->character_id === (int)$character->id)<a href="{{ route('shops.mine') }}" class="rounded border border-amber-300 bg-amber-50 px-3 py-2 text-xs font-black text-amber-800">自分の商店を編集</a>@else<form method="POST" action="{{ $isFavorite ? route('shops.unfavorite', $shop) : route('shops.favorite', $shop) }}">@csrf @if($isFavorite) @method('DELETE') @endif<button class="rounded border px-3 py-2 text-xs font-black text-amber-700">{{ $isFavorite ? 'お気に入り解除' : 'お気に入り' }}</button></form>@endif</div></section>
        @if(session('error'))<div class="rounded bg-red-50 p-3 text-sm font-bold text-red-700">{{ session('error') }}</div>@endif
        <section class="space-y-2"><h3 class="font-black text-slate-800">ヴァルモンの卵</h3>@forelse($eggListings as $listing)<div class="rounded-lg border border-violet-200 bg-white p-3"><div class="flex items-center justify-between gap-2"><div><div class="font-black text-slate-900">{{ $listing->display_name_snapshot }}</div><div class="text-xs font-bold text-slate-500">期限 {{ $listing->expires_at->format('m/d H:i') }}</div></div><div class="text-right"><div class="font-black text-amber-700">{{ number_format($listing->listing_price) }}G</div>@if((int)$listing->seller_character_id !== (int)$character->id)<form method="POST" action="{{ route('shops.eggs.buy', $listing) }}">@csrf<button class="mt-1 rounded bg-violet-600 px-3 py-1.5 text-xs font-black text-white">購入</button></form>@endif</div></div></div>@empty<p class="rounded border border-dashed bg-white p-4 text-sm font-bold text-slate-500">出品中の卵はありません。</p>@endforelse</section>
        <section class="space-y-2"><h3 class="font-black text-slate-800">素材</h3>@forelse($materialListings as $listing)<a href="{{ route('market.materials.show', $listing->material_id) }}" class="flex justify-between rounded-lg border bg-white p-3 text-sm font-bold"><span>{{ $listing->material?->displayName() }} ×{{ $listing->remaining_quantity }}</span><span>{{ number_format($listing->unit_price) }}G</span></a>@empty<p class="rounded border border-dashed bg-white p-4 text-sm font-bold text-slate-500">出品中の素材はありません。</p>@endforelse</section>
        <section class="space-y-2"><h3 class="font-black text-slate-800">装備</h3>@forelse($equipmentListings as $listing)<a href="{{ route('equipment-market.show', $listing) }}" class="flex justify-between rounded-lg border bg-white p-3 text-sm font-bold"><span>{{ $listing->display_name_snapshot }}</span><span>{{ number_format($listing->listing_price) }}G</span></a>@empty<p class="rounded border border-dashed bg-white p-4 text-sm font-bold text-slate-500">出品中の装備はありません。</p>@endforelse</section>
    </div>
</x-layouts.facility>
